// Generated by bynkc — do not edit by hand.
// context shop.orders

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type __DurableObjectState, type __DurableObjectNamespace, __StateRegistry, __makeAgent, type __AgentWire, __decodeAgentArgs, __encodeAgentResult, __rehydrationViolation, type __JsonValue, type __BoundaryError, type __ServiceBinding, __callService, __boundaryError } from "../../../runtime.js";

import { Line } from "./types.js";
import type { Stamp } from "./stamp.js";
import * as handlers_shop_fees from "../../shop-fees/handlers.js";
import * as handlers_shop_orders from "../../shop-orders/handlers.js";

import type * as shop_fees from "../../shop-fees/handlers.js";
import type * as shop_payment from "../../shop-payment/handlers.js";

export interface BookState {
  readonly last: Option<Line>;
  readonly count: number;
}

const __BookRegistry = new __StateRegistry();
function __zeroOfBookState(): BookState { return { last: None, count: 0 }; }

function __rehydrateBookState(s: BookState, stored: BookState): void {
  if (globalThis.Object.prototype.hasOwnProperty.call(stored, "last")) { const __r = __deserialise_Option_Line((s.last as unknown as __JsonValue), "last"); if (__r.tag === "Err") throw __rehydrationViolation("Book", __r.error); (s as { -readonly [K in keyof typeof s]: (typeof s)[K] }).last = __r.value as unknown as (typeof s)["last"]; }
  if (globalThis.Object.prototype.hasOwnProperty.call(stored, "count")) { const __r = ((__v) => typeof __v !== "number" ? Err({ kind: "StructuralMismatch", path: "count", expected: "safe integer", actual: typeof __v } as __BoundaryError) : globalThis.Number.isSafeInteger(__v) ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "count", expected: "safe integer", actual: String(__v) } as __BoundaryError))((s.count as unknown as __JsonValue)); if (__r.tag === "Err") throw __rehydrationViolation("Book", __r.error); (s as { -readonly [K in keyof typeof s]: (typeof s)[K] }).count = __r.value as unknown as (typeof s)["count"]; }
}

function __encodeBookState(s: BookState): globalThis.Record<string, unknown> {
  return { ...s, last: __serialise_Option_Line(s.last), count: ((v: number) => { if (!globalThis.Number.isSafeInteger(v)) throw new globalThis.Error("Int outside the safe-integer range at boundary"); return v as __JsonValue; })(s.count) };
}

export class Book {
  state: __DurableObjectState;
  private __env: unknown;
  constructor(state: __DurableObjectState, env?: unknown) {
    this.state = state;
    this.__env = env;
  }

  private async loadState(): globalThis.Promise<BookState> {
    const stored = await this.state.storage.get<BookState>("state");
    if (stored === undefined) return __zeroOfBookState();
    const __merged = { ...__zeroOfBookState(), ...stored };
    __rehydrateBookState(__merged, stored);
    return __merged;
  }

  private async commitState(s: BookState): globalThis.Promise<void> {
    await this.state.storage.put("state", __encodeBookState(s));
  }

  async add(line: Line, deps: { Stamp: Stamp; Fees: shop_fees.Fees }): globalThis.Promise<number> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const f = await deps.Fees.fee();
      const s = await deps.Stamp.next();
      __state.last = Some(line);
      const __r0 = await (() => { __state.count = ((c) => c + line.qty)(__state.count); return undefined; })();
      return __state.count + s + f;
    })();
    await this.commitState(__state);
    return __result;
  }

  async fetch(request: globalThis.Request): globalThis.Promise<globalThis.Response> {
    const url = new globalThis.URL(request.url);
    if (url.pathname.startsWith("/_bynk/agent/")) {
      const methodName = url.pathname.slice("/_bynk/agent/".length);
      const { args, deps } = (await request.json()) as { args: unknown[]; deps: unknown };
      const env = this.__env as unknown as globalThis.Record<string, unknown>;
      const __givenDeps = { Fees: new handlers_shop_fees.FlatFees(), Stamp: new handlers_shop_orders.FixedStamp() };
      const result = await (this as unknown as globalThis.Record<string, (...bynkArgs: unknown[]) => unknown>)[methodName](...__decodeAgentArgs(__BookWire, methodName, args), { ...((deps ?? {}) as globalThis.Record<string, unknown>), ...__givenDeps });
      return new globalThis.Response(globalThis.JSON.stringify(__encodeAgentResult(__BookWire, methodName, result)), { headers: { "content-type": "application/json" } });
    }
    return new globalThis.Response("Not Found", { status: 404 });
  }

}

const __BookWire: __AgentWire = {
  add: { args: [{ enc: __serialise_Line, dec: __deserialise_Line }], result: { enc: (__v: number) => ((v: number) => { if (!globalThis.Number.isSafeInteger(v)) throw new globalThis.Error("Int outside the safe-integer range at boundary"); return v as __JsonValue; })(__v), dec: (__j: __JsonValue) => ((__v) => typeof __v !== "number" ? Err({ kind: "StructuralMismatch", path: "$", expected: "safe integer", actual: typeof __v } as __BoundaryError) : globalThis.Number.isSafeInteger(__v) ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "$", expected: "safe integer", actual: String(__v) } as __BoundaryError))(__j) } },
};

export function __makeBook(key: string, env?: { BOOK?: __DurableObjectNamespace }): Book {
  return __makeAgent(__BookRegistry, env?.BOOK, key, (state) => new Book(state), __BookWire);
}

export function __resetAgents(): void {
  __BookRegistry.reset();
}

export function __serialise_Line(value: Line): __JsonValue {
  return {
    sku: value.sku as __JsonValue,
    qty: ((v: number) => { if (!globalThis.Number.isSafeInteger(v)) throw new globalThis.Error("Int outside the safe-integer range at boundary"); return v as __JsonValue; })(value.qty),
  };
}

export function __deserialise_Line(json: __JsonValue, path: string = "$"): Result<Line, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  if (typeof obj["sku"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.sku`, expected: "string", actual: typeof obj["sku"] });
  }
  const __sku = obj["sku"];
  if (typeof obj["qty"] !== "number") {
    return Err({ kind: "StructuralMismatch", path: `${path}.qty`, expected: "number", actual: typeof obj["qty"] });
  }
  if (!globalThis.Number.isSafeInteger(obj["qty"])) {
    return Err({ kind: "StructuralMismatch", path: `${path}.qty`, expected: "safe integer", actual: String(obj["qty"]) });
  }
  const __qty = obj["qty"];
  return Ok({ sku: __sku, qty: __qty } as Line);
}


export function __serialise_Option_Line(value: Option<Line>): __JsonValue {
  if (value.tag === "Some") return { kind: "Some", value: __serialise_Line(value.value) };
  return { kind: "None" };
}

function __option_value_Line(raw: __JsonValue, at: string): Result<unknown, __BoundaryError> {
  const __r_v = __deserialise_Line(raw, at);
  if (__r_v.tag === "Err") return __r_v;
  const __v = __r_v.value;
  return Ok(__v);
}

export function __deserialise_Option_Line(json: __JsonValue, path: string = "$"): Result<Option<Line>, __BoundaryError> {
  if (json === undefined || json === null) {
    return Ok(None as Option<Line>);
  }
  if (typeof json === "object" && !globalThis.Array.isArray(json)) {
    const obj = json as { [k: string]: __JsonValue };
    const __keys = globalThis.Object.keys(obj);
    if (obj["kind"] === "None" && __keys.length === 1) {
      return Ok(None as Option<Line>);
    }
    if (obj["kind"] === "Some" && __keys.length === 2 && "value" in obj) {
      const __t = __option_value_Line(obj["value"], `${path}.value`);
      if (__t.tag === "Err") {
        return __t;
      }
      return Ok(Some(__t.value as Line) as Option<Line>);
    }
  }
  const __b = __option_value_Line(json, path);
  if (__b.tag === "Ok") {
    return Ok(Some(__b.value as Line) as Option<Line>);
  }
  if (__b.error.kind === "StructuralMismatch" && __b.error.path === path) {
    return Err({ ...__b.error, expected: __b.error.expected + " | null | {\"kind\": \"None\"} | {\"kind\": \"Some\", \"value\": ...}" });
  }
  return __b;
}
