// Generated by bynkc — do not edit by hand.
// context shop.orders

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type __DurableObjectNamespace, type __JsonValue, type __BoundaryError, type __ServiceBinding, __callService, __boundaryError } from "../../../runtime.js";

import type * as shop_fees from "../../shop-fees/handlers.js";
import type * as shop_payment from "../../shop-payment/handlers.js";

export interface Line {
  readonly sku: string;
  readonly qty: number;
}

export const Line = {
};
