// Generated by bynkc — do not edit by hand.
// commons demo.refined_patterns_int_range

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export function classify(status: number): string {
  if ((Number.isInteger(status) && (status >= 200 && status <= 299))) {
    return "success";
  }
  if ((Number.isInteger(status) && (status >= 400 && status <= 499))) {
    return "client error";
  }
  if ((Number.isInteger(status) && (status >= 500 && status <= 599))) {
    return "server error";
  }
  return "other";
}

