// Generated by bynkc — do not edit by hand.
// commons ids

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type JsonValue, type BoundaryError, type ServiceBinding, callService, boundaryError } from "./runtime.js";

export type RoomId = string & { readonly __brand: "RoomId" };

export const RoomId = {
  of(value: string): Result<RoomId, ValidationError> {
    return Ok(value as RoomId);
  },
  unsafe(value: string): RoomId {
    return value as RoomId;
  },
};

export function serialise_RoomId(value: RoomId): JsonValue {
  return value as unknown as string;
}

export function deserialise_RoomId(json: JsonValue, path: string = "$"): Result<RoomId, BoundaryError> {
  if (typeof json !== "string") {
    return Err({ kind: "StructuralMismatch", path, expected: "string", actual: typeof json });
  }
  const validated = (typeof (RoomId as unknown as { of?: (json: unknown) => Result<unknown, ValidationError> }).of === "function")
    ? (RoomId as unknown as { of: (json: unknown) => Result<unknown, ValidationError> }).of(json)
    : (Ok(json as unknown as RoomId) as Result<unknown, ValidationError>);
  if (validated.tag === "Err") {
    return Err({ kind: "RefinementViolation", path, violation: validated.error });
  }
  return Ok(validated.value as RoomId);
}

