// Generated by bynkc — do not edit by hand.
// context echo

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type Connection, type DurableObjectState, type DurableObjectNamespace, StateRegistry, makeAgent, rehydrationViolation, resolveConnection, connIdOf, acceptHibernatableConnection, newWebSocketPair, webSocketUpgradeResponse, WorkersConnection, type JsonValue, type BoundaryError, type ServiceBinding, callService, boundaryError } from "../../runtime.js";

export type RoomId = string & { readonly __brand: "echo.RoomId" };

export const RoomId = {
  of(value: string): Result<RoomId, ValidationError> {
    return Ok(value as RoomId);
  },
  unsafe(value: string): RoomId {
    return value as RoomId;
  },
};

export type UserId = string & { readonly __brand: "echo.UserId" };

export const UserId = {
  of(value: string): Result<UserId, ValidationError> {
    return Ok(value as UserId);
  },
  unsafe(value: string): UserId {
    return value as UserId;
  },
};

export interface Frame {
  readonly text: string;
}

export const Frame = {
};

export const Echo = {
};

export interface RoomState {
  readonly conns: Record<string, string>;
}

const __RoomRegistry = new StateRegistry();
function __zeroOfRoomState(): RoomState { return { conns: {} }; }

function __rehydrateRoomState(s: RoomState): void {
  for (const __k of Object.keys(s.conns)) { const __r = deserialise_RoomId((__k as unknown as JsonValue), "conns"); if (__r.tag === "Err") throw rehydrationViolation("Room", __r.error); }
}

export class Room {
  state: DurableObjectState;
  constructor(state: DurableObjectState) {
    this.state = state;
  }

  private async loadState(): Promise<RoomState> {
    const stored = await this.state.storage.get<RoomState>("state");
    if (stored === undefined) return __zeroOfRoomState();
    const __merged = { ...__zeroOfRoomState(), ...stored };
    __rehydrateRoomState(__merged);
    return __merged;
  }

  private async commitState(s: RoomState): Promise<void> {
    await this.state.storage.put("state", s);
  }

  async join(rid: RoomId, conn: Connection<Frame>, deps: {}): Promise<void> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = await ((__state.conns[String(rid)] = connIdOf(conn)), undefined);
      return undefined;
    })();
    await this.commitState(__state);
    return __result;
  }

  async __wsOpen_Echo(connection: Connection<Frame>, roomId: RoomId, deps: {}): Promise<void> {
    const __r0 = await this.join(roomId, connection, deps);
    return undefined;
  }

  async __wsMessage_Echo(connection: Connection<Frame>, frame: Frame, deps: {}): Promise<void> {
    return undefined;
  }

  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname === "/_bynk/ws/open/Echo") {
      const __pair = newWebSocketPair();
      const __payload = JSON.parse(request.headers.get("X-Bynk-Ws-Open") ?? "{}") as { args: unknown[] };
      const connection = acceptHibernatableConnection<Frame>(this.state, __pair.server, { identity: "", args: __payload.args });
      await this.__wsOpen_Echo(connection, __payload.args[0] as RoomId, {});
      return webSocketUpgradeResponse(__pair.client);
    }
    if (url.pathname.startsWith("/_bynk/agent/")) {
      const methodName = url.pathname.slice("/_bynk/agent/".length);
      const { args, deps } = (await request.json()) as { args: unknown[]; deps: unknown };
      const result = await (this as unknown as Record<string, (...bynkArgs: unknown[]) => unknown>)[methodName](...args, deps);
      return new Response(JSON.stringify(result ?? null), { headers: { "content-type": "application/json" } });
    }
    return new Response("Not Found", { status: 404 });
  }

  async webSocketMessage(ws: { deserializeAttachment(): unknown; send(data: string): void; close(code?: number, reason?: string): void }, message: string | ArrayBuffer): Promise<void> {
    const __att = ws.deserializeAttachment() as { connId: string; identity: string; args: unknown[] } | null;
    if (__att === null) { ws.close(1011, "no session"); return; }
    const connection = new WorkersConnection<Frame>(ws, __att.connId);
    let __raw: string;
    try { __raw = typeof message === "string" ? message : new TextDecoder().decode(message); } catch { ws.close(1003, "unreadable frame"); return; }
    let __json: JsonValue;
    try { __json = JSON.parse(__raw) as JsonValue; } catch { ws.close(1003, "malformed frame"); return; }
    const __dec = deserialise_Frame(__json, "frame");
    if (__dec.tag === "Err") { ws.close(1008, "invalid frame"); return; }
    await this.__wsMessage_Echo(connection, __dec.value, {});
  }

}

export function __makeRoom(key: RoomId, env?: { ROOM?: DurableObjectNamespace }): Room {
  return makeAgent(__RoomRegistry, env?.ROOM, key, (state) => new Room(state));
}

export function __resetAgents(): void {
  __RoomRegistry.reset();
}

export function serialise_Frame(value: Frame): JsonValue {
  return {
    text: value.text as JsonValue,
  };
}

export function deserialise_Frame(json: JsonValue, path: string = "$"): Result<Frame, BoundaryError> {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: JsonValue };
  if (typeof obj["text"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.text`, expected: "string", actual: typeof obj["text"] });
  }
  const __text = obj["text"];
  return Ok({ text: __text } as Frame);
}

export function serialise_RoomId(value: RoomId): JsonValue {
  return value as unknown as string;
}

export function deserialise_RoomId(json: JsonValue, path: string = "$"): Result<RoomId, BoundaryError> {
  if (typeof json !== "string") {
    return Err({ kind: "StructuralMismatch", path, expected: "string", actual: typeof json });
  }
  const validated = (typeof (RoomId as unknown as { of?: (json: unknown) => Result<unknown, ValidationError> }).of === "function")
    ? (RoomId as unknown as { of: (json: unknown) => Result<unknown, ValidationError> }).of(json)
    : (Ok(json as unknown as RoomId) as Result<unknown, ValidationError>);
  if (validated.tag === "Err") {
    return Err({ kind: "RefinementViolation", path, violation: validated.error });
  }
  return Ok(validated.value as RoomId);
}


