// Generated by bynkc — do not edit by hand.
// Worker entry point for context `echo`.

import { Ok, Err, type Result, type __JsonValue, type __BoundaryError, __boundaryError } from "../../runtime.js";
import { compose, type Env } from "./compose.js";
import * as handlers from "./handlers.js";

export { Room } from "./handlers.js";

export default {
  async fetch(request: globalThis.Request, env: Env): globalThis.Promise<globalThis.Response> {
    const url = new globalThis.URL(request.url);
    const path = url.pathname;
    const method = request.method;
    const surface = compose(env);
    try {
      if (path.startsWith("/_bynk/call/")) {
        const servicePath = path.slice("/_bynk/call/".length);
        switch (servicePath) {
          default:
            return new globalThis.Response("Not found", { status: 404 });
        }
      }

      if (request.headers.get("Upgrade") === "websocket") {
        const __ws_roomId = url.searchParams.get("roomId");
        if (__ws_roomId === null) return new globalThis.Response("Missing parameter: roomId", { status: 400 });
        return surface.ws_Echo_open(request, __ws_roomId);
      }

      return new globalThis.Response("Not Found", { status: 404 });
    } catch {
      return new globalThis.Response("Internal Server Error", { status: 500 });
    }
  },
};
