// Generated by bynkc — do not edit by hand.
// system test: shop.api

import { Ok, Err, Some, None, callService, type Result, type Option, type ValidationError, type JsonError, type JsonValue, type BoundaryError, type ServiceBinding, responseToHttpResult, responseToHttpOutcome, makeIntegrationDoNamespace, type DurableObjectState, type DurableObjectNamespace } from "../runtime.js";
import * as shop_api from "../workers/shop-api/handlers.js";
import worker_shop_api from "../workers/shop-api/index.js";

class ExpectationError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number, detail: string) {
    super(`${detail}\n  at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkExpectFailure(location: string, start: number, end: number, detail: string) {
  return new ExpectationError(location, start, end, detail);
}
function __bynkExpect(cond: boolean, location: string, start: number, end: number, detail: string): void {
  if (!cond) { throw __bynkExpectFailure(location, start, end, detail); }
}
function __bynkShow(v: unknown): string {
  try { return typeof v === "bigint" ? String(v) : (JSON.stringify(v) ?? String(v)); } catch { return String(v); }
}

function makeHarness() {
  const env_shop_api: any = {};
  env_shop_api.CART = makeIntegrationDoNamespace((state) => new shop_api.Cart(state));
  const rootEnv: any = {};
  rootEnv.SHOP_API = { fetch: (req: Request) => worker_shop_api.fetch(req, env_shop_api) } as ServiceBinding;
  return { env: rootEnv };
}

function __bynkNow(): number { return Math.floor(Date.now() / 1000); }
function __b64url(s: string): string { return btoa(s).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, ""); }
function __bytesB64url(bytes: Uint8Array): string { let bin = ""; for (const b of bytes) bin += String.fromCharCode(b); return btoa(bin).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, ""); }
async function __bynkSignHs256(payload: Record<string, unknown>, secret: string): Promise<string> {
  const h = __b64url(JSON.stringify({ alg: "HS256", typ: "JWT" }));
  const p = __b64url(JSON.stringify(payload));
  const enc = new TextEncoder();
  const key = await crypto.subtle.importKey("raw", enc.encode(secret) as BufferSource, { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
  const sig = await crypto.subtle.sign("HMAC", key, enc.encode(`${h}.${p}`) as BufferSource);
  return `${h}.${p}.${__bytesB64url(new Uint8Array(sig))}`;
}
(globalThis as any).process = (globalThis as any).process ?? { env: {} };
(globalThis as any).process.env["AUTH_SECRET"] = "__bynk_test_secret";
async function __sysdrive_api_http_POST_cart(body: any, __sub: string) {
  const __body = JSON.stringify(shop_api.serialise_Item(body));
  const __h = makeHarness();
  const __req = new Request(`https://test/cart`, { method: "POST", headers: { "content-type": "application/json", "authorization": `Bearer ${await __bynkSignHs256({ sub: __sub, exp: __bynkNow() + 3600 }, ((globalThis as any).process?.env?.["AUTH_SECRET"] ?? ""))}`, }, body: __body, });
  const __res = await __h.env.SHOP_API.fetch(__req);
  return responseToHttpResult(__res, shop_api.deserialise_Item);
}
async function __sysdrive_raw_api_http_POST_cart(body: string, __sub: string) {
  const __h = makeHarness();
  const __req = new Request(`https://test/cart`, { method: "POST", headers: { "content-type": "application/json", "authorization": `Bearer ${await __bynkSignHs256({ sub: __sub, exp: __bynkNow() + 3600 }, ((globalThis as any).process?.env?.["AUTH_SECRET"] ?? ""))}`, }, body: body, });
  const __res = await __h.env.SHOP_API.fetch(__req);
  return responseToHttpOutcome(__res, shop_api.deserialise_Item);
}
async function __sysdrive_api_http_POST_reject(body: any, __sub: string) {
  const __body = JSON.stringify(shop_api.serialise_Item(body));
  const __h = makeHarness();
  const __req = new Request(`https://test/reject`, { method: "POST", headers: { "content-type": "application/json", "authorization": `Bearer ${await __bynkSignHs256({ sub: __sub, exp: __bynkNow() + 3600 }, ((globalThis as any).process?.env?.["AUTH_SECRET"] ?? ""))}`, }, body: __body, });
  const __res = await __h.env.SHOP_API.fetch(__req);
  return responseToHttpResult(__res, shop_api.deserialise_Item);
}
async function __sysdrive_raw_api_http_POST_reject(body: string, __sub: string) {
  const __h = makeHarness();
  const __req = new Request(`https://test/reject`, { method: "POST", headers: { "content-type": "application/json", "authorization": `Bearer ${await __bynkSignHs256({ sub: __sub, exp: __bynkNow() + 3600 }, ((globalThis as any).process?.env?.["AUTH_SECRET"] ?? ""))}`, }, body: body, });
  const __res = await __h.env.SHOP_API.fetch(__req);
  return responseToHttpOutcome(__res, shop_api.deserialise_Item);
}

async function test_a_typed_create_returns_Created_over_the_real_wire() {
  try {
    const deps = makeHarness();
    const item = await __sysdrive_api_http_POST_cart({ sku: "widget" }, "alice");
    if (!(item.tag === "Created")) { throw __bynkExpectFailure("shop/tests/api.test.bynk:4:12", 174, 192, "expect item is Created(_)"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

async function test_an_empty_sku_is_rejected_at_the_boundary_before_the_handler() {
  try {
    const deps = makeHarness();
    const r = await __sysdrive_raw_api_http_POST_cart("{\"sku\": \"\"}", "alice");
    if (!(r.tag === "Rejected" && r.value.tag === "RefinementViolation")) { throw __bynkExpectFailure("shop/tests/api.test.bynk:8:12", 352, 389, "expect r is Rejected(RefinementViolation(_))"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

async function test_malformed_json_is_rejected_at_the_boundary() {
  try {
    const deps = makeHarness();
    const r = await __sysdrive_raw_api_http_POST_cart("{not json", "alice");
    if (!(r.tag === "Rejected" && r.value.tag === "MalformedJson")) { throw __bynkExpectFailure("shop/tests/api.test.bynk:12:12", 526, 557, "expect r is Rejected(MalformedJson(_))"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

async function test_valid_raw_input_passes_the_boundary_to_the_handler() {
  try {
    const deps = makeHarness();
    const r = await __sysdrive_raw_api_http_POST_cart("{\"sku\": \"raw-ok\"}", "alice");
    if (!(r.tag === "Handled")) { throw __bynkExpectFailure("shop/tests/api.test.bynk:16:12", 714, 729, "expect r is Handled(_)"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

async function test_a_handler_returned_400_is_Handled__not_a_boundary_rejection() {
  try {
    const deps = makeHarness();
    const r = await __sysdrive_raw_api_http_POST_reject("{\"sku\": \"ok\"}", "alice");
    if (!(r.tag === "Handled")) { throw __bynkExpectFailure("shop/tests/api.test.bynk:20:12", 893, 908, "expect r is Handled(_)"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run(only?: string) {
  const results = [];
  const want = (n: string): boolean => only === undefined || only === n;
  if (want("a typed create returns Created over the real wire")) results.push({ name: "a typed create returns Created over the real wire", ...(await test_a_typed_create_returns_Created_over_the_real_wire()) });
  if (want("an empty sku is rejected at the boundary before the handler")) results.push({ name: "an empty sku is rejected at the boundary before the handler", ...(await test_an_empty_sku_is_rejected_at_the_boundary_before_the_handler()) });
  if (want("malformed json is rejected at the boundary")) results.push({ name: "malformed json is rejected at the boundary", ...(await test_malformed_json_is_rejected_at_the_boundary()) });
  if (want("valid raw input passes the boundary to the handler")) results.push({ name: "valid raw input passes the boundary to the handler", ...(await test_valid_raw_input_passes_the_boundary_to_the_handler()) });
  if (want("a handler-returned 400 is Handled, not a boundary rejection")) results.push({ name: "a handler-returned 400 is Handled, not a boundary rejection", ...(await test_a_handler_returned_400_is_Handled__not_a_boundary_rejection()) });
  return results;
}
