// Generated by bynkc — do not edit by hand.
// context shop.inventory

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type DurableObjectState, type DurableObjectNamespace, StateRegistry, makeAgent, rehydrationViolation, type JsonValue, type BoundaryError } from "../runtime.js";

export interface Item {
  readonly qty: number;
}

export const Item = {
};

export interface Row {
  readonly sku: string;
  readonly qty: number;
}

export const Row = {
};

export interface InventoryState {
  readonly items: Record<string, Item>;
}

const __InventoryRegistry = new StateRegistry();
function __zeroOfInventoryState(): InventoryState { return { items: {} }; }

function __rehydrateInventoryState(s: InventoryState): void {
  for (const __v of Object.values(s.items)) { const __r = deserialise_Item((__v as unknown as JsonValue), "items"); if (__r.tag === "Err") throw rehydrationViolation("Inventory", __r.error); }
  for (const __k of Object.keys(s.items)) { const __r = ((__v) => typeof __v === "string" ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "items", expected: "string", actual: typeof __v } as BoundaryError))((__k as unknown as JsonValue)); if (__r.tag === "Err") throw rehydrationViolation("Inventory", __r.error); }
}

export class Inventory {
  state: DurableObjectState;
  constructor(state: DurableObjectState) {
    this.state = state;
  }

  private async loadState(): Promise<InventoryState> {
    const stored = await this.state.storage.get<InventoryState>("state");
    if (stored === undefined) return __zeroOfInventoryState();
    const __merged = { ...__zeroOfInventoryState(), ...stored };
    __rehydrateInventoryState(__merged);
    return __merged;
  }

  private async commitState(s: InventoryState): Promise<void> {
    await this.state.storage.put("state", s);
  }

  async rows(deps: {}): Promise<readonly Row[]> {
    const __state = await this.loadState();
    return ((() => ((() => Object.entries(__state.items).map(([__k, __v]) => ({ key: __k, value: __v }))))().map((__x) => ((e) => ({ sku: e.key, qty: e.value.qty }))(__x))))();
  }

  async bigRows(deps: {}): Promise<readonly Row[]> {
    const __state = await this.loadState();
    return ((() => ((() => [...((() => ((() => Object.entries(__state.items).map(([__k, __v]) => ({ key: __k, value: __v }))))().filter((__x) => ((e) => e.value.qty > 0)(__x))))()].sort((__a, __b) => { const __ka = ((e) => e.key)(__a), __kb = ((e) => e.key)(__b); return __ka < __kb ? -1 : __ka > __kb ? 1 : 0; })))().map((__x) => ((e) => ({ sku: e.key, qty: e.value.qty }))(__x))))();
  }

  async skus(deps: {}): Promise<readonly string[]> {
    const __state = await this.loadState();
    return ((() => [...((() => Object.keys(__state.items)))()].sort((__a, __b) => { const __ka = ((k) => k)(__a), __kb = ((k) => k)(__b); return __ka < __kb ? -1 : __ka > __kb ? 1 : 0; })))();
  }

  async quantities(deps: {}): Promise<readonly number[]> {
    const __state = await this.loadState();
    return ((() => ((() => Object.values(__state.items)))().map((__x) => ((it) => it.qty)(__x))))();
  }

  async hasSku(sku: string, deps: {}): Promise<boolean> {
    const __state = await this.loadState();
    return ((() => Object.entries(__state.items).map(([__k, __v]) => ({ key: __k, value: __v }))))().some((__x) => ((e) => e.key === sku)(__x));
  }

  async pending(deps: {}): Promise<readonly Row[]> {
    const __state = await this.loadState();
    const q = (() => Object.entries(__state.items).map(([__k, __v]) => ({ key: __k, value: __v })));
    return ((() => ((() => (q)().filter((__x) => ((e) => e.value.qty > 0)(__x))))().map((__x) => ((e) => ({ sku: e.key, qty: e.value.qty }))(__x))))();
  }

}

export function __makeInventory(key: string, env?: { INVENTORY?: DurableObjectNamespace }): Inventory {
  return makeAgent(__InventoryRegistry, env?.INVENTORY, key, (state) => new Inventory(state));
}

export interface LedgerState {
  readonly balances: Record<string, Item>;
}

const __LedgerRegistry = new StateRegistry();
function __zeroOfLedgerState(): LedgerState { return { balances: {} }; }

function __rehydrateLedgerState(s: LedgerState): void {
  for (const __v of Object.values(s.balances)) { const __r = deserialise_Item((__v as unknown as JsonValue), "balances"); if (__r.tag === "Err") throw rehydrationViolation("Ledger", __r.error); }
}

export class Ledger {
  state: DurableObjectState;
  constructor(state: DurableObjectState) {
    this.state = state;
  }

  private async loadState(): Promise<LedgerState> {
    const stored = await this.state.storage.get<LedgerState>("state");
    if (stored === undefined) return __zeroOfLedgerState();
    const __merged = { ...__zeroOfLedgerState(), ...stored };
    __rehydrateLedgerState(__merged);
    return __merged;
  }

  private async commitState(s: LedgerState): Promise<void> {
    await this.state.storage.put("state", s);
  }

  async accounts(deps: {}): Promise<readonly number[]> {
    const __state = await this.loadState();
    return ((() => [...((() => Object.keys(__state.balances).map((__k) => Number(__k))))()].sort((__a, __b) => { const __ka = ((k) => k)(__a), __kb = ((k) => k)(__b); return __ka < __kb ? -1 : __ka > __kb ? 1 : 0; })))();
  }

  async maxAccount(deps: {}): Promise<Option<number>> {
    const __state = await this.loadState();
    return (() => { const __a = ((() => Object.entries(__state.balances).map(([__k, __v]) => ({ key: Number(__k), value: __v }))))(); if (__a.length === 0) return None; let __m = ((e) => e.key)(__a[0]); for (const __x of __a) { const __k = ((e) => e.key)(__x); if (__k > __m) __m = __k; } return Some(__m); })();
  }

}

export function __makeLedger(key: string, env?: { LEDGER?: DurableObjectNamespace }): Ledger {
  return makeAgent(__LedgerRegistry, env?.LEDGER, key, (state) => new Ledger(state));
}

export function __resetAgents(): void {
  __InventoryRegistry.reset();
  __LedgerRegistry.reset();
}

export function serialise_Item(value: Item): JsonValue {
  return {
    qty: value.qty as JsonValue,
  };
}

export function deserialise_Item(json: JsonValue, path: string = "$"): Result<Item, BoundaryError> {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: JsonValue };
  if (typeof obj["qty"] !== "number") {
    return Err({ kind: "StructuralMismatch", path: `${path}.qty`, expected: "number", actual: typeof obj["qty"] });
  }
  if (!Number.isInteger(obj["qty"])) {
    return Err({ kind: "StructuralMismatch", path: `${path}.qty`, expected: "integer", actual: String(obj["qty"]) });
  }
  const __qty = obj["qty"];
  return Ok({ qty: __qty } as Item);
}


