// Generated by bynkc — do not edit by hand.
// composition root for `farewell` Worker.

import { type __ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";

export interface Env {
}

export function compose(env: Env) {
  const Clock = new handlers.FixedClock();
  const deps = { Clock };
  return {
    async hello(name: string) {
      return handlers.hello.call(name, deps);
    },
  };
}
