// Generated by bynkc — do not edit by hand.
// context farewell

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type __JsonValue, type __BoundaryError, type __ServiceBinding, __callService, __boundaryError } from "../../runtime.js";

export interface Clock {
  now(): globalThis.Promise<number>;
}

export const __ClockToken: symbol = globalThis.Symbol("Clock");

export class FixedClock implements Clock {
  async now(): globalThis.Promise<number> {
    return 42;
  }
}

export const __FixedClockProvider = { token: __ClockToken, factory: () => new FixedClock() };

export const hello = {
  async call(name: string, deps: { Clock: Clock }): globalThis.Promise<Result<string, void>> {
    const n = await deps.Clock.now();
    return Ok("hello");
  },
};

export function __serialise_Result_String_Unit(value: Result<string, void>): __JsonValue {
  if (value.tag === "Ok") return { kind: "Ok", value: value.value as __JsonValue };
  return { kind: "Err", error: null };
}

export function __deserialise_Result_String_Unit(json: __JsonValue, path: string = "$"): Result<Result<string, void>, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  if (obj["kind"] === "Ok") {
  if (typeof obj["value"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.value`, expected: "string", actual: typeof obj["value"] });
  }
  const __v = obj["value"];
    return Ok(Ok(__v) as Result<string, void>);
  } else if (obj["kind"] === "Err") {
  const __e = undefined;
    return Ok(Err(__e) as Result<string, void>);
  }
  return Err({ kind: "StructuralMismatch", path, expected: "Ok | Err", actual: String(obj["kind"]) });
}
