//! TypeScript emission (spec §7, v0.1 §6, v0.2 §6).
//!
//! Walks the typed AST and writes a single TypeScript module.
//!
//! v0.2 lowering rules:
//! - Refined-base types: branded type alias + constructor object with
//!   `of`/`unsafe` (+ any user-declared methods).
//! - Record types: TypeScript `interface` + namespace object with methods.
//! - Sum types: discriminated-union type alias + namespace object with
//!   variant constructors and methods.
//! - Field access lowers to property access.
//! - Method calls lower to `Type.method(receiver, args)` (UFCS).
//! - `match` lowers to a switch on `.tag`; in tail position it inlines,
//!   otherwise it becomes an IIFE.
//! - `is` lowers to a tag check; bindings become `const` declarations
//!   on the truthy side of `if`/`&&`.

use std::collections::HashMap;
use std::fmt::Write as _;

use crate::ast::*;
use crate::checker::{NamedKind, Ty, TypedCommons};

const RUNTIME_IMPORT: &str = "./runtime.js";
const INDENT_STEP: usize = 2;

/// Emit TypeScript source for the typed commons.
pub fn emit(commons: &TypedCommons) -> String {
    let mut out = String::new();
    write_header(&mut out, commons);
    // Types come first (they define interfaces and namespaces).
    for item in &commons.commons.items {
        if let CommonsItem::Type(t) = item {
            emit_type(&mut out, t, commons);
        }
    }
    // Free functions afterward.
    for item in &commons.commons.items {
        if let CommonsItem::Fn(f) = item
            && let FnName::Free(_) = &f.name
        {
            emit_free_fn(&mut out, f, commons);
        }
    }
    out
}

fn write_header(out: &mut String, commons: &TypedCommons) {
    writeln!(out, "// Generated by karnc — do not edit by hand.").unwrap();
    writeln!(out, "// commons {}", commons.commons.name.joined()).unwrap();
    writeln!(out).unwrap();
    if !commons.commons.items.is_empty() {
        writeln!(
            out,
            "import {{ Ok, Err, Some, None, type Result, type Option, type ValidationError }} from \"{RUNTIME_IMPORT}\";",
        )
        .unwrap();
        writeln!(out).unwrap();
    }
}

fn emit_type(out: &mut String, t: &TypeDecl, commons: &TypedCommons) {
    match &t.body {
        TypeBody::Refined {
            base, refinement, ..
        } => emit_refined_type(out, t, *base, refinement.as_ref(), commons),
        TypeBody::Record(r) => emit_record_type(out, t, r, commons),
        TypeBody::Sum(s) => emit_sum_type(out, t, s, commons),
    }
}

fn emit_refined_type(
    out: &mut String,
    t: &TypeDecl,
    base: BaseType,
    refinement: Option<&Refinement>,
    commons: &TypedCommons,
) {
    let ts_base = ts_base(base);
    writeln!(
        out,
        "export type {name} = {base} & {{ readonly __brand: \"{name}\" }};",
        name = t.name.name,
        base = ts_base,
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "export const {name} = {{", name = t.name.name).unwrap();
    writeln!(
        out,
        "  of(value: {base}): Result<{name}, ValidationError> {{",
        name = t.name.name,
        base = ts_base,
    )
    .unwrap();
    emit_refined_checks(out, t, base, refinement);
    writeln!(out, "    return Ok(value as {name});", name = t.name.name).unwrap();
    writeln!(out, "  }},").unwrap();
    writeln!(
        out,
        "  unsafe(value: {base}): {name} {{",
        name = t.name.name,
        base = ts_base,
    )
    .unwrap();
    writeln!(out, "    return value as {name};", name = t.name.name).unwrap();
    writeln!(out, "  }},").unwrap();
    emit_attached_methods(out, &t.name.name, commons);
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();
}

fn emit_refined_checks(
    out: &mut String,
    t: &TypeDecl,
    base: BaseType,
    refinement: Option<&Refinement>,
) {
    let name = &t.name.name;
    if base == BaseType::Int {
        writeln!(out, "    if (!Number.isInteger(value)) {{").unwrap();
        writeln!(
            out,
            "      return Err({{ field: \"{name}\", message: \"must be an integer\", value }});"
        )
        .unwrap();
        writeln!(out, "    }}").unwrap();
    }
    if let Some(r) = refinement {
        for pred in &r.predicates {
            emit_pred_check(out, name, &pred.kind);
        }
    }
}

fn emit_pred_check(out: &mut String, type_name: &str, pred: &PredKind) {
    match pred {
        PredKind::NonNegative => {
            writeln!(out, "    if (!(value >= 0)) {{").unwrap();
            writeln!(
                out,
                "      return Err({{ field: \"{type_name}\", message: \"must be non-negative\", value }});",
            )
            .unwrap();
            writeln!(out, "    }}").unwrap();
        }
        PredKind::Positive => {
            writeln!(out, "    if (!(value > 0)) {{").unwrap();
            writeln!(
                out,
                "      return Err({{ field: \"{type_name}\", message: \"must be positive\", value }});",
            )
            .unwrap();
            writeln!(out, "    }}").unwrap();
        }
        PredKind::InRange(a, b) => {
            writeln!(out, "    if (!(value >= {a} && value <= {b})) {{").unwrap();
            writeln!(
                out,
                "      return Err({{ field: \"{type_name}\", message: \"must be in range [{a}, {b}]\", value }});",
            )
            .unwrap();
            writeln!(out, "    }}").unwrap();
        }
        PredKind::NonEmpty => {
            writeln!(out, "    if (!(value.length > 0)) {{").unwrap();
            writeln!(
                out,
                "      return Err({{ field: \"{type_name}\", message: \"must be non-empty\", value }});",
            )
            .unwrap();
            writeln!(out, "    }}").unwrap();
        }
        PredKind::MinLength(n) => {
            writeln!(out, "    if (!(value.length >= {n})) {{").unwrap();
            writeln!(
                out,
                "      return Err({{ field: \"{type_name}\", message: \"length must be at least {n}\", value }});",
            )
            .unwrap();
            writeln!(out, "    }}").unwrap();
        }
        PredKind::MaxLength(n) => {
            writeln!(out, "    if (!(value.length <= {n})) {{").unwrap();
            writeln!(
                out,
                "      return Err({{ field: \"{type_name}\", message: \"length must be at most {n}\", value }});",
            )
            .unwrap();
            writeln!(out, "    }}").unwrap();
        }
        PredKind::Length(n) => {
            writeln!(out, "    if (!(value.length === {n})) {{").unwrap();
            writeln!(
                out,
                "      return Err({{ field: \"{type_name}\", message: \"length must be exactly {n}\", value }});",
            )
            .unwrap();
            writeln!(out, "    }}").unwrap();
        }
        PredKind::Matches(pat) => {
            let escaped = escape_ts_string(pat);
            writeln!(
                out,
                "    if (!new RegExp(\"^\" + \"{escaped}\" + \"$\").test(value)) {{"
            )
            .unwrap();
            writeln!(
                out,
                "      return Err({{ field: \"{type_name}\", message: \"must match /{}/\", value }});",
                escape_ts_string(pat),
            )
            .unwrap();
            writeln!(out, "    }}").unwrap();
        }
    }
}

fn emit_record_type(out: &mut String, t: &TypeDecl, r: &RecordBody, commons: &TypedCommons) {
    writeln!(out, "export interface {name} {{", name = t.name.name).unwrap();
    for f in &r.fields {
        writeln!(
            out,
            "  readonly {name}: {ty};",
            name = f.name.name,
            ty = ts_type_ref(&f.type_ref),
        )
        .unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "export const {name} = {{", name = t.name.name).unwrap();
    emit_attached_methods(out, &t.name.name, commons);
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();
}

fn emit_sum_type(out: &mut String, t: &TypeDecl, s: &SumBody, commons: &TypedCommons) {
    writeln!(out, "export type {name} =", name = t.name.name).unwrap();
    for (i, v) in s.variants.iter().enumerate() {
        let pipe = if i == 0 { " " } else { "|" };
        if v.payload.is_empty() {
            let term = if i == s.variants.len() - 1 { ";" } else { "" };
            writeln!(
                out,
                "  {pipe} {{ readonly tag: \"{tag}\" }}{term}",
                tag = v.name.name
            )
            .unwrap();
        } else {
            let fields: Vec<String> = v
                .payload
                .iter()
                .map(|f| {
                    format!(
                        "readonly {name}: {ty}",
                        name = f.name.name,
                        ty = ts_type_ref(&f.type_ref)
                    )
                })
                .collect();
            let term = if i == s.variants.len() - 1 { ";" } else { "" };
            writeln!(
                out,
                "  {pipe} {{ readonly tag: \"{tag}\"; {fields} }}{term}",
                tag = v.name.name,
                fields = fields.join("; "),
            )
            .unwrap();
        }
    }
    writeln!(out).unwrap();
    writeln!(out, "export const {name} = {{", name = t.name.name).unwrap();
    for v in &s.variants {
        if v.payload.is_empty() {
            writeln!(
                out,
                "  {tag}: {{ tag: \"{tag}\" }} as {name},",
                tag = v.name.name,
                name = t.name.name,
            )
            .unwrap();
        } else {
            let params: Vec<String> = v
                .payload
                .iter()
                .map(|f| {
                    format!(
                        "{name}: {ty}",
                        name = f.name.name,
                        ty = ts_type_ref(&f.type_ref)
                    )
                })
                .collect();
            let obj_fields: Vec<String> = v.payload.iter().map(|f| f.name.name.clone()).collect();
            writeln!(
                out,
                "  {tag}: ({params}): {name} => ({{ tag: \"{tag}\", {fields} }}),",
                tag = v.name.name,
                params = params.join(", "),
                name = t.name.name,
                fields = obj_fields.join(", "),
            )
            .unwrap();
        }
    }
    emit_attached_methods(out, &t.name.name, commons);
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();
}

fn emit_attached_methods(out: &mut String, type_name: &str, commons: &TypedCommons) {
    for item in &commons.commons.items {
        let CommonsItem::Fn(f) = item else { continue };
        let FnName::Method {
            type_name: t,
            method_name,
        } = &f.name
        else {
            continue;
        };
        if t.name != type_name {
            continue;
        }
        emit_method(out, f, type_name, method_name, commons);
    }
}

fn emit_method(
    out: &mut String,
    f: &FnDecl,
    type_name: &str,
    method_name: &Ident,
    commons: &TypedCommons,
) {
    let mut params: Vec<String> = Vec::new();
    if f.has_self {
        params.push(format!("self: {type_name}"));
    }
    for p in &f.params {
        params.push(format!("{}: {}", p.name.name, ts_type_ref(&p.type_ref)));
    }
    writeln!(
        out,
        "  {method}({params}): {ret} {{",
        method = method_name.name,
        params = params.join(", "),
        ret = ts_type_ref(&f.return_type),
    )
    .unwrap();
    let mut cx = LowerCtx::new(commons);
    emit_block_as_function_body(out, &f.body, &mut cx, INDENT_STEP * 2);
    writeln!(out, "  }},").unwrap();
}

fn emit_free_fn(out: &mut String, f: &FnDecl, commons: &TypedCommons) {
    let FnName::Free(name) = &f.name else {
        return;
    };
    let params: Vec<String> = f
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name.name, ts_type_ref(&p.type_ref)))
        .collect();
    writeln!(
        out,
        "export function {name}({params}): {ret} {{",
        name = name.name,
        params = params.join(", "),
        ret = ts_type_ref(&f.return_type),
    )
    .unwrap();
    let mut cx = LowerCtx::new(commons);
    emit_block_as_function_body(out, &f.body, &mut cx, INDENT_STEP);
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

/// Per-function lowering context: fresh-temp counter + typed-commons handle
/// (used to look up receiver types for method-call UFCS lowering).
struct LowerCtx<'a> {
    next_tmp: u32,
    commons: &'a TypedCommons,
}

impl<'a> LowerCtx<'a> {
    fn new(commons: &'a TypedCommons) -> Self {
        Self {
            next_tmp: 0,
            commons,
        }
    }
    fn fresh(&mut self) -> String {
        let n = self.next_tmp;
        self.next_tmp += 1;
        format!("__r{n}")
    }
    fn receiver_namespace(&self, e: &Expr) -> Option<String> {
        let ty = self.commons.expr_types.get(&e.span)?;
        if let Ty::Named { name, .. } = ty {
            Some(name.clone())
        } else {
            None
        }
    }
    /// Resolve the payload field name for the i-th positional binding of
    /// a variant. Built-ins are recognised by name; user variants are
    /// looked up via the type tables.
    fn positional_field_name(
        &self,
        discriminant_ty: Option<&Ty>,
        variant: &str,
        idx: usize,
    ) -> String {
        match (variant, idx) {
            ("Ok", 0) | ("Some", 0) => return "value".to_string(),
            ("Err", 0) => return "error".to_string(),
            _ => {}
        }
        if let Some(Ty::Named {
            kind: NamedKind::Sum,
            name,
        }) = discriminant_ty
            && let Some(decl) = self.commons.types.get(name)
            && let TypeBody::Sum(s) = &decl.body
            && let Some(v) = s.variants.iter().find(|v| v.name.name == variant)
            && let Some(f) = v.payload.get(idx)
        {
            return f.name.name.clone();
        }
        // Single-field fallback. The checker rejects mixed bindings already.
        "value".to_string()
    }
}

fn emit_block_as_function_body(out: &mut String, block: &Block, cx: &mut LowerCtx, indent: usize) {
    for stmt in &block.statements {
        emit_statement(out, stmt, cx, indent);
    }
    // Tail position: match → inline switch, if → inline if, otherwise return expr.
    match &block.tail.kind {
        ExprKind::Match { discriminant, arms } => {
            emit_match_tail(out, discriminant, arms, cx, indent);
        }
        ExprKind::If {
            cond,
            then_block,
            else_block,
        } if !both_simple(then_block, else_block) || cond_has_is_bindings(cond) => {
            emit_if_tail(out, cond, then_block, else_block, cx, indent);
        }
        _ => {
            let mut stmts = Vec::new();
            let tail = lower_expr(&block.tail, &mut stmts, cx);
            for s in &stmts {
                write_line(out, indent, s);
            }
            write_line(out, indent, &format!("return {tail};"));
        }
    }
}

fn emit_statement(out: &mut String, stmt: &Statement, cx: &mut LowerCtx, indent: usize) {
    match stmt {
        Statement::Let(l) => {
            let mut stmts = Vec::new();
            let value = lower_expr(&l.value, &mut stmts, cx);
            for s in &stmts {
                write_line(out, indent, s);
            }
            match &l.type_annot {
                Some(annot) => write_line(
                    out,
                    indent,
                    &format!(
                        "const {name}: {ty} = {value};",
                        name = l.name.name,
                        ty = ts_type_ref(annot),
                    ),
                ),
                None => write_line(
                    out,
                    indent,
                    &format!("const {name} = {value};", name = l.name.name),
                ),
            }
        }
    }
}

fn write_line(out: &mut String, indent: usize, line: &str) {
    for _ in 0..indent {
        out.push(' ');
    }
    out.push_str(line);
    out.push('\n');
}

fn lower_expr(e: &Expr, stmts: &mut Vec<String>, cx: &mut LowerCtx) -> String {
    match &e.kind {
        ExprKind::IntLit(n) => n.to_string(),
        ExprKind::StrLit(s) => format!("\"{}\"", escape_ts_string(s)),
        ExprKind::BoolLit(b) => b.to_string(),
        ExprKind::Ident(id) => {
            // A bare ident whose name matches a declared variant of a sum
            // type (and whose checker type is that sum) is a nullary
            // variant constructor reference. Qualify it as `Type.Variant`.
            // Otherwise (locals, params, `self`) emit the identifier as-is.
            if let Some(Ty::Named {
                kind: NamedKind::Sum,
                name: type_name,
            }) = cx.commons.expr_types.get(&e.span)
                && let Some(decl) = cx.commons.types.get(type_name)
                && let TypeBody::Sum(s) = &decl.body
                && s.variants.iter().any(|v| v.name.name == id.name)
            {
                return format!("{}.{}", type_name, id.name);
            }
            id.name.clone()
        }
        ExprKind::Call(name, args) => {
            // Bare variant constructor with payload → qualify.
            let args_lowered: Vec<String> = args.iter().map(|a| lower_expr(a, stmts, cx)).collect();
            if let Some(Ty::Named {
                kind: NamedKind::Sum,
                name: type_name,
            }) = cx.commons.expr_types.get(&e.span)
                && type_name != &name.name
            {
                return format!("{}.{}({})", type_name, name.name, args_lowered.join(", "));
            }
            format!("{}({})", name.name, args_lowered.join(", "))
        }
        ExprKind::UnaryOp(op, inner) => {
            let inner = lower_expr(inner, stmts, cx);
            let sym = match op {
                UnaryOp::Neg => "-",
                UnaryOp::Not => "!",
            };
            format!("{sym}{inner}")
        }
        ExprKind::BinOp(op, lhs, rhs) => {
            // For `&&` we need to lower `is` bindings into the rhs scope.
            // We handle that here by collecting bindings from lhs, emitting
            // them as `const` declarations before evaluating rhs — but
            // `&&` short-circuits, so simply emitting them inline is wrong.
            // We compile `lhs && (...is binding flow...) rhs` to a function
            // expression: `(lhs && ((bindings) => rhs)())`. Simpler: rely
            // on TypeScript's narrowing for the value-from-is part of
            // `is` patterns. For now, for the special pattern `x is Ok(n)`
            // we lower the rhs assuming the binding `n = x.value` was
            // captured. We use a parenthesised IIFE to scope the binding.
            if *op == BinOp::And
                && let Some((bindings, lhs_expr, rhs_expr)) = lower_and_with_is(lhs, rhs, stmts, cx)
            {
                if bindings.is_empty() {
                    return format!("{lhs_expr} && {rhs_expr}");
                }
                // Emit:  lhs && (() => { const n = ...; return rhs; })()
                let mut wrap = String::new();
                wrap.push_str(&lhs_expr);
                wrap.push_str(" && ((() => { ");
                for b in &bindings {
                    wrap.push_str(b);
                    wrap.push(' ');
                }
                wrap.push_str(&format!("return {rhs_expr}; }})())"));
                return wrap;
            }
            let l = lower_expr(lhs, stmts, cx);
            let r = lower_expr(rhs, stmts, cx);
            if *op == BinOp::Div {
                format!("Math.trunc({l} / {r})")
            } else {
                format!("{l} {} {r}", ts_binop(*op))
            }
        }
        ExprKind::Paren(inner) => {
            let s = lower_expr(inner, stmts, cx);
            format!("({s})")
        }
        ExprKind::Ok(inner) => {
            let s = lower_expr(inner, stmts, cx);
            format!("Ok({s})")
        }
        ExprKind::Err(inner) => {
            let s = lower_expr(inner, stmts, cx);
            format!("Err({s})")
        }
        ExprKind::Some(inner) => {
            let s = lower_expr(inner, stmts, cx);
            format!("Some({s})")
        }
        ExprKind::None => "None".to_string(),
        ExprKind::Question(inner) => {
            let inner_expr = lower_expr(inner, stmts, cx);
            let tmp = cx.fresh();
            stmts.push(format!("const {tmp} = {inner_expr};"));
            stmts.push(format!("if ({tmp}.tag === \"Err\") return {tmp};"));
            format!("{tmp}.value")
        }
        ExprKind::ConstructorCall {
            type_name,
            method,
            args,
        } => {
            let args: Vec<String> = args.iter().map(|a| lower_expr(a, stmts, cx)).collect();
            // Nullary variant qualified construction: `T.V` (no parens) at the
            // source level wouldn't reach here, so `T.V()` always means call.
            format!("{}.{}({})", type_name.name, method.name, args.join(", "))
        }
        ExprKind::RecordConstruction { type_name, fields } => {
            let mut parts = Vec::new();
            for f in fields {
                match &f.value {
                    Some(v) => {
                        let val = lower_expr(v, stmts, cx);
                        parts.push(format!("{}: {}", f.name.name, val));
                    }
                    None => parts.push(f.name.name.clone()),
                }
            }
            let _ = type_name;
            format!("{{ {} }}", parts.join(", "))
        }
        ExprKind::FieldAccess { receiver, field } => {
            let r = lower_expr(receiver, stmts, cx);
            format!("{r}.{}", field.name)
        }
        ExprKind::MethodCall {
            receiver,
            method,
            args,
        } => {
            // Static call: receiver is a bare ident naming a declared type.
            if let ExprKind::Ident(id) = &receiver.kind
                && cx.commons.types.contains_key(&id.name)
            {
                let args_lowered: Vec<String> =
                    args.iter().map(|a| lower_expr(a, stmts, cx)).collect();
                return format!("{}.{}({})", id.name, method.name, args_lowered.join(", "));
            }
            // Instance call: UFCS lowering with the receiver as first arg.
            let ns = cx
                .receiver_namespace(receiver)
                .unwrap_or_else(|| "/* unknown */".to_string());
            let recv = lower_expr(receiver, stmts, cx);
            let mut all = vec![recv];
            for a in args {
                all.push(lower_expr(a, stmts, cx));
            }
            format!("{ns}.{}({})", method.name, all.join(", "))
        }
        ExprKind::If {
            cond,
            then_block,
            else_block,
        } => lower_if(cond, then_block, else_block, stmts, cx),
        ExprKind::Block(b) => lower_block_as_expr(b, cx),
        ExprKind::Match { discriminant, arms } => lower_match_as_iife(discriminant, arms, cx),
        ExprKind::Is { value, pattern } => lower_is(value, pattern, stmts, cx),
    }
}

/// When we encounter `lhs && rhs`, see if lhs is an `is` (possibly wrapped
/// in parens or nested `&&`) and if so collect the bindings to inject into
/// rhs. Returns `(binding_const_decls, lowered_lhs, lowered_rhs)` if
/// special handling is appropriate; otherwise returns None.
fn lower_and_with_is(
    lhs: &Expr,
    rhs: &Expr,
    stmts: &mut Vec<String>,
    cx: &mut LowerCtx,
) -> Option<(Vec<String>, String, String)> {
    let mut bindings = Vec::new();
    let mut found = false;
    gather_is_bindings_for_emit(lhs, cx, &mut bindings, &mut found);
    if !found {
        return None;
    }
    let lhs_expr = lower_expr(lhs, stmts, cx);
    // We lower rhs ourselves (not into the outer stmts), so that any
    // statement-style prefix from rhs is folded into the IIFE properly.
    let mut rhs_stmts = Vec::new();
    let rhs_expr = lower_expr(rhs, &mut rhs_stmts, cx);
    let mut rhs_full = String::new();
    for s in &rhs_stmts {
        rhs_full.push_str(s);
        rhs_full.push(' ');
    }
    rhs_full.push_str(&rhs_expr);
    Some((bindings, lhs_expr, rhs_full))
}

/// Walk an expression collecting `const name = expr.field;` strings for
/// any `is`-pattern bindings on the truthy path. `found` indicates whether
/// at least one `is` was seen.
fn gather_is_bindings_for_emit(e: &Expr, cx: &LowerCtx, out: &mut Vec<String>, found: &mut bool) {
    match &e.kind {
        ExprKind::Is { value, pattern } => {
            *found = true;
            let value_text = value_text_for_is(value);
            let disc_ty = cx.commons.expr_types.get(&value.span).cloned();
            if let Pattern::Variant {
                variant, bindings, ..
            } = pattern
            {
                for (i, b) in bindings.iter().enumerate() {
                    if b.is_wildcard() {
                        continue;
                    }
                    match &b.kind {
                        PatternBindingKind::Named { field, name } => {
                            out.push(format!(
                                "const {name} = {value}.{field};",
                                name = name.name,
                                value = value_text,
                                field = field.name
                            ));
                        }
                        PatternBindingKind::Positional { name } => {
                            let field =
                                cx.positional_field_name(disc_ty.as_ref(), &variant.name, i);
                            out.push(format!(
                                "const {name} = {value}.{field};",
                                name = name.name,
                                value = value_text,
                                field = field
                            ));
                        }
                    }
                }
            }
        }
        ExprKind::BinOp(BinOp::And, l, r) => {
            gather_is_bindings_for_emit(l, cx, out, found);
            gather_is_bindings_for_emit(r, cx, out, found);
        }
        ExprKind::Paren(inner) => gather_is_bindings_for_emit(inner, cx, out, found),
        _ => {}
    }
}

/// Render the receiver of an `is` expression for use in binding lookups.
/// Only simple expressions are sound — for arbitrary call expressions we'd
/// need to lift to a temporary. The checker should reject anything that
/// makes this dangerous; for now we handle ident and member-access cases.
fn value_text_for_is(value: &Expr) -> String {
    match &value.kind {
        ExprKind::Ident(id) => id.name.clone(),
        ExprKind::FieldAccess { receiver, field } => {
            format!("{}.{}", value_text_for_is(receiver), field.name)
        }
        ExprKind::Paren(inner) => value_text_for_is(inner),
        _ => "(/* TODO: complex is-receiver */ )".to_string(),
    }
}

fn lower_if(
    cond: &Expr,
    then_block: &Block,
    else_block: &Block,
    stmts: &mut Vec<String>,
    cx: &mut LowerCtx,
) -> String {
    let cond_expr = lower_expr(cond, stmts, cx);
    // If the cond contains `is`-bindings, the then-branch needs a place
    // for the `const name = receiver.field;` declarations — a ternary
    // has no such place. Force the IIFE form.
    if both_simple(then_block, else_block) && !cond_has_is_bindings(cond) {
        let mut tstmts = Vec::new();
        let testr = lower_expr(&then_block.tail, &mut tstmts, cx);
        debug_assert!(tstmts.is_empty());
        let mut estmts = Vec::new();
        let eestr = lower_expr(&else_block.tail, &mut estmts, cx);
        debug_assert!(estmts.is_empty());
        format!("({cond_expr} ? {testr} : {eestr})")
    } else {
        let mut iife = String::new();
        iife.push_str("(() => {\n");
        iife.push_str("    if (");
        iife.push_str(&cond_expr);
        iife.push_str(") {\n");
        // Inject is-binding declarations on the truthy side.
        let mut is_bindings = Vec::new();
        let mut found = false;
        gather_is_bindings_for_emit(cond, cx, &mut is_bindings, &mut found);
        for b in &is_bindings {
            for _ in 0..(INDENT_STEP * 3) {
                iife.push(' ');
            }
            iife.push_str(b);
            iife.push('\n');
        }
        emit_block_as_function_body(&mut iife, then_block, cx, INDENT_STEP * 3);
        for _ in 0..(INDENT_STEP * 2) {
            iife.push(' ');
        }
        iife.push_str("} else {\n");
        emit_block_as_function_body(&mut iife, else_block, cx, INDENT_STEP * 3);
        for _ in 0..(INDENT_STEP * 2) {
            iife.push(' ');
        }
        iife.push_str("}\n");
        for _ in 0..INDENT_STEP {
            iife.push(' ');
        }
        iife.push_str("})()");
        iife
    }
}

/// True if the expression contains an `is` test with at least one
/// non-wildcard binding. Walks through `&&`, `||`, and parens.
fn cond_has_is_bindings(e: &Expr) -> bool {
    match &e.kind {
        ExprKind::Is {
            pattern: Pattern::Variant { bindings, .. },
            ..
        } => bindings.iter().any(|b| !b.is_wildcard()),
        ExprKind::BinOp(BinOp::And, l, r) | ExprKind::BinOp(BinOp::Or, l, r) => {
            cond_has_is_bindings(l) || cond_has_is_bindings(r)
        }
        ExprKind::Paren(inner) => cond_has_is_bindings(inner),
        _ => false,
    }
}

fn emit_if_tail(
    out: &mut String,
    cond: &Expr,
    then_block: &Block,
    else_block: &Block,
    cx: &mut LowerCtx,
    indent: usize,
) {
    let mut pre = Vec::new();
    let cond_expr = lower_expr(cond, &mut pre, cx);
    for s in &pre {
        write_line(out, indent, s);
    }
    write_line(out, indent, &format!("if ({cond_expr}) {{"));
    // is-binding declarations on the truthy path.
    let mut is_bindings = Vec::new();
    let mut found = false;
    gather_is_bindings_for_emit(cond, cx, &mut is_bindings, &mut found);
    for b in &is_bindings {
        write_line(out, indent + INDENT_STEP, b);
    }
    emit_block_as_function_body(out, then_block, cx, indent + INDENT_STEP);
    write_line(out, indent, "} else {");
    emit_block_as_function_body(out, else_block, cx, indent + INDENT_STEP);
    write_line(out, indent, "}");
}

fn both_simple(a: &Block, b: &Block) -> bool {
    a.statements.is_empty()
        && b.statements.is_empty()
        && simple_expr(&a.tail)
        && simple_expr(&b.tail)
}

fn simple_expr(e: &Expr) -> bool {
    match &e.kind {
        ExprKind::Question(_) => false,
        ExprKind::Match { .. } => false,
        ExprKind::Block(b) => b.statements.is_empty() && simple_expr(&b.tail),
        ExprKind::If {
            then_block,
            else_block,
            cond,
        } => simple_expr(cond) && both_simple(then_block, else_block),
        ExprKind::Ok(i) | ExprKind::Err(i) | ExprKind::Some(i) => simple_expr(i),
        ExprKind::Paren(i) | ExprKind::UnaryOp(_, i) => simple_expr(i),
        ExprKind::BinOp(_, l, r) => simple_expr(l) && simple_expr(r),
        ExprKind::Call(_, args) | ExprKind::ConstructorCall { args, .. } => {
            args.iter().all(simple_expr)
        }
        ExprKind::MethodCall { receiver, args, .. } => {
            simple_expr(receiver) && args.iter().all(simple_expr)
        }
        ExprKind::FieldAccess { receiver, .. } => simple_expr(receiver),
        ExprKind::RecordConstruction { fields, .. } => fields.iter().all(|f| match &f.value {
            Some(v) => simple_expr(v),
            None => true,
        }),
        ExprKind::Is { value, .. } => simple_expr(value),
        _ => true,
    }
}

fn lower_block_as_expr(b: &Block, cx: &mut LowerCtx) -> String {
    let mut iife = String::new();
    iife.push_str("(() => {\n");
    emit_block_as_function_body(&mut iife, b, cx, INDENT_STEP * 2);
    for _ in 0..INDENT_STEP {
        iife.push(' ');
    }
    iife.push_str("})()");
    iife
}

fn lower_match_as_iife(discriminant: &Expr, arms: &[MatchArm], cx: &mut LowerCtx) -> String {
    let disc_ty = cx.commons.expr_types.get(&discriminant.span).cloned();
    let mut stmts = Vec::new();
    let disc = lower_expr(discriminant, &mut stmts, cx);
    let mut iife = String::new();
    // Pre-statements need to be evaluated before the IIFE; lift them into
    // a sequence: `(prestmt1, prestmt2, iife)`. Since TS doesn't let us
    // evaluate statements inline, we wrap in another arrow.
    let inner_iife = build_match_iife(&disc, &disc_ty, arms, cx);
    if stmts.is_empty() {
        iife.push_str(&inner_iife);
    } else {
        iife.push_str("(() => {\n");
        for s in &stmts {
            for _ in 0..(INDENT_STEP * 2) {
                iife.push(' ');
            }
            iife.push_str(s);
            iife.push('\n');
        }
        for _ in 0..(INDENT_STEP * 2) {
            iife.push(' ');
        }
        iife.push_str("return ");
        iife.push_str(&inner_iife);
        iife.push_str(";\n");
        for _ in 0..INDENT_STEP {
            iife.push(' ');
        }
        iife.push_str("})()");
    }
    iife
}

fn build_match_iife(
    disc_expr: &str,
    disc_ty: &Option<Ty>,
    arms: &[MatchArm],
    cx: &mut LowerCtx,
) -> String {
    let mut out = String::new();
    out.push_str("((__d) => {\n");
    for _ in 0..(INDENT_STEP * 2) {
        out.push(' ');
    }
    out.push_str("switch (__d.tag) {\n");
    for arm in arms {
        emit_match_case(&mut out, "__d", disc_ty, arm, cx, INDENT_STEP * 3);
    }
    for _ in 0..(INDENT_STEP * 2) {
        out.push(' ');
    }
    out.push_str("}\n");
    for _ in 0..(INDENT_STEP * 2) {
        out.push(' ');
    }
    out.push_str("throw new Error(\"non-exhaustive match\");\n");
    for _ in 0..INDENT_STEP {
        out.push(' ');
    }
    out.push_str(&format!("}})({disc_expr})"));
    out
}

fn emit_match_tail(
    out: &mut String,
    discriminant: &Expr,
    arms: &[MatchArm],
    cx: &mut LowerCtx,
    indent: usize,
) {
    let mut pre = Vec::new();
    let disc = lower_expr(discriminant, &mut pre, cx);
    let disc_ty = cx.commons.expr_types.get(&discriminant.span).cloned();
    for s in &pre {
        write_line(out, indent, s);
    }
    write_line(out, indent, &format!("switch ({disc}.tag) {{"));
    for arm in arms {
        emit_match_case(out, &disc, &disc_ty, arm, cx, indent + INDENT_STEP);
    }
    write_line(out, indent, "}");
    write_line(out, indent, "throw new Error(\"non-exhaustive match\");");
}

fn emit_match_case(
    out: &mut String,
    disc_var: &str,
    disc_ty: &Option<Ty>,
    arm: &MatchArm,
    cx: &mut LowerCtx,
    indent: usize,
) {
    match &arm.pattern {
        Pattern::Wildcard(_) => {
            write_line(out, indent, "default: {");
            emit_match_body(out, &arm.body, cx, indent + INDENT_STEP);
            write_line(out, indent, "}");
        }
        Pattern::Variant {
            variant, bindings, ..
        } => {
            write_line(
                out,
                indent,
                &format!("case \"{tag}\": {{", tag = variant.name),
            );
            for (i, b) in bindings.iter().enumerate() {
                if b.is_wildcard() {
                    continue;
                }
                let field = match &b.kind {
                    PatternBindingKind::Named { field, .. } => field.name.clone(),
                    PatternBindingKind::Positional { .. } => {
                        cx.positional_field_name(disc_ty.as_ref(), &variant.name, i)
                    }
                };
                let local = b.local_name().name.clone();
                write_line(
                    out,
                    indent + INDENT_STEP,
                    &format!("const {local} = {disc_var}.{field};"),
                );
            }
            emit_match_body(out, &arm.body, cx, indent + INDENT_STEP);
            write_line(out, indent, "}");
        }
    }
}

fn emit_match_body(out: &mut String, body: &MatchBody, cx: &mut LowerCtx, indent: usize) {
    match body {
        MatchBody::Expr(e) => {
            let mut stmts = Vec::new();
            let v = lower_expr(e, &mut stmts, cx);
            for s in &stmts {
                write_line(out, indent, s);
            }
            write_line(out, indent, &format!("return {v};"));
        }
        MatchBody::Block(b) => emit_block_as_function_body(out, b, cx, indent),
    }
}

fn lower_is(value: &Expr, pattern: &Pattern, stmts: &mut Vec<String>, cx: &mut LowerCtx) -> String {
    let v = lower_expr(value, stmts, cx);
    match pattern {
        Pattern::Wildcard(_) => "true".to_string(),
        Pattern::Variant { variant, .. } => {
            format!("{v}.tag === \"{}\"", variant.name)
        }
    }
}

fn ts_base(b: BaseType) -> &'static str {
    match b {
        BaseType::Int => "number",
        BaseType::String => "string",
        BaseType::Bool => "boolean",
    }
}

fn ts_type_ref(r: &TypeRef) -> String {
    match r {
        TypeRef::Base(b, _) => ts_base(*b).to_string(),
        TypeRef::Named(id) => id.name.clone(),
        TypeRef::Result(t, e, _) => format!("Result<{}, {}>", ts_type_ref(t), ts_type_ref(e)),
        TypeRef::Option(t, _) => format!("Option<{}>", ts_type_ref(t)),
        TypeRef::ValidationError(_) => "ValidationError".to_string(),
    }
}

fn ts_binop(op: BinOp) -> &'static str {
    match op {
        BinOp::Or => "||",
        BinOp::And => "&&",
        BinOp::Eq => "===",
        BinOp::NotEq => "!==",
        BinOp::Lt => "<",
        BinOp::LtEq => "<=",
        BinOp::Gt => ">",
        BinOp::GtEq => ">=",
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
    }
}

fn escape_ts_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c => out.push(c),
        }
    }
    out
}

#[allow(dead_code)]
fn _unused_hashmap(_h: HashMap<String, ()>) {}
