// Generated by bynkc — do not edit by hand.
// context shop.orders

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type __JsonValue, type __BoundaryError, type __ServiceBinding, __callService, __boundaryError } from "../../../runtime.js";

import type * as shop_payment from "../../shop-payment/handlers.js";

export const place = {
  async call(qty: number, deps: { env: { SHOP_PAYMENT: __ServiceBinding } }): globalThis.Promise<boolean> {
    return __callService(deps.env.SHOP_PAYMENT, "authorise", ((v: number) => { if (!globalThis.Number.isSafeInteger(v)) throw new globalThis.Error("Int outside the safe-integer range at boundary"); return v as __JsonValue; })(qty), (__j: __JsonValue) => ((__v) => typeof __v === "boolean" ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "$", expected: "boolean", actual: typeof __v } as __BoundaryError))(__j), "shop.orders", "b5e747de6448afda");
  },
};
