// Generated by bynkc — do not edit by hand.
// Worker entry point for context `commerce.payment`.

import { Ok, Err, type Result, type __JsonValue, type __BoundaryError, __boundaryError } from "../../runtime.js";
import { compose, type Env } from "./compose.js";
import * as handlers from "./handlers.js";

export default {
  async fetch(request: globalThis.Request, env: Env): globalThis.Promise<globalThis.Response> {
    const url = new globalThis.URL(request.url);
    const path = url.pathname;
    const method = request.method;
    const surface = compose(env);
    let __route: string = "request";
    try {
      if (path.startsWith("/_bynk/call/")) {
        const servicePath = path.slice("/_bynk/call/".length);
        switch (servicePath) {
          case "authorise": {
            __route = "call authorise";
            const __contract = request.headers.get("X-Bynk-Contract");
            if (__contract !== "938adff5c562387b") {
              globalThis.console.error("ContractMismatch commerce.payment call authorise", { service: "authorise", expected: "938adff5c562387b", actual: globalThis.String(__contract).slice(0, 16) });
              return new globalThis.Response(globalThis.JSON.stringify({ kind: "ContractMismatch", service: "authorise", expected: "938adff5c562387b", actual: __contract }), { status: 409, headers: { "content-type": "application/json" } });
            }
            const args = await request.json() as __JsonValue;
            const __r_amount = handlers.__deserialise_Money(args, "$");
            if (__r_amount.tag === "Err") return new globalThis.Response(globalThis.JSON.stringify(__r_amount.error), { status: 400, headers: { "content-type": "application/json" } });
            const amount = __r_amount.value;
            const result = await surface.authorise(amount);
            const body = handlers.__serialise_Result_AuthId_PaymentError(result);
            return new globalThis.Response(globalThis.JSON.stringify(body), { status: 200, headers: { "content-type": "application/json" } });
          }
          default:
            return new globalThis.Response("Not found", { status: 404 });
        }
      }

      return new globalThis.Response("Not Found", { status: 404 });
    } catch (e) {
      globalThis.console.error(`commerce.payment ${__route} faulted`, e);
      return new globalThis.Response("Internal Server Error", { status: 500 });
    }
  },
};
