// Generated by bynkc — do not edit by hand.
// Worker entry point for context `items`.

import { Ok, Err, type Result, type __JsonValue, type __BoundaryError, __boundaryError, __matchPath, __httpResultToResponse, type __SecurityPolicy, __applySecurityHeaders } from "../../runtime.js";
import { compose, type Env } from "./compose.js";
import * as handlers from "./handlers.js";

export default {
  async fetch(request: globalThis.Request, env: Env): globalThis.Promise<globalThis.Response> {
    const url = new globalThis.URL(request.url);
    const path = url.pathname;
    const method = request.method;
    const surface = compose(env);
    const __security_api: __SecurityPolicy = { nosniff: true, hstsMaxAgeSecs: null };
    let __route: string = "request";
    try {
      if (path.startsWith("/_bynk/call/")) {
        const servicePath = path.slice("/_bynk/call/".length);
        switch (servicePath) {
          default:
            return new globalThis.Response("Not found", { status: 404 });
        }
      }

      {
        const __m = __matchPath("/items/:id", path);
        if (method === "PUT" && __m) {
          __route = "PUT /items/:id";
          const __raw_id = __m.params["id"];
          const __r_id = handlers.ItemId.of(__raw_id);
          if (__r_id.tag === "Err") return __applySecurityHeaders(new globalThis.Response(globalThis.JSON.stringify({ kind: "RefinementViolation", path: "path.id", violation: __r_id.error }), { status: 400, headers: { "content-type": "application/json" } }), __security_api);
          const id = __r_id.value;
          let __body_json: __JsonValue;
          try {
            __body_json = (await request.json()) as __JsonValue;
          } catch {
            return __applySecurityHeaders(new globalThis.Response(globalThis.JSON.stringify({ kind: "MalformedJson", details: "Invalid request body" }), { status: 400, headers: { "content-type": "application/json" } }), __security_api);
          }
          const __r_body = handlers.__deserialise_UpdateItem(__body_json, "$");
          if (__r_body.tag === "Err") return __applySecurityHeaders(new globalThis.Response(globalThis.JSON.stringify(__r_body.error), { status: 400, headers: { "content-type": "application/json" } }), __security_api);
          const body = __r_body.value;
          const result = await surface.http_PUT_items_Param_id(id, body);
          return __applySecurityHeaders(__httpResultToResponse(result, handlers.__serialise_ItemView), __security_api);
        }
      }
      if (__matchPath("/items/:id", path) !== null) {
        const __status = method === "OPTIONS" ? 204 : 405;
        const __res = new globalThis.Response(null, { status: __status, headers: { allow: "OPTIONS, PUT" } });
        return __applySecurityHeaders(__res, __security_api);
      }
      return new globalThis.Response("Not Found", { status: 404 });
    } catch (e) {
      globalThis.console.error(`items ${__route} faulted`, e);
      return new globalThis.Response("Internal Server Error", { status: 500 });
    }
  },
};
