// Generated by bynkc — do not edit by hand.
// composition root for `shop.one` Worker.

import { type __ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";

export interface Env {
  GRID: __DurableObjectNamespace;
  LABEL: __DurableObjectNamespace;
  ORDER: __DurableObjectNamespace;
  TALLY: __DurableObjectNamespace;
}

type __DurableObjectNamespace = { idFromName(name: string): { toString(): string }; get(id: any): any };

export function compose(env: Env) {
  const deps = { env };
  return {
    async doubled(n: number) {
      return handlers.doubled.call(n, deps);
    },
    async label(id: string) {
      return handlers.label.call(id, deps);
    },
    async name(id: handlers.OrderId) {
      return handlers.name.call(id, deps);
    },
    async sum(x: number, y: number) {
      return handlers.sum.call(x, y, deps);
    },
  };
}
