// Generated by bynkc — do not edit by hand.
// composition root for `demo.desk` Worker.

import { type __ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";

export interface Env {
  DEMO_VAULT: __ServiceBinding;
}

export function compose(env: Env) {
  const deps = { env };
  return {
    async check(n: number) {
      return handlers.check.call(n, deps);
    },
    async local(n: number) {
      return handlers.local.call(n, deps);
    },
  };
}
