// Generated by bynkc — do not edit by hand.
// context commerce.notifications

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

import { EventEnvelope } from "../bynk.js";
import { PaymentConfirmed } from "./order.js";

import * as commerce_order from "./order.js";

export const OnPayment = {
  async event(e: PaymentConfirmed, env: EventEnvelope, deps: {}): Promise<void> {
    return undefined;
  },
};

export interface CommerceNotificationsDeps {
  readonly surface: { order: ReturnType<typeof commerce_order.makeSurface> };
}

export function makeSurface(deps: CommerceNotificationsDeps) {
  return {
  };
}

