// Generated by bynkc — do not edit by hand.
// context api

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, HttpResult, QueueResult, type JsonValue, type BoundaryError, type ServiceBinding, callService, boundaryError } from "../../runtime.js";

import { Cents as __CommonsCents } from "../../money/cents.js";

export type Cents = __CommonsCents & { readonly __ctxBrand: "api" };
export const Cents = {
  of(value: number): Result<Cents, ValidationError> { return __CommonsCents.of(value) as unknown as Result<Cents, ValidationError>; },
};

/**
 * Golden coverage for P7.2 (#1300)'s `brand_assertion` fix: a `uses`-commons
 * named type reaching the entry as an HTTP POST body and as a queue message.
 * `deserialise_Cents` is a straight re-export from `money.js` and so returns the
 * *unbranded* commons `Cents`, while `intake.call`/`credit.message` (in
 * `handlers.ts`) are typed against the *branded* `Cents` this context rebrands —
 * without the entry-side brand-assertion cast, `tsc --strict` rejects both
 * generated projects.
 */

export const intake = {
  async http_POST_cents(body: Cents, deps: {}): Promise<HttpResult<number>> {
    return HttpResult.Created(body);
  },
};

export const credit = {
  async queue_credit_0(amount: Cents, deps: {}): Promise<QueueResult> {
    return QueueResult.Ack;
  },
};

import { serialise_Cents, deserialise_Cents } from "../../money/cents.js";
export { serialise_Cents, deserialise_Cents };

