// Generated by bynkc — do not edit by hand.
// commons thing

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

export type Widget = number & { readonly __brand: "Widget" };

export const Widget = {
  of(value: number): Result<Widget, ValidationError> {
    if (!Number.isInteger(value)) {
      return Err({ field: "Widget", message: "must be an integer", value });
    }
    if (!(value >= 0)) {
      return Err({ field: "Widget", message: "must be non-negative", value });
    }
    return Ok(value as Widget);
  },
  fromInt(n: number): Result<Widget, ValidationError> {
    return Widget.of(n);
  },
};

