// Generated by bynkc — do not edit by hand.
// commons envelope

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export type ApiResult<T> =
    { readonly tag: "Loaded"; readonly value: T }
  | { readonly tag: "Failed"; readonly message: string };

export const ApiResult = {
  Loaded: <T>(value: T): ApiResult<T> => ({ tag: "Loaded", value }),
  Failed: <T>(message: string): ApiResult<T> => ({ tag: "Failed", message }),
};

export interface User {
  readonly id: number;
  readonly name: string;
}

export const User = {
};

export type Tree<A> =
    { readonly tag: "Leaf"; readonly value: A }
  | { readonly tag: "Empty" };

export const Tree = {
  Leaf: <A>(value: A): Tree<A> => ({ tag: "Leaf", value }),
  Empty: { tag: "Empty" } as Tree<never>,
};

export function succeed(u: User): ApiResult<User> {
  return ApiResult.Loaded(u);
}

export function fail_for(u: User): ApiResult<User> {
  const r: ApiResult<User> = ApiResult.Failed("not found");
  return r;
}

export function name_or_default(r: ApiResult<User>): string {
  switch (r.tag) {
    case "Loaded": {
      const v = r.value;
      return v.name;
    }
    case "Failed": {
      const m = r.message;
      return m;
    }
  }
  throw new Error("non-exhaustive match");
}

export function empty_tree(): Tree<number> {
  return Tree.Empty;
}

export function leaf_value(t: Tree<number>): number {
  switch (t.tag) {
    case "Leaf": {
      const value = t.value;
      return value;
    }
    case "Empty": {
      return 0;
    }
  }
  throw new Error("non-exhaustive match");
}

