// Generated by bynkc — do not edit by hand.
// test target: app.bundle

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";
import * as app_bundle from "./../app/bundle.js";
import * as bynk_locale from "./../bynk/locale.js";
import * as bynk_locale_types from "./../bynk/locale/types.js";

class ExpectationError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number, detail: string) {
    super(`${detail}\n  at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkExpectFailure(location: string, start: number, end: number, detail: string) {
  return new ExpectationError(location, start, end, detail);
}
function __bynkExpect(cond: boolean, location: string, start: number, end: number, detail: string): void {
  if (!cond) { throw __bynkExpectFailure(location, start, end, detail); }
}
function __bynkShow(v: unknown): string {
  try { return typeof v === "bigint" ? String(v) : (JSON.stringify(v) ?? String(v)); } catch { return String(v); }
}

function makeTestDeps() {
  return {  };
}

// case tier: unit
async function test_the_reference_locale_still_renders_its_own_translation() {
  try {
    const deps = {};
    const { render } = app_bundle as any;
    const { message, renderArg, withMoment, withNum, withText, withWhole } = bynk_locale as any;
    const { LocaleTag, Message, MessageArg } = bynk_locale_types as any;
    const msg = withWhole(withText(message("greeting"), "name", "Ada"), "age", 30);
    if (!(render(("en" as any), msg) === "Hello, Ada, you are 30")) { throw __bynkExpectFailure("tests/bundle.test.bynk:10:12", 421, 466, "expect render(\"en\", msg) == \"Hello, Ada, you are 30\"\n  expected: render(\"en\", msg) == \"Hello, Ada, you are 30\"\n  actual:   " + __bynkShow((render(("en" as any), msg))) + " == " + __bynkShow(("Hello, Ada, you are 30"))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_second__declared_locale_renders_its_own_translation() {
  try {
    const deps = {};
    const { render } = app_bundle as any;
    const { message, renderArg, withMoment, withNum, withText, withWhole } = bynk_locale as any;
    const { LocaleTag, Message, MessageArg } = bynk_locale_types as any;
    const msg = withWhole(withText(message("greeting"), "name", "Ada"), "age", 30);
    if (!(render(("fr" as any), msg) === "30 ans, bonjour Ada")) { throw __bynkExpectFailure("tests/bundle.test.bynk:15:12", 629, 671, "expect render(\"fr\", msg) == \"30 ans, bonjour Ada\"\n  expected: render(\"fr\", msg) == \"30 ans, bonjour Ada\"\n  actual:   " + __bynkShow((render(("fr" as any), msg))) + " == " + __bynkShow(("30 ans, bonjour Ada"))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_locale_not_declared_in_the_bundle_falls_back_to_the_reference() {
  try {
    const deps = {};
    const { render } = app_bundle as any;
    const { message, renderArg, withMoment, withNum, withText, withWhole } = bynk_locale as any;
    const { LocaleTag, Message, MessageArg } = bynk_locale_types as any;
    const msg = withWhole(withText(message("greeting"), "name", "Ada"), "age", 30);
    if (!(render(("de" as any), msg) === "Hello, Ada, you are 30")) { throw __bynkExpectFailure("tests/bundle.test.bynk:20:12", 844, 889, "expect render(\"de\", msg) == \"Hello, Ada, you are 30\"\n  expected: render(\"de\", msg) == \"Hello, Ada, you are 30\"\n  actual:   " + __bynkShow((render(("de" as any), msg))) + " == " + __bynkShow(("Hello, Ada, you are 30"))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_code_no_locale_declares_falls_back_to_bynk_locale_render_s_floor() {
  try {
    const deps = {};
    const { render } = app_bundle as any;
    const { message, renderArg, withMoment, withNum, withText, withWhole } = bynk_locale as any;
    const { LocaleTag, Message, MessageArg } = bynk_locale_types as any;
    const msg = withWhole(message("nope"), "x", 5);
    if (!(render(("fr" as any), msg) === "nope {x=5}")) { throw __bynkExpectFailure("tests/bundle.test.bynk:25:12", 1033, 1066, "expect render(\"fr\", msg) == \"nope {x=5}\"\n  expected: render(\"fr\", msg) == \"nope {x=5}\"\n  actual:   " + __bynkShow((render(("fr" as any), msg))) + " == " + __bynkShow(("nope {x=5}"))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run(only?: string) {
  const results = [];
  const want = (n: string): boolean => only === undefined || only === n;
  if (want("the reference locale still renders its own translation")) results.push({ name: "the reference locale still renders its own translation", ...(await test_the_reference_locale_still_renders_its_own_translation()) });
  if (want("a second, declared locale renders its own translation")) results.push({ name: "a second, declared locale renders its own translation", ...(await test_a_second__declared_locale_renders_its_own_translation()) });
  if (want("a locale not declared in the bundle falls back to the reference")) results.push({ name: "a locale not declared in the bundle falls back to the reference", ...(await test_a_locale_not_declared_in_the_bundle_falls_back_to_the_reference()) });
  if (want("a code no locale declares falls back to bynk.locale.render's floor")) results.push({ name: "a code no locale declares falls back to bynk.locale.render's floor", ...(await test_a_code_no_locale_declares_falls_back_to_bynk_locale_render_s_floor()) });
  return results;
}
