// Generated by bynkc — do not edit by hand.
// commons shipping.rates

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../../runtime.js";

export type Rate = number & { readonly __brand: "Rate" };

export const Rate = {
  of(value: number): Result<Rate, ValidationError> {
    if (!Number.isInteger(value)) {
      return Err({ field: "Rate", message: "must be an integer", value });
    }
    if (!(value >= 0)) {
      return Err({ field: "Rate", message: "must be non-negative", value });
    }
    return Ok(value as Rate);
  },
  fromInt(n: number): Result<Rate, ValidationError> {
    return Rate.of(n);
  },
};

