//! Events track, slice 0 (spine #936, ADR 0284): the fan-out Durable Object.
//!
//! One instance per *publishing* context. Cloudflare requires a DO's
//! `class_name` to resolve to an export of the Worker's `main` module, so
//! this is emitted as its own file (`events_fanout.ts`) and re-exported from
//! `index.ts` — mirroring how an agent's DO class lives in `handlers.ts` and
//! is re-exported the same way, except an event fan-out has no backing
//! `AgentDecl` to emit from, so this is hand-built rather than reusing
//! `emit_agent`. The subscriber registry (who gets `E`) is fully compile-time
//! known (`discover_event_subscribers` in `project.rs`), so it is baked in as
//! a literal routing table rather than carried on the wire.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use crate::emitter::wrangler::{EVENTS_FANOUT_CLASS_NAME, consumed_binding_name};

/// The Worker-relative specifier `events_fanout.ts` imports the runtime
/// from — same depth as `compose.ts` (`workers/<worker>/events_fanout.ts`).
const EVENTS_FANOUT_RUNTIME_SPECIFIER: &str = "../../runtime.js";

/// `context`: the publishing context's qualified name (used only in the
/// header comment). `routes`: this context's own declared event type names →
/// their subscribers, as `(subscriber_context, subscriber_service)` pairs —
/// already sorted (`discover_event_subscribers` sorts each `Vec`), so the
/// generated table (and so the fan-out order for a multi-subscriber event) is
/// deterministic build to build.
pub(crate) fn emit_events_fanout_do(
    context: &str,
    routes: &BTreeMap<String, Vec<(String, String)>>,
) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by bynkc — do not edit by hand.");
    let _ = writeln!(
        out,
        "// Events fan-out Durable Object for context `{context}` (spine #936, ADR 0284)."
    );
    writeln!(out).unwrap();
    let _ = writeln!(
        out,
        "import type {{ DurableObjectState, ServiceBinding }} from \"{EVENTS_FANOUT_RUNTIME_SPECIFIER}\";"
    );
    let _ = writeln!(
        out,
        "import {{ deliverEvent }} from \"{EVENTS_FANOUT_RUNTIME_SPECIFIER}\";"
    );
    writeln!(out).unwrap();
    let _ = writeln!(out, "interface FanoutEvent {{");
    let _ = writeln!(out, "  type: string;");
    let _ = writeln!(out, "  payload: unknown;");
    // Events track, slice 2 (spine #936): minted once at emission
    // (`lower.rs`'s `__events.push`), forwarded here unchanged and always —
    // whether a subscriber's own handler actually declared the optional
    // second `env: EventEnvelope` parameter is decided downstream, at the
    // receiving context's entry route, not here.
    let _ = writeln!(
        out,
        "  envelope: {{ eventId: string; publisherId: string; emittedAt: number; schemaVersion: number }};"
    );
    let _ = writeln!(out, "}}");
    writeln!(out).unwrap();
    let _ = writeln!(
        out,
        "const __eventRoutes: Record<string, Array<{{ binding: string; service: string }}>> = {{"
    );
    for (name, subs) in routes {
        let entries: Vec<String> = subs
            .iter()
            .map(|(sub_ctx, sub_svc)| {
                format!(
                    "{{ binding: {:?}, service: {:?} }}",
                    consumed_binding_name(sub_ctx),
                    sub_svc
                )
            })
            .collect();
        let _ = writeln!(out, "  {name:?}: [{}],", entries.join(", "));
    }
    let _ = writeln!(out, "}};");
    writeln!(out).unwrap();
    let _ = writeln!(out, "export class {EVENTS_FANOUT_CLASS_NAME} {{");
    let _ = writeln!(out, "  private env: Record<string, ServiceBinding>;");
    let _ = writeln!(
        out,
        "  constructor(_state: DurableObjectState, env?: unknown) {{"
    );
    let _ = writeln!(
        out,
        "    this.env = (env ?? {{}}) as Record<string, ServiceBinding>;"
    );
    let _ = writeln!(out, "  }}");
    writeln!(out).unwrap();
    let _ = writeln!(out, "  async fetch(request: Request): Promise<Response> {{");
    let _ = writeln!(
        out,
        "    const {{ events }} = (await request.json()) as {{ events: FanoutEvent[] }};"
    );
    let _ = writeln!(out, "    for (const ev of events) {{");
    // `__eventRoutes` is a plain object literal — an event type named
    // "toString"/"constructor"/etc would otherwise resolve off
    // `Object.prototype` (a truthy, non-array value `??` never catches),
    // throwing a `for...of` TypeError outside every per-subscriber `try`/
    // `catch` below. `Array.isArray` closes it without changing the
    // table's own literal-object shape.
    let _ = writeln!(out, "      const subs = __eventRoutes[ev.type];");
    let _ = writeln!(out, "      if (!Array.isArray(subs)) continue;");
    let _ = writeln!(out, "      for (const sub of subs) {{");
    let _ = writeln!(out, "        const binding = this.env[sub.binding];");
    let _ = writeln!(out, "        if (!binding) continue;");
    // ADR 0284: subscriber failure isolation — one subscriber's rejection is
    // logged and does not stop delivery to the remaining subscribers, nor
    // does it propagate back to the (already-committed) publishing handler.
    let _ = writeln!(out, "        try {{");
    let _ = writeln!(
        out,
        "          await deliverEvent(binding, sub.service, ev.payload, ev.envelope);"
    );
    let _ = writeln!(out, "        }} catch (e) {{");
    let _ = writeln!(
        out,
        "          console.error(\"EventsFanout delivery failed\", {{ event: ev.type, service: sub.service, error: String(e) }});"
    );
    let _ = writeln!(out, "        }}");
    let _ = writeln!(out, "      }}");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "    return new Response(null, {{ status: 204 }});");
    let _ = writeln!(out, "  }}");
    let _ = writeln!(out, "}}");
    out
}
