//! Events track, slice 0 (spine #936, ADR 0284): the fan-out Durable Object.
//!
//! One instance per *publishing* context. Cloudflare requires a DO's
//! `class_name` to resolve to an export of the Worker's `main` module, so
//! this is emitted as its own file (`events_fanout.ts`) and re-exported from
//! `index.ts` — mirroring how an agent's DO class lives in `handlers.ts` and
//! is re-exported the same way, except an event fan-out has no backing
//! `AgentDecl` to emit from, so this is hand-built rather than reusing
//! `emit_agent`. The subscriber registry (who gets `E`) is fully compile-time
//! known (`bynk_check::symbols::discover_event_subscribers`), so it is baked in as
//! a literal routing table rather than carried on the wire.
//!
//! Arc C's own first real conversion slice (#1317): builds a real
//! `bynk_ts::TsProgram` directly instead of `writeln!`-ing a `String` — the
//! first `bynk-emit` construction site whose output reaches
//! `Document::Ts` without a `TsStmt::verbatim` wrap.

use std::collections::BTreeMap;

use bynk_ts::{
    TsBinaryOp, TsBindingName, TsClassCtor, TsClassField, TsClassMethod, TsDecl, TsExpr, TsLit,
    TsParam, TsProgram, TsStmt, TsType, TsUnaryOp,
};

use crate::emitter::wrangler::{EVENTS_FANOUT_CLASS_NAME, consumed_binding_name};

/// The Worker-relative specifier `events_fanout.ts` imports the runtime
/// from — same depth as `compose.ts` (`workers/<worker>/events_fanout.ts`).
const EVENTS_FANOUT_RUNTIME_SPECIFIER: &str = "../../runtime.js";

/// `context`: the publishing context's qualified name (used only in the
/// header comment). `routes`: this context's own declared event type names →
/// their subscribers, as `(subscriber_context, subscriber_service)` pairs —
/// already sorted (`discover_event_subscribers` sorts each `Vec`), so the
/// generated table (and so the fan-out order for a multi-subscriber event) is
/// deterministic build to build.
pub(crate) fn emit_events_fanout_do(
    context: &str,
    routes: &BTreeMap<String, Vec<(String, String)>>,
) -> TsProgram {
    let mut program = TsProgram::new();
    program.push(TsStmt::comment(
        "Generated by bynkc — do not edit by hand.",
        None,
    ));
    program.push(TsStmt::comment(
        format!("Events fan-out Durable Object for context `{context}` (spine #936, ADR 0284)."),
        None,
    ));
    program.push(TsStmt::decl(
        TsDecl::Import {
            type_only: true,
            names: vec![
                "DurableObjectState".to_string(),
                "ServiceBinding".to_string(),
            ],
            from: EVENTS_FANOUT_RUNTIME_SPECIFIER.to_string(),
        },
        None,
    ));
    program.push(TsStmt::decl(
        TsDecl::Import {
            type_only: false,
            names: vec!["deliverEvent".to_string()],
            from: EVENTS_FANOUT_RUNTIME_SPECIFIER.to_string(),
        },
        None,
    ));
    program.push(TsStmt::decl(
        TsDecl::Interface {
            name: "FanoutEvent".to_string(),
            members: vec![
                ("type".to_string(), TsType::named("string")),
                ("payload".to_string(), TsType::named("unknown")),
                // Events track, slice 2 (spine #936): minted once at
                // emission (`lower.rs`'s `__events.push`), forwarded here
                // unchanged and always — whether a subscriber's own handler
                // actually declared the optional second `env:
                // EventEnvelope` parameter is decided downstream, at the
                // receiving context's entry route, not here.
                (
                    "envelope".to_string(),
                    TsType::Object(vec![
                        ("eventId".to_string(), TsType::named("string")),
                        ("publisherId".to_string(), TsType::named("string")),
                        ("emittedAt".to_string(), TsType::named("number")),
                        ("schemaVersion".to_string(), TsType::named("number")),
                    ]),
                ),
            ],
        },
        None,
    ));
    program.push(TsStmt::decl(
        TsDecl::ConstDecl {
            name: "__eventRoutes".to_string(),
            ty: Some(TsType::named_with_args(
                "Record",
                vec![
                    TsType::named("string"),
                    TsType::named_with_args(
                        "Array",
                        vec![TsType::Object(vec![
                            ("binding".to_string(), TsType::named("string")),
                            ("service".to_string(), TsType::named("string")),
                        ])],
                    ),
                ],
            )),
            init: event_routes_table(routes),
        },
        None,
    ));
    program.push(TsStmt::decl(
        TsDecl::Export(Box::new(TsDecl::Class {
            name: EVENTS_FANOUT_CLASS_NAME.to_string(),
            fields: vec![TsClassField {
                name: "env".to_string(),
                ty: TsType::named_with_args(
                    "Record",
                    vec![TsType::named("string"), TsType::named("ServiceBinding")],
                ),
                private: true,
            }],
            constructor: Some(events_fanout_ctor()),
            methods: vec![events_fanout_fetch()],
        })),
        None,
    ));
    program
}

/// `{ "<event type>": [{ binding: "...", service: "..." }, ...], ... }` —
/// built from `routes` the same "loop over real data, build real nodes"
/// pattern P7.9 already established for `Ty`/`TypeRef` conversion
/// (`bynk-emit/src/emitter.rs`'s `ts_ty_to_ts_type`/`ts_type_ref_to_ts_type`),
/// here for expressions instead of types. The outer key is pre-quoted
/// (`format!("{name:?}")`, matching the original `write!`-based code
/// byte-for-byte) since `TsExpr::Object`'s own key field is a raw string
/// pushed verbatim, not itself a `TsExpr` — there is no other way to get
/// quotes around an event-type name that isn't a bare identifier.
fn event_routes_table(routes: &BTreeMap<String, Vec<(String, String)>>) -> TsExpr {
    TsExpr::multiline_object(
        routes
            .iter()
            .map(|(name, subs)| {
                let entries = subs
                    .iter()
                    .map(|(sub_ctx, sub_svc)| {
                        TsExpr::object(vec![
                            (
                                "binding".to_string(),
                                TsExpr::Lit(TsLit::Str(consumed_binding_name(sub_ctx))),
                            ),
                            (
                                "service".to_string(),
                                TsExpr::Lit(TsLit::Str(sub_svc.clone())),
                            ),
                        ])
                    })
                    .collect();
                (format!("{name:?}"), TsExpr::Array(entries))
            })
            .collect(),
    )
}

fn events_fanout_ctor() -> TsClassCtor {
    TsClassCtor {
        params: vec![
            TsParam {
                name: "_state".to_string(),
                ty: Some(TsType::named("DurableObjectState")),
                optional: false,
            },
            TsParam {
                name: "env".to_string(),
                ty: Some(TsType::named("unknown")),
                optional: true,
            },
        ],
        body: vec![TsStmt::assign(
            TsExpr::Member {
                object: Box::new(TsExpr::Ident("this".to_string())),
                property: "env".to_string(),
            },
            TsExpr::As {
                expr: Box::new(TsExpr::Binary {
                    op: TsBinaryOp::NullishCoalescing,
                    left: Box::new(TsExpr::Ident("env".to_string())),
                    right: Box::new(TsExpr::object(vec![])),
                }),
                ty: TsType::named_with_args(
                    "Record",
                    vec![TsType::named("string"), TsType::named("ServiceBinding")],
                ),
            },
            None,
        )],
    }
}

fn events_fanout_fetch() -> TsClassMethod {
    TsClassMethod {
        name: "fetch".to_string(),
        is_async: true,
        params: vec![TsParam {
            name: "request".to_string(),
            ty: Some(TsType::named("Request")),
            optional: false,
        }],
        return_type: Some(TsType::named_with_args(
            "Promise",
            vec![TsType::named("Response")],
        )),
        body: vec![
            TsStmt::const_stmt(
                TsBindingName::ObjectPattern(vec!["events".to_string()]),
                None,
                TsExpr::As {
                    expr: Box::new(TsExpr::Await(Box::new(TsExpr::Call {
                        callee: Box::new(TsExpr::Member {
                            object: Box::new(TsExpr::Ident("request".to_string())),
                            property: "json".to_string(),
                        }),
                        args: vec![],
                    }))),
                    ty: TsType::Object(vec![(
                        "events".to_string(),
                        TsType::array(TsType::named("FanoutEvent")),
                    )]),
                },
                None,
            ),
            TsStmt::for_of(
                "ev",
                TsExpr::Ident("events".to_string()),
                TsStmt::block(
                    vec![
                        TsStmt::const_stmt(
                            TsBindingName::Ident("subs".to_string()),
                            None,
                            TsExpr::Index {
                                object: Box::new(TsExpr::Ident("__eventRoutes".to_string())),
                                index: Box::new(TsExpr::Member {
                                    object: Box::new(TsExpr::Ident("ev".to_string())),
                                    property: "type".to_string(),
                                }),
                            },
                            None,
                        ),
                        // `__eventRoutes` is a plain object literal — an
                        // event type named "toString"/"constructor"/etc
                        // would otherwise resolve off `Object.prototype` (a
                        // truthy, non-array value `??` never catches),
                        // throwing a `for...of` TypeError outside every
                        // per-subscriber `try`/`catch` below. `Array.isArray`
                        // closes it without changing the table's own
                        // literal-object shape.
                        TsStmt::if_stmt(
                            TsExpr::Unary {
                                op: TsUnaryOp::Not,
                                expr: Box::new(TsExpr::Call {
                                    callee: Box::new(TsExpr::Member {
                                        object: Box::new(TsExpr::Ident("Array".to_string())),
                                        property: "isArray".to_string(),
                                    }),
                                    args: vec![TsExpr::Ident("subs".to_string())],
                                }),
                            },
                            TsStmt::continue_stmt(None),
                            None,
                        ),
                        TsStmt::for_of(
                            "sub",
                            TsExpr::Ident("subs".to_string()),
                            TsStmt::block(
                                vec![
                                    TsStmt::const_stmt(
                                        TsBindingName::Ident("binding".to_string()),
                                        None,
                                        TsExpr::Index {
                                            object: Box::new(TsExpr::Member {
                                                object: Box::new(TsExpr::Ident("this".to_string())),
                                                property: "env".to_string(),
                                            }),
                                            index: Box::new(TsExpr::Member {
                                                object: Box::new(TsExpr::Ident("sub".to_string())),
                                                property: "binding".to_string(),
                                            }),
                                        },
                                        None,
                                    ),
                                    TsStmt::if_stmt(
                                        TsExpr::Unary {
                                            op: TsUnaryOp::Not,
                                            expr: Box::new(TsExpr::Ident("binding".to_string())),
                                        },
                                        TsStmt::continue_stmt(None),
                                        None,
                                    ),
                                    // ADR 0284: subscriber failure isolation
                                    // — one subscriber's rejection is logged
                                    // and does not stop delivery to the
                                    // remaining subscribers, nor does it
                                    // propagate back to the (already-
                                    // committed) publishing handler.
                                    TsStmt::try_catch(
                                        TsStmt::block(
                                            vec![TsStmt::expr_stmt(
                                                TsExpr::Await(Box::new(TsExpr::Call {
                                                    callee: Box::new(TsExpr::Ident(
                                                        "deliverEvent".to_string(),
                                                    )),
                                                    args: vec![
                                                        TsExpr::Ident("binding".to_string()),
                                                        TsExpr::Member {
                                                            object: Box::new(TsExpr::Ident(
                                                                "sub".to_string(),
                                                            )),
                                                            property: "service".to_string(),
                                                        },
                                                        TsExpr::Member {
                                                            object: Box::new(TsExpr::Ident(
                                                                "ev".to_string(),
                                                            )),
                                                            property: "payload".to_string(),
                                                        },
                                                        TsExpr::Member {
                                                            object: Box::new(TsExpr::Ident(
                                                                "ev".to_string(),
                                                            )),
                                                            property: "envelope".to_string(),
                                                        },
                                                    ],
                                                })),
                                                None,
                                            )],
                                            None,
                                        ),
                                        "e",
                                        TsStmt::block(
                                            vec![TsStmt::expr_stmt(
                                                TsExpr::Call {
                                                    callee: Box::new(TsExpr::Member {
                                                        object: Box::new(TsExpr::Ident(
                                                            "console".to_string(),
                                                        )),
                                                        property: "error".to_string(),
                                                    }),
                                                    args: vec![
                                                        TsExpr::Lit(TsLit::Str(
                                                            "EventsFanout delivery failed"
                                                                .to_string(),
                                                        )),
                                                        TsExpr::object(vec![
                                                            (
                                                                "event".to_string(),
                                                                TsExpr::Member {
                                                                    object: Box::new(
                                                                        TsExpr::Ident(
                                                                            "ev".to_string(),
                                                                        ),
                                                                    ),
                                                                    property: "type".to_string(),
                                                                },
                                                            ),
                                                            (
                                                                "service".to_string(),
                                                                TsExpr::Member {
                                                                    object: Box::new(
                                                                        TsExpr::Ident(
                                                                            "sub".to_string(),
                                                                        ),
                                                                    ),
                                                                    property: "service".to_string(),
                                                                },
                                                            ),
                                                            (
                                                                "error".to_string(),
                                                                TsExpr::Call {
                                                                    callee: Box::new(
                                                                        TsExpr::Ident(
                                                                            "String".to_string(),
                                                                        ),
                                                                    ),
                                                                    args: vec![TsExpr::Ident(
                                                                        "e".to_string(),
                                                                    )],
                                                                },
                                                            ),
                                                        ]),
                                                    ],
                                                },
                                                None,
                                            )],
                                            None,
                                        ),
                                        None,
                                    ),
                                ],
                                None,
                            ),
                            None,
                        ),
                    ],
                    None,
                ),
                None,
            ),
            TsStmt::return_stmt(
                Some(TsExpr::New {
                    callee: Box::new(TsExpr::Ident("Response".to_string())),
                    args: vec![
                        TsExpr::Lit(TsLit::Null),
                        TsExpr::object(vec![(
                            "status".to_string(),
                            TsExpr::Lit(TsLit::Num("204".to_string())),
                        )]),
                    ],
                }),
                None,
            ),
        ],
    }
}

/// Arc C's own first slice (#1317, Decision D/"Done when"): the P7.8-era
/// `bynk-ts` test (`printer.rs`'s own
/// `prints_events_fanout_dos_own_class_byte_identical_to_the_real_emitter`)
/// proves the algebra can represent this file's *class* portion, built from
/// a hand-rebuilt tree — it does not exercise `emit_events_fanout_do`
/// itself, and never covered the header/imports/interface/table at all.
/// This is the fresh, direct test the accepted proposal requires: calls the
/// real, converted function with real-shaped data and asserts the printed
/// output is byte-identical to a real fixture's own `events_fanout.ts`, not
/// a hand-rebuilt approximation of it.
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn matches_the_real_fixtures_own_events_fanout_ts_byte_for_byte() {
        let expected = include_str!(
            "../../../bynkc/tests/fixtures/positive/966_event_field_default_cross_context/\
             expected/workers/commerce-order/events_fanout.ts"
        );
        let mut routes = BTreeMap::new();
        routes.insert(
            "PaymentConfirmed".to_string(),
            vec![(
                "commerce.notifications".to_string(),
                "OnPayment".to_string(),
            )],
        );
        let program = emit_events_fanout_do("commerce.order", &routes);
        let printed = bynk_ts::print(&program, "", "", "");
        assert_eq!(printed.text, expected);
    }
}
