"use strict";
// Generated by bynkc — do not edit by hand.
// system test: shop.api
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.run = run;
const runtime_js_1 = require("../runtime.js");
const shop_api = __importStar(require("../workers/shop-api/handlers.js"));
const index_js_1 = __importDefault(require("../workers/shop-api/index.js"));
class ExpectationError extends Error {
    location;
    start;
    end;
    constructor(location, start, end, detail) {
        super(`${detail}\n  at ${location}`);
        this.location = location;
        this.start = start;
        this.end = end;
    }
}
function __bynkExpectFailure(location, start, end, detail) {
    return new ExpectationError(location, start, end, detail);
}
function __bynkExpect(cond, location, start, end, detail) {
    if (!cond) {
        throw __bynkExpectFailure(location, start, end, detail);
    }
}
function __bynkShow(v) {
    try {
        return typeof v === "bigint" ? String(v) : (JSON.stringify(v) ?? String(v));
    }
    catch {
        return String(v);
    }
}
function makeHarness() {
    const env_shop_api = {};
    env_shop_api.CART = (0, runtime_js_1.makeIntegrationDoNamespace)((state) => new shop_api.Cart(state));
    const rootEnv = {};
    rootEnv.SHOP_API = { fetch: (req) => index_js_1.default.fetch(req, env_shop_api) };
    return { env: rootEnv };
}
function __bynkNow() { return Math.floor(Date.now() / 1000); }
function __b64url(s) { return btoa(s).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, ""); }
function __bytesB64url(bytes) { let bin = ""; for (const b of bytes)
    bin += String.fromCharCode(b); return btoa(bin).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, ""); }
async function __bynkSignHs256(payload, secret) {
    const h = __b64url(JSON.stringify({ alg: "HS256", typ: "JWT" }));
    const p = __b64url(JSON.stringify(payload));
    const enc = new TextEncoder();
    const key = await crypto.subtle.importKey("raw", enc.encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
    const sig = await crypto.subtle.sign("HMAC", key, enc.encode(`${h}.${p}`));
    return `${h}.${p}.${__bytesB64url(new Uint8Array(sig))}`;
}
globalThis.process = globalThis.process ?? { env: {} };
globalThis.process.env["AUTH_SECRET"] = "__bynk_test_secret";
async function __sysdrive_api_http_POST_cart(body, __sub) {
    const __body = JSON.stringify(shop_api.serialise_Item(body));
    const __h = makeHarness();
    const __req = new Request(`https://test/cart`, { method: "POST", headers: { "content-type": "application/json", "authorization": `Bearer ${await __bynkSignHs256({ sub: __sub, exp: __bynkNow() + 3600 }, (globalThis.process?.env?.["AUTH_SECRET"] ?? ""))}`, }, body: __body, });
    const __res = await __h.env.SHOP_API.fetch(__req);
    return (0, runtime_js_1.responseToHttpResult)(__res, shop_api.deserialise_Item);
}
async function __sysdrive_api_http_GET_cart_size(__sub) {
    const __h = makeHarness();
    const __req = new Request(`https://test/cart/size`, { method: "GET", headers: { "authorization": `Bearer ${await __bynkSignHs256({ sub: __sub, exp: __bynkNow() + 3600 }, (globalThis.process?.env?.["AUTH_SECRET"] ?? ""))}`, }, });
    const __res = await __h.env.SHOP_API.fetch(__req);
    return (0, runtime_js_1.responseToHttpResult)(__res, (__j) => ((__v) => typeof __v !== "number" ? (0, runtime_js_1.Err)({ kind: "StructuralMismatch", path: "$", expected: "integer", actual: typeof __v }) : Number.isInteger(__v) ? (0, runtime_js_1.Ok)(__v) : (0, runtime_js_1.Err)({ kind: "StructuralMismatch", path: "$", expected: "integer", actual: String(__v) }))(__j));
}
async function test_a_create_returns_Created_over_the_real_wire() {
    try {
        const deps = makeHarness();
        const item = await __sysdrive_api_http_POST_cart({ sku: "widget" }, "alice");
        if (!(item.tag === "Created")) {
            throw __bynkExpectFailure("shop/tests/api.test.bynk:4:12", 168, 186, "expect item is Created(_)");
        }
        return { pass: true };
    }
    catch (e) {
        if (e instanceof ExpectationError) {
            return { pass: false, error: { message: e.message, location: e.location } };
        }
        return { pass: false, error: { message: String(e), location: "unknown" } };
    }
}
async function test_the_size_read_is_Ok_over_the_wire() {
    try {
        const deps = makeHarness();
        const n = await __sysdrive_api_http_GET_cart_size("bob");
        if (!(n.tag === "Ok")) {
            throw __bynkExpectFailure("shop/tests/api.test.bynk:8:12", 297, 307, "expect n is Ok(_)");
        }
        return { pass: true };
    }
    catch (e) {
        if (e instanceof ExpectationError) {
            return { pass: false, error: { message: e.message, location: e.location } };
        }
        return { pass: false, error: { message: String(e), location: "unknown" } };
    }
}
async function run(only) {
    const results = [];
    const want = (n) => only === undefined || only === n;
    if (want("a create returns Created over the real wire"))
        results.push({ name: "a create returns Created over the real wire", ...(await test_a_create_returns_Created_over_the_real_wire()) });
    if (want("the size read is Ok over the wire"))
        results.push({ name: "the size read is Ok over the wire", ...(await test_the_size_read_is_Ok_over_the_wire()) });
    return results;
}
//# sourceMappingURL=integration_shop_api.test.ts.map
