// Generated by bynkc — do not edit by hand.
// commons tally

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export function tally(xs: readonly number[]): number {
  return ((__xs: readonly number[], __acc: number, __f: (acc: number, x: number) => number) => { for (const __x of __xs) __acc = __f(__acc, __x); return __acc; })(xs, 0, (acc: number, x: number) => acc + x);
}
