// Generated by bynkc — do not edit by hand.
// context commerce.checkout

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type JsonValue, type BoundaryError, type ServiceBinding, callService, boundaryError } from "../../runtime.js";

import { Receipt } from "../commerce-payment/handlers.js";

import type * as commerce_payment from "../commerce-payment/handlers.js";

export const pay = {
  async call(id: string, deps: { env: { COMMERCE_PAYMENT: ServiceBinding } }): Promise<Receipt> {
    return callService(deps.env.COMMERCE_PAYMENT, "authorise", id as JsonValue, deserialise_Receipt, "commerce.checkout", "da78d5301d8df299");
  },
};

export function serialise_Receipt(value: commerce_payment.Receipt): JsonValue {
  return {
    id: value.id as JsonValue,
  };
}

export function deserialise_Receipt(json: JsonValue, path: string = "$"): Result<commerce_payment.Receipt, BoundaryError> {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: JsonValue };
  if (typeof obj["id"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.id`, expected: "string", actual: typeof obj["id"] });
  }
  const __id = obj["id"];
  return Ok({ id: __id } as commerce_payment.Receipt);
}


