// Generated by bynkc — do not edit by hand.
// context counter

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type DurableObjectState, type DurableObjectNamespace, StateRegistry, makeAgent, rehydrationViolation, HttpResult, type JsonValue, type BoundaryError, type ServiceBinding, callService, boundaryError } from "../../runtime.js";

import * as bynk__binding from "../../bynk-cloudflare.js";
import * as bynk from "../../bynk.js";

export interface TallyState {
  readonly total: number;
}

const __TallyRegistry = new StateRegistry();
function __zeroOfTallyState(): TallyState { return { total: 0 }; }

function __rehydrateTallyState(s: TallyState): void {
  { const __r = ((__v) => typeof __v !== "number" ? Err({ kind: "StructuralMismatch", path: "total", expected: "integer", actual: typeof __v } as BoundaryError) : Number.isInteger(__v) ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "total", expected: "integer", actual: String(__v) } as BoundaryError))((s.total as unknown as JsonValue)); if (__r.tag === "Err") throw rehydrationViolation("Tally", __r.error); }
}

export class Tally {
  state: DurableObjectState;
  private __env: unknown;
  constructor(state: DurableObjectState, env?: unknown) {
    this.state = state;
    this.__env = env;
  }

  private async loadState(): Promise<TallyState> {
    const stored = await this.state.storage.get<TallyState>("state");
    if (stored === undefined) return __zeroOfTallyState();
    const __merged = { ...__zeroOfTallyState(), ...stored };
    __rehydrateTallyState(__merged);
    return __merged;
  }

  private async commitState(s: TallyState): Promise<void> {
    await this.state.storage.put("state", s);
  }

  async bump(deps: { Clock: bynk.Clock }): Promise<number> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = await deps.Clock.now();
      const n = __state.total + 1;
      __state.total = n;
      return n;
    })();
    await this.commitState(__state);
    return __result;
  }

  async peek(deps: {}): Promise<number> {
    const __state = await this.loadState();
    return __state.total;
  }

  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname.startsWith("/_bynk/agent/")) {
      const methodName = url.pathname.slice("/_bynk/agent/".length);
      const { args, deps } = (await request.json()) as { args: unknown[]; deps: unknown };
      const env = this.__env as any;
      const __givenDeps = { Clock: new bynk__binding.ClockProvider() };
      const result = await (this as any)[methodName](...args, { ...((deps ?? {}) as Record<string, unknown>), ...__givenDeps });
      return new Response(JSON.stringify(result ?? null), { headers: { "content-type": "application/json" } });
    }
    return new Response("Not Found", { status: 404 });
  }

}

export function __makeTally(key: string, env?: { TALLY?: DurableObjectNamespace }): Tally {
  return makeAgent(__TallyRegistry, env?.TALLY, key, (state) => new Tally(state));
}

export const api = {
  async http_POST_bump(deps: { Clock: bynk.Clock; env: { TALLY: DurableObjectNamespace } }): Promise<HttpResult<number>> {
    const n = await __makeTally("main", deps.env).bump(deps);
    return HttpResult.Ok(n);
  },
};

export function __resetAgents(): void {
  __TallyRegistry.reset();
}

