// Generated by bynkc — do not edit by hand.
// composition root for `api` Worker.

import { type ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";

export interface Env {
}

export function compose(env: Env) {
  const deps = {  };
  return {
    async http_GET_config() {
      return handlers.api.http_GET_config(deps);
    },
    async http_GET_plain() {
      return handlers.api.http_GET_plain(deps);
    },
    async http_GET_private() {
      return handlers.api.http_GET_private(deps);
    },
    async http_GET_ticks() {
      return handlers.api.http_GET_ticks(deps);
    },
    async http_POST_items(body: any) {
      return handlers.api.http_POST_items(body, deps);
    },
  };
}
