// Generated by bynkc — do not edit by hand.
// context shop.orders

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type __DurableObjectState, type __DurableObjectNamespace, __StateRegistry, __makeAgent, __rehydrationViolation, HttpResult, QueueResult, type __JsonValue, type __BoundaryError } from "../runtime.js";

export type UserId = string & { readonly __brand: "shop.orders.UserId" };

export const UserId = {
  of(value: string): Result<UserId, ValidationError> {
    if (!(value.length > 0)) {
      return Err({ field: "UserId", message: "must be non-empty", value });
    }
    return Ok(value as UserId);
  },
};

export interface Item {
  readonly sku: string;
}

export const Item = {
};

export interface CartState {
  readonly items: globalThis.Record<string, Item>;
}

const __CartRegistry = new __StateRegistry();
function __zeroOfCartState(): CartState { return { items: {} }; }

function __rehydrateCartState(s: CartState, stored: CartState): void {
  if (globalThis.Object.prototype.hasOwnProperty.call(stored, "items")) for (const __k of globalThis.Object.keys(s.items)) { const __r = __deserialise_Item((s.items[__k] as unknown as __JsonValue), "items"); if (__r.tag === "Err") throw __rehydrationViolation("Cart", __r.error); s.items[__k] = __r.value as unknown as (typeof s.items)[string]; }
  for (const __k of globalThis.Object.keys(s.items)) { const __r = ((__v) => typeof __v === "string" ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "items", expected: "string", actual: typeof __v } as __BoundaryError))((__k as unknown as __JsonValue)); if (__r.tag === "Err") throw __rehydrationViolation("Cart", __r.error); }
}

function __encodeCartState(s: CartState): globalThis.Record<string, unknown> {
  return { ...s, items: globalThis.Object.fromEntries(globalThis.Object.entries(s.items).map(([__k, __v]) => [__k, __serialise_Item(__v)])) };
}

export class Cart {
  state: __DurableObjectState;
  constructor(state: __DurableObjectState) {
    this.state = state;
  }

  private async loadState(): globalThis.Promise<CartState> {
    const stored = await this.state.storage.get<CartState>("state");
    if (stored === undefined) return __zeroOfCartState();
    const __merged = { ...__zeroOfCartState(), ...stored };
    __rehydrateCartState(__merged, stored);
    return __merged;
  }

  private async commitState(s: CartState): globalThis.Promise<void> {
    await this.state.storage.put("state", __encodeCartState(s));
  }

  async add(sku: string, deps: {}): globalThis.Promise<Item> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const item = { sku: sku };
      const __r0 = await (globalThis.Object.defineProperty(__state.items, sku, { value: item, writable: true, enumerable: true, configurable: true }), undefined);
      return item;
    })();
    await this.commitState(__state);
    return __result;
  }

  async size(deps: {}): globalThis.Promise<number> {
    const __state = await this.loadState();
    return ((() => globalThis.Object.values(__state.items)))().length;
  }

}

export function __makeCart(key: UserId, env?: { CART?: __DurableObjectNamespace }): Cart {
  return __makeAgent(__CartRegistry, env?.CART, key, (state) => new Cart(state));
}

export const api = {
  async http_POST_cart_Param_sku(sku: string, deps: { identity: UserId }): globalThis.Promise<HttpResult<Item>> {
    const item = await __makeCart(deps.identity).add(sku, deps);
    return HttpResult.Created(item);
  },
  async http_GET_cart_size(deps: { identity: UserId }): globalThis.Promise<HttpResult<number>> {
    const n = await __makeCart(deps.identity).size(deps);
    return HttpResult.Ok(n);
  },
};

export const sweeper = {
  async cron_sweeper_0(deps: {}): globalThis.Promise<Result<void, string>> {
    return Ok(undefined);
  },
};

export const intake = {
  async queue_intake_0(item: Item, deps: {}): globalThis.Promise<QueueResult> {
    return QueueResult.Ack;
  },
};

export function __resetAgents(): void {
  __CartRegistry.reset();
}

export interface __ShopOrdersDeps {
}

export function __makeSurface(deps: __ShopOrdersDeps) {
  return {
  };
}

export function __serialise_Item(value: Item): __JsonValue {
  return {
    sku: value.sku as __JsonValue,
  };
}

export function __deserialise_Item(json: __JsonValue, path: string = "$"): Result<Item, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  if (typeof obj["sku"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.sku`, expected: "string", actual: typeof obj["sku"] });
  }
  const __sku = obj["sku"];
  return Ok({ sku: __sku } as Item);
}

