// Generated by bynkc — do not edit by hand.
// context demo.svc

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

export interface Logger {
  log(message: string): globalThis.Promise<void>;
}

export const LoggerToken: symbol = globalThis.Symbol("Logger");

export class ConsoleLogger implements Logger {
  async log(message: string): globalThis.Promise<void> {
    return undefined;
  }
}

export const ConsoleLoggerProvider = { token: LoggerToken, factory: () => new ConsoleLogger() };

