// Generated by bynkc — do not edit by hand.
// commons pair

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export interface Keyed<K, V> {
  readonly key: K;
  readonly value: V;
}

export const Keyed = {
};

export function entry(k: string, v: number): Keyed<string, number> {
  return { key: k, value: v };
}

export function bucket(k: string, vs: readonly number[]): Keyed<string, readonly number[]> {
  return { key: k, value: vs };
}

export function key_of(e: Keyed<string, number>): string {
  return e.key;
}

export function values_of(e: Keyed<string, readonly number[]>): readonly number[] {
  return e.value;
}

