"use strict";
// Generated by bynkc — do not edit by hand.
// composition root for `shop.api` Worker.
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.compose = compose;
const runtime_js_1 = require("../../runtime.js");
const handlers = __importStar(require("./handlers.js"));
function compose(env) {
    const deps = { env };
    return {
        async http_POST_cart(request, body) {
            const __authz = request.headers.get("Authorization");
            if (__authz === null || !__authz.startsWith("Bearer "))
                return runtime_js_1.HttpResult.Unauthorized;
            const __secret = env["AUTH_SECRET"] ?? globalThis.process?.env?.["AUTH_SECRET"];
            if (typeof __secret !== "string")
                return runtime_js_1.HttpResult.Unauthorized;
            const __claims = await (0, runtime_js_1.verifyBearerJwtHs256)(__authz.slice(7), __secret);
            if (__claims.tag === "Err")
                return runtime_js_1.HttpResult.Unauthorized;
            const __id = handlers.UserId.of(__claims.value.sub);
            if (__id.tag === "Err")
                return runtime_js_1.HttpResult.Unauthorized;
            return handlers.api.http_POST_cart(body, { ...deps, identity: __id.value });
        },
        async http_GET_cart_size(request) {
            const __authz = request.headers.get("Authorization");
            if (__authz === null || !__authz.startsWith("Bearer "))
                return runtime_js_1.HttpResult.Unauthorized;
            const __secret = env["AUTH_SECRET"] ?? globalThis.process?.env?.["AUTH_SECRET"];
            if (typeof __secret !== "string")
                return runtime_js_1.HttpResult.Unauthorized;
            const __claims = await (0, runtime_js_1.verifyBearerJwtHs256)(__authz.slice(7), __secret);
            if (__claims.tag === "Err")
                return runtime_js_1.HttpResult.Unauthorized;
            const __id = handlers.UserId.of(__claims.value.sub);
            if (__id.tag === "Err")
                return runtime_js_1.HttpResult.Unauthorized;
            return handlers.api.http_GET_cart_size({ ...deps, identity: __id.value });
        },
    };
}
