"use strict";
// Generated by bynkc — do not edit by hand.
// context shop.api
Object.defineProperty(exports, "__esModule", { value: true });
exports.api = exports.Cart = exports.Item = exports.UserId = void 0;
exports.__makeCart = __makeCart;
exports.__resetAgents = __resetAgents;
exports.serialise_Item = serialise_Item;
exports.deserialise_Item = deserialise_Item;
const runtime_js_1 = require("../../runtime.js");
exports.UserId = {
    of(value) {
        if (!(value.length > 0)) {
            return (0, runtime_js_1.Err)({ field: "UserId", message: "must be non-empty", value });
        }
        return (0, runtime_js_1.Ok)(value);
    },
};
exports.Item = {};
const __CartRegistry = new runtime_js_1.StateRegistry();
function __zeroOfCartState() { return { items: {} }; }
function __rehydrateCartState(s) {
    for (const __v of Object.values(s.items)) {
        const __r = deserialise_Item(__v, "items");
        if (__r.tag === "Err")
            throw (0, runtime_js_1.rehydrationViolation)("Cart", __r.error);
    }
    for (const __k of Object.keys(s.items)) {
        const __r = ((__v) => typeof __v === "string" ? (0, runtime_js_1.Ok)(__v) : (0, runtime_js_1.Err)({ kind: "StructuralMismatch", path: "items", expected: "string", actual: typeof __v }))(__k);
        if (__r.tag === "Err")
            throw (0, runtime_js_1.rehydrationViolation)("Cart", __r.error);
    }
}
class Cart {
    state;
    constructor(state) {
        this.state = state;
    }
    async loadState() {
        const stored = await this.state.storage.get("state");
        if (stored === undefined)
            return __zeroOfCartState();
        const __merged = { ...__zeroOfCartState(), ...stored };
        __rehydrateCartState(__merged);
        return __merged;
    }
    async commitState(s) {
        await this.state.storage.put("state", s);
    }
    async add(sku, deps) {
        const __state = { ...(await this.loadState()) };
        const __result = await (async () => {
            const item = { sku: sku };
            const __r0 = await ((__state.items[sku] = item), undefined);
            return item;
        })();
        await this.commitState(__state);
        return __result;
    }
    async size(deps) {
        const __state = await this.loadState();
        return ((() => Object.values(__state.items)))().length;
    }
    async fetch(request) {
        const url = new URL(request.url);
        if (url.pathname.startsWith("/_bynk/agent/")) {
            const methodName = url.pathname.slice("/_bynk/agent/".length);
            const { args, deps } = (await request.json());
            const result = await this[methodName](...args, deps);
            return new Response(JSON.stringify(result ?? null), { headers: { "content-type": "application/json" } });
        }
        return new Response("Not Found", { status: 404 });
    }
}
exports.Cart = Cart;
function __makeCart(key, env) {
    return (0, runtime_js_1.makeAgent)(__CartRegistry, env?.CART, key, (state) => new Cart(state));
}
exports.api = {
    async http_POST_cart(body, deps) {
        const item = await __makeCart(deps.identity, deps.env).add(body.sku, deps);
        return runtime_js_1.HttpResult.Created(item);
    },
    async http_GET_cart_size(deps) {
        const n = await __makeCart(deps.identity, deps.env).size(deps);
        return runtime_js_1.HttpResult.Ok(n);
    },
};
function __resetAgents() {
    __CartRegistry.reset();
}
function serialise_Item(value) {
    return {
        sku: value.sku,
    };
}
function deserialise_Item(json, path = "$") {
    if (typeof json !== "object" || json === null || Array.isArray(json)) {
        return (0, runtime_js_1.Err)({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
    }
    const obj = json;
    if (typeof obj["sku"] !== "string") {
        return (0, runtime_js_1.Err)({ kind: "StructuralMismatch", path: `${path}.sku`, expected: "string", actual: typeof obj["sku"] });
    }
    const __sku = obj["sku"];
    return (0, runtime_js_1.Ok)({ sku: __sku });
}
//# sourceMappingURL=handlers.ts.map
