// Generated by bynkc — do not edit by hand.
// composition root for `shop.orders` Worker.

import { type __ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";

export interface Env {
  SHOP_PAYMENT: __ServiceBinding;
}

export function compose(env: Env) {
  const deps = { env };
  return {
    async blob(text: string) {
      return handlers.blob.call(text, deps);
    },
    async echo(line: handlers.Line) {
      return handlers.echo.call(line, deps);
    },
    async place(line: handlers.Line) {
      return handlers.place.call(line, deps);
    },
  };
}
