// Generated by bynkc — do not edit by hand.
// Worker entry point for context `api`.

import { Ok, Err, type Result, type __JsonValue, type __BoundaryError, __boundaryError } from "../../runtime.js";
import { compose, type Env } from "./compose.js";
import * as handlers from "./handlers.js";

export default {
  async fetch(request: globalThis.Request, env: Env): globalThis.Promise<globalThis.Response> {
    const url = new globalThis.URL(request.url);
    const path = url.pathname;
    const method = request.method;
    const surface = compose(env);
    let __route: string = "request";
    try {
      if (path.startsWith("/_bynk/call/")) {
        const servicePath = path.slice("/_bynk/call/".length);
        switch (servicePath) {
          case "results": {
            __route = "call results";
            const __contract = request.headers.get("X-Bynk-Contract");
            if (__contract !== "5e9e8ed4e53d519f") {
              globalThis.console.error("ContractMismatch api call results", { service: "results", expected: "5e9e8ed4e53d519f", actual: globalThis.String(__contract).slice(0, 16) });
              return new globalThis.Response(globalThis.JSON.stringify({ kind: "ContractMismatch", service: "results", expected: "5e9e8ed4e53d519f", actual: __contract }), { status: 409, headers: { "content-type": "application/json" } });
            }
            const args = await request.json() as __JsonValue;
            const __r_input = handlers.__deserialise_ApiResult_User(args, "$");
            if (__r_input.tag === "Err") return new globalThis.Response(globalThis.JSON.stringify(__r_input.error), { status: 400, headers: { "content-type": "application/json" } });
            const input = __r_input.value;
            const result = await surface.results(input);
            const body = handlers.__serialise_Result_ApiResult_User_Unit(result);
            return new globalThis.Response(globalThis.JSON.stringify(body), { status: 200, headers: { "content-type": "application/json" } });
          }
          default:
            return new globalThis.Response("Not found", { status: 404 });
        }
      }

      return new globalThis.Response("Not Found", { status: 404 });
    } catch (e) {
      globalThis.console.error(`api ${__route} faulted`, e);
      return new globalThis.Response("Internal Server Error", { status: 500 });
    }
  },
};
