// Generated by bynkc — do not edit by hand.
// context shop.api

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type __DurableObjectState, type __DurableObjectNamespace, __StateRegistry, __makeAgent, type __AgentWire, __decodeAgentArgs, __encodeAgentResult, __rehydrationViolation, HttpResult, type __JsonValue, type __BoundaryError, type __ServiceBinding, __callService, __boundaryError } from "../../runtime.js";

export type UserId = string & { readonly __brand: "shop.api.UserId" };

export const UserId = {
  of(value: string): Result<UserId, ValidationError> {
    if (!(value.length > 0)) {
      return Err({ field: "UserId", message: "must be non-empty", value });
    }
    return Ok(value as UserId);
  },
};

export type Sku = string & { readonly __brand: "shop.api.Sku" };

export const Sku = {
  of(value: string): Result<Sku, ValidationError> {
    if (!(value.length > 0)) {
      return Err({ field: "Sku", message: "must be non-empty", value });
    }
    if (!(value.length <= 8)) {
      return Err({ field: "Sku", message: "length must be at most 8", value });
    }
    return Ok(value as Sku);
  },
};

export interface Item {
  readonly sku: Sku;
}

export const Item = {
};

export interface CartState {
  readonly items: globalThis.Record<string, Item>;
}

const __CartRegistry = new __StateRegistry();
function __zeroOfCartState(): CartState { return { items: {} }; }

function __rehydrateCartState(s: CartState, stored: CartState): void {
  if (globalThis.Object.prototype.hasOwnProperty.call(stored, "items")) for (const __k of globalThis.Object.keys(s.items)) { const __r = __deserialise_Item((s.items[__k] as unknown as __JsonValue), "items"); if (__r.tag === "Err") throw __rehydrationViolation("Cart", __r.error); s.items[__k] = __r.value as unknown as (typeof s.items)[string]; }
  for (const __k of globalThis.Object.keys(s.items)) { const __r = ((__v) => typeof __v === "string" ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "items", expected: "string", actual: typeof __v } as __BoundaryError))((__k as unknown as __JsonValue)); if (__r.tag === "Err") throw __rehydrationViolation("Cart", __r.error); }
}

function __encodeCartState(s: CartState): globalThis.Record<string, unknown> {
  return { ...s, items: globalThis.Object.fromEntries(globalThis.Object.entries(s.items).map(([__k, __v]) => [__k, __serialise_Item(__v)])) };
}

export class Cart {
  state: __DurableObjectState;
  constructor(state: __DurableObjectState) {
    this.state = state;
  }

  private async loadState(): globalThis.Promise<CartState> {
    const stored = await this.state.storage.get<CartState>("state");
    if (stored === undefined) return __zeroOfCartState();
    const __merged = { ...__zeroOfCartState(), ...stored };
    __rehydrateCartState(__merged, stored);
    return __merged;
  }

  private async commitState(s: CartState): globalThis.Promise<void> {
    await this.state.storage.put("state", __encodeCartState(s));
  }

  async add(item: Item, deps: {}): globalThis.Promise<Item> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = await (globalThis.Object.defineProperty(__state.items, item.sku, { value: item, writable: true, enumerable: true, configurable: true }), undefined);
      return item;
    })();
    await this.commitState(__state);
    return __result;
  }

  async fetch(request: globalThis.Request): globalThis.Promise<globalThis.Response> {
    const url = new globalThis.URL(request.url);
    if (url.pathname.startsWith("/_bynk/agent/")) {
      const methodName = url.pathname.slice("/_bynk/agent/".length);
      const { args, deps } = (await request.json()) as { args: unknown[]; deps: unknown };
      const result = await (this as unknown as globalThis.Record<string, (...bynkArgs: unknown[]) => unknown>)[methodName](...__decodeAgentArgs(__CartWire, methodName, args), deps);
      return new globalThis.Response(globalThis.JSON.stringify(__encodeAgentResult(__CartWire, methodName, result)), { headers: { "content-type": "application/json" } });
    }
    return new globalThis.Response("Not Found", { status: 404 });
  }

}

const __CartWire: __AgentWire = {
  add: { args: [{ enc: __serialise_Item, dec: __deserialise_Item }], result: { enc: __serialise_Item, dec: __deserialise_Item } },
};

export function __makeCart(key: UserId, env?: { CART?: __DurableObjectNamespace }): Cart {
  return __makeAgent(__CartRegistry, env?.CART, key, (state) => new Cart(state), __CartWire);
}

export const api = {
  async http_POST_cart(body: Item, deps: { env: { CART: __DurableObjectNamespace }; identity: UserId }): globalThis.Promise<HttpResult<Item>> {
    const saved = await __makeCart(deps.identity, deps.env).add(body, deps);
    return HttpResult.Created(saved);
  },
  async http_POST_reject(body: Item, deps: { identity: UserId }): globalThis.Promise<HttpResult<Item>> {
    return HttpResult.BadRequest("the handler ran and rejected it");
  },
  async http_PUT_cart_Param_sku(sku: Sku, body: Item, deps: { identity: UserId }): globalThis.Promise<HttpResult<Item>> {
    return HttpResult.Created(body);
  },
};

export function __resetAgents(): void {
  __CartRegistry.reset();
}

export function __serialise_Item(value: Item): __JsonValue {
  return {
    sku: __serialise_Sku(value.sku),
  };
}

export function __deserialise_Item(json: __JsonValue, path: string = "$"): Result<Item, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  const __r_sku = __deserialise_Sku(obj["sku"], `${path}.sku`);
  if (__r_sku.tag === "Err") return __r_sku;
  const __sku = __r_sku.value;
  return Ok({ sku: __sku } as Item);
}

export function __serialise_Sku(value: Sku): __JsonValue {
  return value as unknown as string;
}

export function __deserialise_Sku(json: __JsonValue, path: string = "$"): Result<Sku, __BoundaryError> {
  if (typeof json !== "string") {
    return Err({ kind: "StructuralMismatch", path, expected: "string", actual: typeof json });
  }
  const validated = (typeof (Sku as unknown as { of?: (json: unknown) => Result<unknown, ValidationError> }).of === "function")
    ? (Sku as unknown as { of: (json: unknown) => Result<unknown, ValidationError> }).of(json)
    : (Ok(json as unknown as Sku) as Result<unknown, ValidationError>);
  if (validated.tag === "Err") {
    return Err({ kind: "RefinementViolation", path, violation: validated.error });
  }
  return Ok(validated.value as Sku);
}


