// Generated by bynkc — do not edit by hand.
// context commerce.payment

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type JsonValue, type BoundaryError, type ServiceBinding, callService, boundaryError } from "../../runtime.js";

export interface Receipt {
  readonly id: string;
}

export const Receipt = {
};

export const authorise = {
  async call(id: string, deps: {}): Promise<Receipt> {
    return { id: id };
  },
};

export function serialise_Receipt(value: Receipt): JsonValue {
  return {
    id: value.id as JsonValue,
  };
}

export function deserialise_Receipt(json: JsonValue, path: string = "$"): Result<Receipt, BoundaryError> {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: JsonValue };
  if (typeof obj["id"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.id`, expected: "string", actual: typeof obj["id"] });
  }
  const __id = obj["id"];
  return Ok({ id: __id } as Receipt);
}


