// Generated by bynkc — do not edit by hand.
// composition root

import * as demo_desk from "./demo/desk.js";
import * as demo_ledger from "./demo/ledger.js";
import * as demo_vault from "./demo/vault.js";

export function composeApp() {
  const demo_vaultDeps = {  };
  const demo_vaultSurface = demo_vault.makeSurface(demo_vaultDeps);
  const demo_deskDeps = { surface: { Vault: demo_vaultSurface } };
  const demo_deskSurface = demo_desk.makeSurface(demo_deskDeps);
  const demo_ledgerDeps = { Audit: new demo_ledger.SilentAudit() };
  const demo_ledgerSurface = demo_ledger.makeSurface(demo_ledgerDeps);

  return {
    desk: demo_deskSurface,
    ledger: demo_ledgerSurface,
    vault: demo_vaultSurface,
  };
}
