// Generated by bynkc — do not edit by hand.
// commons probe

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export type PositiveInt = number & { readonly __brand: "PositiveInt" };

export const PositiveInt = {
  of(value: number): Result<PositiveInt, ValidationError> {
    if (!globalThis.Number.isSafeInteger(value)) {
      return Err({ field: "PositiveInt", message: "must be a safe integer", value });
    }
    if (!(value > 0)) {
      return Err({ field: "PositiveInt", message: "must be positive", value });
    }
    return Ok(value as PositiveInt);
  },
};

export function classify(n: number): boolean {
  if (n > 0) {
    const __r0 = n;
    return (globalThis.Number.isSafeInteger(__r0) && __r0 > 0);
  } else {
    const __r1 = n;
    return (globalThis.Number.isSafeInteger(__r1) && __r1 > 0);
  }
}
