// Generated by bynkc — do not edit by hand.
// context demo

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type DurableObjectState, type DurableObjectNamespace, StateRegistry, makeAgent, rehydrationViolation, type JsonValue, type BoundaryError } from "./runtime.js";

export interface Box {
  readonly n: number;
}

export const Box = {
  put(self: Box, x: number): Promise<void> {
    return Promise.resolve(undefined);
  },
};

export interface WidgetState {
  readonly items: Record<string, number>;
}

const __WidgetRegistry = new StateRegistry();
function __zeroOfWidgetState(): WidgetState { return { items: {} }; }

function __rehydrateWidgetState(s: WidgetState): void {
  for (const __v of Object.values(s.items)) { const __r = ((__v) => typeof __v !== "number" ? Err({ kind: "StructuralMismatch", path: "items", expected: "integer", actual: typeof __v } as BoundaryError) : Number.isInteger(__v) ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "items", expected: "integer", actual: String(__v) } as BoundaryError))((__v as unknown as JsonValue)); if (__r.tag === "Err") throw rehydrationViolation("Widget", __r.error); }
  for (const __k of Object.keys(s.items)) { const __r = ((__v) => typeof __v === "string" ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "items", expected: "string", actual: typeof __v } as BoundaryError))((__k as unknown as JsonValue)); if (__r.tag === "Err") throw rehydrationViolation("Widget", __r.error); }
}

export class Widget {
  state: DurableObjectState;
  constructor(state: DurableObjectState) {
    this.state = state;
  }

  private async loadState(): Promise<WidgetState> {
    const stored = await this.state.storage.get<WidgetState>("state");
    if (stored === undefined) return __zeroOfWidgetState();
    const __merged = { ...__zeroOfWidgetState(), ...stored };
    __rehydrateWidgetState(__merged);
    return __merged;
  }

  private async commitState(s: WidgetState): Promise<void> {
    await this.state.storage.put("state", s);
  }

  async shadowedName(items: Box, x: number, deps: {}): Promise<void> {
    const __state = await this.loadState();
    const __r0 = await Box.put(items, x);
    return undefined;
  }

}

export function __makeWidget(key: string, env?: { WIDGET?: DurableObjectNamespace }): Widget {
  return makeAgent(__WidgetRegistry, env?.WIDGET, key, (state) => new Widget(state));
}

export function __resetAgents(): void {
  __WidgetRegistry.reset();
}

