// Generated by bynkc — do not edit by hand.
// commons demo

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, __bynkIntDiv, __bynkToInt } from "./runtime.js";

export function formula(a: number, b: number): number {
  return __bynkIntDiv((a + b) * (a - b), 2);
}

