// Generated by karnc — do not edit by hand.
// context demo.svc

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

export const echo = {
  async call(message: string, deps: {}): Promise<string> {
    return message;
  },
};

export function makeSurface(deps: Parameters<typeof echo.call>[1]) {
  return {
    async echo(message: string): Promise<string> {
      return echo.call(message, deps);
    },
  };
}

