// Generated by bynkc — do not edit by hand.
// Worker entry point for context `greet`.

import { Ok, Err, type Result, type JsonValue, type BoundaryError, boundaryError, matchPath, httpResultToResponse, headResponse, notModifiedIfMatch } from "../../runtime.js";
import { compose, type Env } from "./compose.js";
import * as handlers from "./handlers.js";

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    const path = url.pathname;
    const method = request.method;
    const surface = compose(env);
    try {
      if (path.startsWith("/_bynk/call/")) {
        const servicePath = path.slice("/_bynk/call/".length);
        switch (servicePath) {
          default:
            return new Response("Not found", { status: 404 });
        }
      }

      {
        if ((method === "GET" || method === "HEAD") && path === "/ping") {
          const result = await surface.http_GET_ping();
          const __response = notModifiedIfMatch(httpResultToResponse(result, (v: any) => v as JsonValue, { weakEtag: true }), request);
          return method === "HEAD" ? headResponse(__response) : __response;
        }
      }
      if (path === "/ping") {
        const __status = method === "OPTIONS" ? 204 : 405;
        const __res = new Response(null, { status: __status, headers: { allow: "GET, HEAD, OPTIONS" } });
        return __res;
      }
      return new Response("Not Found", { status: 404 });
    } catch {
      return new Response("Internal Server Error", { status: 500 });
    }
  },
};
