// Generated by bynkc — do not edit by hand.
// Worker entry point for context `assets`.

import { Ok, Err, type Result, type __JsonValue, type __BoundaryError, __boundaryError, __matchPath, __httpResultToResponse, __headResponse, __notModifiedIfMatch, type __SecurityPolicy, __applySecurityHeaders } from "../../runtime.js";
import { compose, type Env } from "./compose.js";
import * as handlers from "./handlers.js";

export default {
  async fetch(request: globalThis.Request, env: Env): globalThis.Promise<globalThis.Response> {
    const url = new globalThis.URL(request.url);
    const path = url.pathname;
    const method = request.method;
    const surface = compose(env);
    const __security_Assets: __SecurityPolicy = { nosniff: true, hstsMaxAgeSecs: null };
    let __route: string = "request";
    try {
      if (path.startsWith("/_bynk/call/")) {
        const servicePath = path.slice("/_bynk/call/".length);
        switch (servicePath) {
          default:
            return new globalThis.Response("Not found", { status: 404 });
        }
      }

      {
        if ((method === "GET" || method === "HEAD") && path === "/pixel.png") {
          __route = "GET /pixel.png";
          const result = await surface.http_GET_pixel_png();
          const __response = __applySecurityHeaders(__notModifiedIfMatch(__httpResultToResponse(result, (__v: void) => null, { weakEtag: true }), request), __security_Assets);
          return method === "HEAD" ? __headResponse(__response) : __response;
        }
      }
      {
        if ((method === "GET" || method === "HEAD") && path === "/sitemap.xml") {
          __route = "GET /sitemap.xml";
          const result = await surface.http_GET_sitemap_xml();
          const __response = __applySecurityHeaders(__notModifiedIfMatch(__httpResultToResponse(result, (__v: void) => null, { weakEtag: true }), request), __security_Assets);
          return method === "HEAD" ? __headResponse(__response) : __response;
        }
      }
      {
        const __m = __matchPath("/robots/:mode", path);
        if ((method === "GET" || method === "HEAD") && __m) {
          __route = "GET /robots/:mode";
          const __raw_mode = __m.params["mode"];
          const mode = __raw_mode;
          const result = await surface.http_GET_robots_Param_mode(mode);
          const __response = __applySecurityHeaders(__notModifiedIfMatch(__httpResultToResponse(result, (__v: void) => null, { weakEtag: true }), request), __security_Assets);
          return method === "HEAD" ? __headResponse(__response) : __response;
        }
      }
      if (path === "/pixel.png") {
        const __status = method === "OPTIONS" ? 204 : 405;
        const __res = new globalThis.Response(null, { status: __status, headers: { allow: "GET, HEAD, OPTIONS" } });
        return __applySecurityHeaders(__res, __security_Assets);
      }
      if (__matchPath("/robots/:mode", path) !== null) {
        const __status = method === "OPTIONS" ? 204 : 405;
        const __res = new globalThis.Response(null, { status: __status, headers: { allow: "GET, HEAD, OPTIONS" } });
        return __applySecurityHeaders(__res, __security_Assets);
      }
      if (path === "/sitemap.xml") {
        const __status = method === "OPTIONS" ? 204 : 405;
        const __res = new globalThis.Response(null, { status: __status, headers: { allow: "GET, HEAD, OPTIONS" } });
        return __applySecurityHeaders(__res, __security_Assets);
      }
      return new globalThis.Response("Not Found", { status: 404 });
    } catch (e) {
      globalThis.console.error(`assets ${__route} faulted`, e);
      return new globalThis.Response("Internal Server Error", { status: 500 });
    }
  },
};
