// Generated by bynkc — do not edit by hand.
// bynk surface binding for the `cloudflare` platform.
import type { Clock, Fetch, Locale, Logger, Random, Secrets } from "./bynk.js";
import type { Request as FetchRequest, Response as FetchResponse } from "./bynk.js";
import { FetchError, Uuid } from "./bynk.js";
import { LocaleTag } from "./bynk/locale/types.js";
import { Err, None, Ok, Some, negotiateLocale, type Option, type Result } from "./runtime.js";

export class ClockProvider implements Clock {
  async now(): Promise<number> {
    return Date.now();
  }
}

export class RandomProvider implements Random {
  async uuid(): Promise<Uuid> {
    const r = Uuid.of(crypto.randomUUID());
    if (r.tag === "Err") {
      throw new Error("unreachable: crypto.randomUUID() yields a valid UUID");
    }
    return r.value;
  }
  async int(lo: number, hi: number): Promise<number> {
    return lo + Math.floor(Math.random() * (hi - lo));
  }
}

export class LoggerProvider implements Logger {
  async info(msg: string): Promise<void> {
    console.log(msg);
  }
  async error(msg: string): Promise<void> {
    console.error(msg);
  }
}

export class FetchProvider implements Fetch {
  async send(req: FetchRequest): Promise<Result<FetchResponse, FetchError>> {
    const headers: Record<string, string> = {};
    if (req.contentType.tag === "Some") {
      headers["content-type"] = req.contentType.value;
    }
    if (req.authorization.tag === "Some") {
      headers["authorization"] = req.authorization.value;
    }
    try {
      const res = await fetch(req.url, {
        method: req.method.tag.toUpperCase(),
        headers,
        body: req.body.tag === "Some" ? req.body.value : undefined,
      });
      return Ok({ status: res.status, body: await res.text() });
    } catch (e) {
      const name = e instanceof Error ? e.name : "";
      return Err(name === "TimeoutError" || name === "AbortError" ? FetchError.Timeout : FetchError.Network);
    }
  }
}

export class SecretsProvider implements Secrets {
  // Decision [B]: explicit env first (workers compose passes it), then a
  // `globalThis` probe of `process.env` (bundle under node) — never bare
  // `process`, which would demand @types/node at the tsc gate. A declared field +
  // assigning constructor, not a parameter property: the latter is non-erasable
  // by pure type-stripping (the strip-only emission invariant, ADR 0136).
  private env?: unknown;
  constructor(env?: unknown) {
    this.env = env;
  }
  async get(name: string): Promise<Option<string>> {
    const fromEnv = (this.env as Record<string, unknown> | undefined)?.[name];
    if (typeof fromEnv === "string") {
      return Some(fromEnv);
    }
    const v = (globalThis as any).process?.env?.[name];
    return typeof v === "string" ? Some(v) : None;
  }
}

// Locale capability track, slice 2 (#882): real Accept-Language negotiation
// on the one platform with an inbound request to negotiate from. `request`/
// `declaredLocales`/`referenceLocale` are threaded in by the emitter only
// when this Worker's context has a uniquely-detected message bundle
// (`bynk-emit/src/project.rs`, `detect_context_message_bundle`); every other
// construction site (Bundle mode, a bundle-less Workers context) still calls
// `new LocaleProvider()`, which behaves exactly as slice 1 shipped it.
export class LocaleProvider implements Locale {
  // De-sugared from a constructor parameter property (declared field +
  // assigning constructor instead): a parameter property isn't
  // strip-removable — it implicitly declares *and* assigns a field, which
  // breaks both `--inspect` debug sessions and the in-browser eval path
  // (`bynkc/tests/tsc_verify.rs`'s `all_emitted_typescript_strips_under_node`
  // gate catches this class of construct).
  private request?: Request;
  private declaredLocales: readonly string[];
  private referenceLocale: string;

  constructor(
    request?: Request,
    declaredLocales: readonly string[] = [],
    referenceLocale: string = "en",
  ) {
    this.request = request;
    this.declaredLocales = declaredLocales;
    this.referenceLocale = referenceLocale;
  }

  async current(): Promise<LocaleTag> {
    const negotiated = negotiateLocale(
      this.request?.headers.get("accept-language"),
      this.declaredLocales,
      this.referenceLocale,
    );
    const r = LocaleTag.of(negotiated);
    if (r.tag === "Err") {
      throw new Error(
        "unreachable: negotiateLocale returns only already-valid declared/reference tags",
      );
    }
    return r.value;
  }
}
