// Generated by bynkc — do not edit by hand.
// composition root

import * as app_web from "./app/web.js";
import * as bynk__binding from "./bynk-cloudflare.js";

export function composeApp() {
  const app_webDeps = { Locale: new bynk__binding.LocaleProvider() };
  const app_webSurface = app_web.makeSurface(app_webDeps);

  return {
    web: app_webSurface,
  };
}
