// Generated by bynkc — do not edit by hand.
// context boundary.provider

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

export type Token = string & { readonly __brand: "boundary.provider.Token" };

export const Token = {
  of(value: string): Result<Token, ValidationError> {
    if (!(value.length > 0)) {
      return Err({ field: "Token", message: "must be non-empty", value });
    }
    return Ok(value as Token);
  },
};

export const verify = {
  async call(token: Token, deps: {}): Promise<Result<number, number>> {
    return Ok(0);
  },
};

export interface BoundaryProviderDeps {
}

export function makeSurface(deps: BoundaryProviderDeps) {
  return {
    async verify(token: Token): Promise<Result<number, number>> {
      return verify.call(token, deps);
    },
  };
}

