// Generated by bynkc — do not edit by hand.
// composition root for `api` Worker.

import { type ServiceBinding, HttpResult, verifyOidcJwt } from "../../runtime.js";
import * as handlers from "./handlers.js";

export interface Env {
}

export function compose(env: Env) {
  const deps = {  };
  return {
    async http_GET_me(request: Request) {
      const __authz = request.headers.get("Authorization");
      if (__authz === null || !__authz.startsWith("Bearer ")) return HttpResult.Unauthorized;
      const __claims = await verifyOidcJwt(__authz.slice(7), "https://issuer.example.com", "my-api", "https://issuer.example.com/.well-known/jwks.json");
      if (__claims.tag === "Err") return HttpResult.Unauthorized;
      const __id = handlers.UserId.of(__claims.value.sub);
      if (__id.tag === "Err") return HttpResult.Unauthorized;
      return handlers.api.http_GET_me({ ...deps, identity: __id.value });
    },
  };
}
