// Generated by bynkc — do not edit by hand.
// context demo.vault

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

export interface Vault {
  open(): globalThis.Promise<number>;
}

export const __VaultToken: symbol = globalThis.Symbol("Vault");

export class RealVault implements Vault {
  async open(): globalThis.Promise<number> {
    return 1;
  }
}

export const __RealVaultProvider = { token: __VaultToken, factory: () => new RealVault() };

export const box = {
  async call(deps: { Vault: Vault }): globalThis.Promise<number> {
    const a = await deps.Vault.open();
    return a + 1;
  },
};

export interface __DemoVaultDeps {
  readonly Vault: Vault;
}

export function __makeSurface(deps: __DemoVaultDeps) {
  return {
    async box(): globalThis.Promise<number> {
      return box.call(deps);
    },
  };
}
