// Generated by bynkc — do not edit by hand.
// composition root for `forecast.lookup` Worker.

import { type __ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";
import * as weather__binding from "../../weather.binding.js";

export interface Env {
}

export function compose(env: Env) {
  const Weather = new weather__binding.FixedWeather();
  const deps = { Weather };
  return {
    async lookup(city: string) {
      return handlers.lookup.call(city, deps);
    },
  };
}
