// Generated by bynkc — do not edit by hand.
// context forecast.lookup

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type __JsonValue, type __BoundaryError, type __ServiceBinding, __callService, __boundaryError } from "../../runtime.js";

import { Report, WeatherError } from "../../weather.js";

import * as weather from "../../weather.js";
import { __serialise_Report, __deserialise_Report, __serialise_WeatherError, __deserialise_WeatherError } from "../../weather.js";

export const lookup = {
  async call(city: string, deps: { Weather: weather.Weather }): globalThis.Promise<Result<Report, WeatherError>> {
    const r = await deps.Weather.current(city);
    return r;
  },
};

export { __serialise_Report, __deserialise_Report, __serialise_WeatherError, __deserialise_WeatherError };

export function __serialise_Result_Report_WeatherError(value: Result<Report, WeatherError>): __JsonValue {
  if (value.tag === "Ok") return { kind: "Ok", value: __serialise_Report(value.value) };
  return { kind: "Err", error: __serialise_WeatherError(value.error) };
}

export function __deserialise_Result_Report_WeatherError(json: __JsonValue, path: string = "$"): Result<Result<Report, WeatherError>, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  if (obj["kind"] === "Ok") {
  const __r_v = __deserialise_Report(obj["value"], `${path}.value`);
  if (__r_v.tag === "Err") return __r_v;
  const __v = __r_v.value;
    return Ok(Ok(__v) as Result<Report, WeatherError>);
  } else if (obj["kind"] === "Err") {
  const __r_e = __deserialise_WeatherError(obj["error"], `${path}.error`);
  if (__r_e.tag === "Err") return __r_e;
  const __e = __r_e.value;
    return Ok(Err(__e) as Result<Report, WeatherError>);
  }
  return Err({ kind: "StructuralMismatch", path, expected: "Ok | Err", actual: String(obj["kind"]) });
}
