// Generated by bynkc — do not edit by hand.
// commons app.bundle

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

import { LocaleTag, Message, MessageArg } from "../bynk/locale/types.js";
import { render as __bynkLocaleRender, renderArg } from "../bynk/locale.js";

const messagesByLocale: Record<string, Record<string, (params: ReadonlyMap<string, MessageArg>) => string>> = {
  /**
   * message-bundles slice 3 (#878): a `select` placeholder with arbitrary
   * (non-CLDR) keys, plus its mandatory `other` arm as the fallback for an
   * undeclared key.
   */
  "en": {
    "greeting": (params: ReadonlyMap<string, MessageArg>): string => ((__arg) => { if (__arg === undefined || __arg.tag !== "Text") { return "{g}"; } const __arms: Record<string, string> = { "male": "He", "female": "She", "other": "They" }; return Object.hasOwn(__arms, __arg.value) ? __arms[__arg.value] : __arms["other"]; })(params.get("g")) + " liked this.",
  },
};

export const messagesReferenceLocale: LocaleTag = ("en" as string) as LocaleTag;
export const messagesLocales: readonly LocaleTag[] = [("en" as string) as LocaleTag];

export function render(tag: LocaleTag, msg: Message): string {
  const __localeTable = messagesByLocale[tag];
  const __referenceTable = messagesByLocale[messagesReferenceLocale];
  const __entry = (__localeTable !== undefined ? __localeTable[msg.code] : undefined) ?? __referenceTable[msg.code];
  if (__entry !== undefined) {
    return __entry(msg.params);
  }
  return __bynkLocaleRender(tag, msg);
}

