// Generated by bynkc — do not edit by hand.
// context cache.store

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type __JsonValue, type __BoundaryError, type __ServiceBinding, __callService, __boundaryError } from "../../runtime.js";

import * as bynk_cloudflare from "../../bynk/cloudflare.js";

export const cache = {
  async call(key: string, value: string, deps: { Kv: bynk_cloudflare.Kv }): globalThis.Promise<Option<string>> {
    const previous = await deps.Kv.get(key);
    const __r0 = await deps.Kv.put(key, value);
    const __r1 = await deps.Kv.delete("stale");
    return previous;
  },
};

export function __serialise_Option_String(value: Option<string>): __JsonValue {
  if (value.tag === "Some") return { kind: "Some", value: value.value as __JsonValue };
  return { kind: "None" };
}

function __option_value_String(raw: __JsonValue, at: string): Result<unknown, __BoundaryError> {
  if (typeof raw !== "string") {
    return Err({ kind: "StructuralMismatch", path: at, expected: "string", actual: typeof raw });
  }
  const __v = raw;
  return Ok(__v);
}

export function __deserialise_Option_String(json: __JsonValue, path: string = "$"): Result<Option<string>, __BoundaryError> {
  if (json === undefined || json === null) {
    return Ok(None as Option<string>);
  }
  if (typeof json === "object" && !globalThis.Array.isArray(json)) {
    const obj = json as { [k: string]: __JsonValue };
    const __keys = globalThis.Object.keys(obj);
    if (obj["kind"] === "None" && __keys.length === 1) {
      return Ok(None as Option<string>);
    }
    if (obj["kind"] === "Some" && __keys.length === 2 && "value" in obj) {
      const __t = __option_value_String(obj["value"], `${path}.value`);
      if (__t.tag === "Err") {
        return __t;
      }
      return Ok(Some(__t.value as string) as Option<string>);
    }
  }
  const __b = __option_value_String(json, path);
  if (__b.tag === "Ok") {
    return Ok(Some(__b.value as string) as Option<string>);
  }
  if (__b.error.kind === "StructuralMismatch" && __b.error.path === path && !__b.error.expected.endsWith(" | null | {\"kind\": \"None\"} | {\"kind\": \"Some\", \"value\": ...}")) {
    return Err({ ...__b.error, expected: __b.error.expected + " | null | {\"kind\": \"None\"} | {\"kind\": \"Some\", \"value\": ...}" });
  }
  return __b;
}
