// Generated by bynkc — do not edit by hand.
// commons demo.box

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, __bynkEq } from "../runtime.js";

/**
 * #1702 review: a method that compares its receiver's type parameter accepts an
 * equality-supporting receiver, and one that does not compare it accepts a
 * function. Its suite runs both (#1703: a suite can now target a unit that
 * declares a generic type).
 */

export interface Box<A> {
  readonly value: A;
}

export const Box = {
  has<A>(self: Box<A>, x: A): boolean {
    return __bynkEq(self.value, x);
  },
  apply<A>(self: Box<A>, n: number): number {
    return 0;
  },
};

export function hasThree(n: number): boolean {
  const b = { value: 3 };
  return Box.has(b, n);
}

export function inc(n: number): number {
  return n + 1;
}

export function boxedFnApplied(f: (a0: number) => number): number {
  const b = { value: f };
  return Box.apply(b, 1);
}
