//! #855 anti-drift, Part 7 item 3 half B.
//!
//! `bynk_check::wire::WireModel` is the IR both the emitter's codec
//! generation (`bynk-emit`) and the editor's wire-contract peek (`bynk-ide`)
//! render from. Phase 2 proved the emitter is byte-identical to its
//! pre-extraction self (the whole `cargo test -p bynkc --test e2e` corpus,
//! unchanged); this file is the complementary check the plan calls for: that
//! the IR's own *claims* about a boundary type's [`bynk_check::wire::Revalidation`]
//! are actually true of the **committed** generated bytes, not merely
//! internally consistent with themselves.
//!
//! This is deliberately **not** a re-run of the compiler — `e2e.rs` already
//! owns that comparison, byte-for-byte, for every fixture. This file reads
//! the fixture's `.bynk` source directly to build a `WireModel` (the same
//! functions the emitter and the peek call), and separately reads the
//! fixture's already-committed `expected/**/*.ts` off disk, and asserts the
//! second is honest about what the first claims. If a future change makes
//! `wire.rs` and the emitter's rendering of it disagree without changing the
//! byte-identity of *this one* fixture (e.g. a refactor that reorders
//! `WireScalar::predicates` at derivation time but not at render time, or
//! vice versa), this is the test that would catch it — `e2e.rs`'s
//! byte-for-byte comparison would not notice a divergence between the IR and
//! its own doc comments, only between the emitter and its own golden file.
//!
//! Fixture: `tests/fixtures/positive/989_wire_shape_refined_revalidation`.
//! `wire.auth` owns a transparent refined type with two predicates in a
//! specific declaration order (`ClientId`), an opaque type (`AuthId`), and a
//! plain sum (`LoginError`); `wire.gateway` consumes `wire.auth` and calls
//! `login`, so its own `handlers.ts` generates the *consumer*-side codecs for
//! all three.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use bynk_check::wire::{self, Provenance, Revalidation, WireBody};
use bynk_syntax::ast::{CommonsItem, SourceUnit, TypeDecl};

fn fixture_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/positive/989_wire_shape_refined_revalidation")
}

fn read(path: &Path) -> String {
    std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("could not read {}: {e}", path.display()))
}

/// Parse a `context` source into its declared type table — the same shape
/// `bynk-check`'s own `wire.rs`/`contract.rs` test modules build by hand.
fn types_of(src: &str) -> HashMap<String, Arc<TypeDecl>> {
    let tokens = bynk_syntax::lexer::tokenize(src).expect("lex");
    let unit = bynk_syntax::parser::parse_unit(&tokens, src).expect("parse");
    let SourceUnit::Context(ctx) = unit else {
        panic!("expected a context unit");
    };
    let mut types = HashMap::new();
    for item in &ctx.items {
        if let CommonsItem::Type(t) = item {
            types.insert(t.name.name.clone(), Arc::new(t.clone()));
        }
    }
    types
}

/// Slice out one `export function <fn_name>(...) { ... }` block from an
/// emitted file — from its declaration to the next top-level `export `, or
/// end of file. Emitted functions are separated by a blank line and every
/// top-level declaration in these files starts with `export `, so this is a
/// reliable boundary without a full TS parse.
fn extract_fn<'a>(text: &'a str, fn_name: &str) -> &'a str {
    let marker = format!("function {fn_name}(");
    let start = text
        .find(&marker)
        .unwrap_or_else(|| panic!("`{marker}` not found in:\n{text}"));
    let rest = &text[start..];
    let end = rest[1..]
        .find("\nexport ")
        .map(|i| i + 1)
        .unwrap_or(rest.len());
    &rest[..end]
}

/// The known, literal condition-snippet each `PredKind` this fixture uses
/// renders as (the deserialiser's `json`-scoped inline check) — grounded in
/// the committed bytes read below, not a re-derivation of the emitter's full
/// `pred_condition_and_message`. Only covers the two predicates this fixture
/// actually declares; extend if the fixture grows more.
fn condition_snippet(p: &bynk_syntax::ast::PredKind) -> String {
    use bynk_syntax::ast::PredKind;
    match p {
        PredKind::NonEmpty => "json.length > 0".to_string(),
        PredKind::MaxLength(n) => format!("json.length <= {n}"),
        other => panic!(
            "wire_shape_drift.rs's condition_snippet has no mapping for {other:?} — extend it or simplify the fixture"
        ),
    }
}

#[test]
fn client_id_inline_revalidation_matches_the_committed_consumer_codec() {
    let root = fixture_root();
    let auth_src = read(&root.join("src/wire/auth.bynk"));
    let types = types_of(&auth_src);

    // The IR's claim: consumed + transparent ⇒ Inline, predicates carried in
    // declaration order (NonEmpty, then MaxLength(20) — the reverse of
    // contract.rs's sorted canonical order, deliberately).
    let consumed = Provenance::Consumed {
        owner_unit: "wire.auth".to_string(),
    };
    let wt = wire::wire_type("ClientId", &types["ClientId"], &types, consumed)
        .expect("ClientId is a scalar wire type");
    let WireBody::Scalar(scalar) = &wt.body else {
        panic!("expected a scalar body, got {:?}", wt.body);
    };
    assert_eq!(scalar.revalidation, Revalidation::Inline);
    assert_eq!(scalar.predicates.len(), 2, "{:?}", scalar.predicates);

    // The committed bytes: the consumer (`wire.gateway`) regenerates its own
    // `deserialise_ClientId`, since a `workers` build never imports a
    // consumed type's codec as a value.
    let gateway_ts = read(&root.join("expected/workers/wire-gateway/handlers.ts"));
    let body = extract_fn(&gateway_ts, "deserialise_ClientId");

    // One `if (!(` per declared predicate.
    let if_not_count = body.matches("if (!(").count();
    assert_eq!(
        if_not_count,
        scalar.predicates.len(),
        "expected one `if (!(` per predicate in deserialise_ClientId:\n{body}"
    );

    // In declaration order: each predicate's known condition snippet appears,
    // and at a strictly increasing byte offset.
    let mut last_pos = 0usize;
    for pred in &scalar.predicates {
        let snippet = condition_snippet(pred);
        let pos = body[last_pos..].find(snippet.as_str()).unwrap_or_else(|| {
            panic!("predicate {pred:?}'s condition `{snippet}` not found (in order) in:\n{body}")
        }) + last_pos;
        last_pos = pos + snippet.len();
    }

    // The honest counter-fact: `StructuralOnly`/`ViaConstructor`'s marker is
    // absent — this really is the inline-predicate path, not a mislabeled
    // structural cast.
    assert!(
        !body.contains(".of === \"function\""),
        "Inline revalidation must not also carry the ViaConstructor `.of` probe:\n{body}"
    );
}

#[test]
fn client_id_via_constructor_revalidation_matches_the_committed_owner_codec() {
    let root = fixture_root();
    let auth_src = read(&root.join("src/wire/auth.bynk"));
    let types = types_of(&auth_src);

    let wt = wire::wire_type("ClientId", &types["ClientId"], &types, Provenance::Owned)
        .expect("ClientId is a scalar wire type");
    let WireBody::Scalar(scalar) = &wt.body else {
        panic!("expected a scalar body, got {:?}", wt.body);
    };
    assert_eq!(scalar.revalidation, Revalidation::ViaConstructor);

    let auth_ts = read(&root.join("expected/workers/wire-auth/handlers.ts"));
    let body = extract_fn(&auth_ts, "deserialise_ClientId");
    assert!(
        body.contains(".of === \"function\""),
        "ViaConstructor revalidation must probe the owner's own `.of`:\n{body}"
    );
}

#[test]
fn auth_id_structural_only_revalidation_matches_the_committed_consumer_codec() {
    let root = fixture_root();
    let auth_src = read(&root.join("src/wire/auth.bynk"));
    let types = types_of(&auth_src);

    let consumed = Provenance::Consumed {
        owner_unit: "wire.auth".to_string(),
    };
    let wt = wire::wire_type("AuthId", &types["AuthId"], &types, consumed)
        .expect("AuthId is a scalar wire type");
    let WireBody::Scalar(scalar) = &wt.body else {
        panic!("expected a scalar body, got {:?}", wt.body);
    };
    assert!(scalar.opaque, "AuthId is declared opaque");
    assert_eq!(scalar.revalidation, Revalidation::StructuralOnly);

    let gateway_ts = read(&root.join("expected/workers/wire-gateway/handlers.ts"));
    let body = extract_fn(&gateway_ts, "deserialise_AuthId");

    // Neither the Inline predicate-check pattern nor the ViaConstructor `.of`
    // probe appears — the predicate really is the owner's secret here, cast
    // structurally after the base `typeof` check.
    assert!(
        !body.contains("if (!("),
        "StructuralOnly must carry no predicate check:\n{body}"
    );
    assert!(
        !body.contains(".of === \"function\""),
        "StructuralOnly must not probe a constructor it cannot see:\n{body}"
    );
}

#[test]
fn login_error_sum_codec_matches_the_wire_discriminant_the_ir_declares() {
    let root = fixture_root();
    let auth_src = read(&root.join("src/wire/auth.bynk"));
    let types = types_of(&auth_src);

    let wt = wire::wire_type(
        "LoginError",
        &types["LoginError"],
        &types,
        Provenance::Owned,
    )
    .expect("LoginError is a sum wire type");
    let WireBody::Sum(sum) = &wt.body else {
        panic!("expected a sum body, got {:?}", wt.body);
    };
    assert_eq!(sum.variants.len(), 1);
    assert_eq!(sum.variants[0].name, "Invalid");

    // The consumer (`wire.gateway`) regenerates its own `LoginError` codec
    // too — check that copy, so this exercises the same consumer-side
    // generation path the predicate assertions above do.
    let gateway_ts = read(&root.join("expected/workers/wire-gateway/handlers.ts"));
    let deser = extract_fn(&gateway_ts, "deserialise_LoginError");
    let ser = extract_fn(&gateway_ts, "serialise_LoginError");

    let wire_needle = format!("obj[\"{}\"]", sum.wire_discriminant);
    assert!(
        deser.contains(&wire_needle),
        "deserialise_LoginError should switch on `{wire_needle}` (the IR's wire_discriminant):\n{deser}"
    );
    let memory_needle = format!("value.{}", sum.memory_discriminant);
    assert!(
        ser.contains(&memory_needle),
        "serialise_LoginError should switch on `{memory_needle}` (the IR's memory_discriminant):\n{ser}"
    );
}
