// Generated by bynkc — do not edit by hand.
// test target: demo.vault

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, __bynkEq } from "../runtime.js";
import * as __ns_demo_vault from "./../demo/vault.js";

class ExpectationError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number, detail: string) {
    super(`${detail}\n  at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkExpectFailure(location: string, start: number, end: number, detail: string) {
  return new ExpectationError(location, start, end, detail);
}
function __bynkExpect(cond: boolean, location: string, start: number, end: number, detail: string): void {
  if (!cond) { throw __bynkExpectFailure(location, start, end, detail); }
}
function __bynkShow(v: unknown): string {
  try { return typeof v === "bigint" ? String(v) : (JSON.stringify(v) ?? String(v)); } catch { return String(v); }
}

class __Stub_Vault {
  __seq_1 = 0;
  __case: string | undefined;
  constructor(c?: string) {
    this.__case = c;
  }
  __applies(op: string): boolean {
    if (op === "open") return this.__case === "a call that returns does not fault" || this.__case === "a fails stub faults the call" || this.__case === "a sequence serves a fault, then a value" || this.__case === "an unclaimed fault fails the case";
    return true;
  }
  async open(): globalThis.Promise<number> {
    if (this.__case === "a fails stub faults the call") {
      throw new globalThis.Error("bynk: injected capability fault (stubs … fails)");
    }
    if (this.__case === "a sequence serves a fault, then a value") {
      const __k = this.__seq_1;
      if (this.__seq_1 < 1) this.__seq_1++;
      switch (__k) {
        case 0: {
          throw new globalThis.Error("bynk: injected capability fault (stubs … fails)");
        }
        default: {
          return 41;
        }
      }
    }
    if (this.__case === "a call that returns does not fault") {
      return 1;
    }
    if (this.__case === "an unclaimed fault fails the case") {
      throw new globalThis.Error("bynk: injected capability fault (stubs … fails)");
    }
    throw new globalThis.Error("bynk: no stub clause matched for Vault.open");
  }
}

function __bynkOverlay(base: unknown, stub: object, cap: string): unknown {
  return new globalThis.Proxy(stub, {
    get(target, prop) {
      const t = target as Record<PropertyKey, unknown> & { __applies?: (op: string) => boolean };
      // An own property (the stub's state, or a wrapper the recording proxy
      // installed) always answers; a stubbed operation answers when it applies
      // to the running case.
      if (globalThis.Object.prototype.hasOwnProperty.call(t, prop)) return t[prop];
      if (prop in t && (t.__applies === undefined || typeof prop !== "string" || t.__applies(prop))) return t[prop];
      if (base !== undefined) {
        const v = (base as Record<PropertyKey, unknown>)[prop];
        return typeof v === "function" ? v.bind(base) : v;
      }
      return () => {
        throw new globalThis.Error(`bynk: ${cap}.${String(prop)} is not stubbed, and the capability has no provider in this test`);
      };
    },
  });
}

function __makeTestDeps(__case?: string) {
  return { Vault: __bynkOverlay(new __ns_demo_vault.RealVault(), new __Stub_Vault(__case), "Vault") as __ns_demo_vault.Vault };
}

// case tier: unit
async function test_a_fails_stub_faults_the_call() {
  try {
    const deps = __makeTestDeps("a fails stub faults the call");
    const { box } = __ns_demo_vault;
    if (!((await (async () => { try { await (box.call(deps)); return false; } catch (__e) { if (__e instanceof ExpectationError) { throw __e; } return true; } })()))) { throw __bynkExpectFailure("tests/vault.test.bynk:7:12", 259, 276, "expect box.call() faults\n  the call returned without faulting"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_sequence_serves_a_fault__then_a_value() {
  try {
    const deps = __makeTestDeps("a sequence serves a fault, then a value");
    const { box } = __ns_demo_vault;
    if (!((await (async () => { try { await (box.call(deps)); return false; } catch (__e) { if (__e instanceof ExpectationError) { throw __e; } return true; } })()))) { throw __bynkExpectFailure("tests/vault.test.bynk:12:12", 391, 408, "expect box.call() faults\n  the call returned without faulting"); }
    const r = await box.call(deps);
    if (!(__bynkEq(r, 42))) { throw __bynkExpectFailure("tests/vault.test.bynk:14:12", 444, 451, "expect r == 42\n  expected: r == 42\n  actual:   " + __bynkShow((r)) + " == " + __bynkShow((42))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_call_that_returns_does_not_fault() {
  try {
    const deps = __makeTestDeps("a call that returns does not fault");
    const { box } = __ns_demo_vault;
    if (!((await (async () => { try { await (box.call(deps)); return false; } catch (__e) { if (__e instanceof ExpectationError) { throw __e; } return true; } })()))) { throw __bynkExpectFailure("tests/vault.test.bynk:19:12", 546, 563, "expect box.call() faults\n  the call returned without faulting"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_an_unclaimed_fault_fails_the_case() {
  try {
    const deps = __makeTestDeps("an unclaimed fault fails the case");
    const { box } = __ns_demo_vault;
    const r = await box.call(deps);
    if (!(true)) { throw __bynkExpectFailure("tests/vault.test.bynk:25:12", 677, 681, "expect true"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_faults_is_an_ordinary_name_elsewhere() {
  try {
    const deps = __makeTestDeps();
    const { box } = __ns_demo_vault;
    const faults = 2;
    if (!(faults === 2)) { throw __bynkExpectFailure("tests/vault.test.bynk:30:12", 765, 776, "expect faults == 2\n  expected: faults == 2\n  actual:   " + __bynkShow((faults)) + " == " + __bynkShow((2))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run(only?: string) {
  const results = [];
  const want = (n: string): boolean => only === undefined || only === n;
  if (want("a fails stub faults the call")) results.push({ name: "a fails stub faults the call", ...(await test_a_fails_stub_faults_the_call()) });
  if (want("a sequence serves a fault, then a value")) results.push({ name: "a sequence serves a fault, then a value", ...(await test_a_sequence_serves_a_fault__then_a_value()) });
  if (want("a call that returns does not fault")) results.push({ name: "a call that returns does not fault", ...(await test_a_call_that_returns_does_not_fault()) });
  if (want("an unclaimed fault fails the case")) results.push({ name: "an unclaimed fault fails the case", ...(await test_an_unclaimed_fault_fails_the_case()) });
  if (want("faults is an ordinary name elsewhere")) results.push({ name: "faults is an ordinary name elsewhere", ...(await test_faults_is_an_ordinary_name_elsewhere()) });
  return results;
}
