// Generated by bynkc — do not edit by hand.
// context room

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type __DurableObjectState, type __DurableObjectNamespace, __StateRegistry, __makeAgent, __rehydrationViolation, type __JsonValue, type __BoundaryError } from "./runtime.js";

import { positive } from "./shared.js";

export interface CounterState {
  readonly hits: number;
}

const __CounterRegistry = new __StateRegistry();
function __zeroOfCounterState(): CounterState { return { hits: 0 }; }

function __rehydrateCounterState(s: CounterState, stored: CounterState): void {
  if (globalThis.Object.prototype.hasOwnProperty.call(stored, "hits")) { const __r = ((__v) => typeof __v !== "number" ? Err({ kind: "StructuralMismatch", path: "hits", expected: "safe integer", actual: typeof __v } as __BoundaryError) : globalThis.Number.isSafeInteger(__v) ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "hits", expected: "safe integer", actual: String(__v) } as __BoundaryError))((s.hits as unknown as __JsonValue)); if (__r.tag === "Err") throw __rehydrationViolation("Counter", __r.error); (s as { -readonly [K in keyof typeof s]: (typeof s)[K] }).hits = __r.value as unknown as (typeof s)["hits"]; }
}

function __encodeCounterState(s: CounterState): globalThis.Record<string, unknown> {
  return { ...s, hits: ((v: number) => { if (!globalThis.Number.isSafeInteger(v)) throw new globalThis.Error("Int outside the safe-integer range at boundary"); return v as __JsonValue; })(s.hits) };
}

export class Counter {
  state: __DurableObjectState;
  constructor(state: __DurableObjectState) {
    this.state = state;
  }

  private async loadState(): globalThis.Promise<CounterState> {
    const stored = await this.state.storage.get<CounterState>("state");
    if (stored === undefined) return __zeroOfCounterState();
    const __merged = { ...__zeroOfCounterState(), ...stored };
    __rehydrateCounterState(__merged, stored);
    return __merged;
  }

  private async commitState(s: CounterState): globalThis.Promise<void> {
    await this.state.storage.put("state", __encodeCounterState(s));
  }

  async bump(n: number, deps: {}): globalThis.Promise<void> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = Some(n);
      if (__r0.tag === "Some") {
        const x = __r0.value;
        if ((() => {
    if (x > 0) {
      __state.hits = x;
      return true;
    } else {
      return false;
    }
  })()) {
          return undefined;
        }
      }
      return undefined;
    })();
    await this.commitState(__state);
    return __result;
  }

  async note(n: number, deps: {}): globalThis.Promise<void> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = Some(n);
      if (__r0.tag === "Some") {
        const x = __r0.value;
        if ((() => {
    if (positive(x)) {
      __state.hits = x;
      return false;
    } else {
      return false;
    }
  })()) {
          return undefined;
        }
      }
      return undefined;
    })();
    await this.commitState(__state);
    return __result;
  }

  async read(deps: {}): globalThis.Promise<number> {
    const __state = await this.loadState();
    return __state.hits;
  }

}

export function __makeCounter(key: string, env?: { COUNTER?: __DurableObjectNamespace }): Counter {
  return __makeAgent(__CounterRegistry, env?.COUNTER, key, (state) => new Counter(state));
}

export const bump = {
  async call(id: string, n: number, deps: {}): globalThis.Promise<void> {
    return __makeCounter(id).bump(n, deps);
  },
};

export const note = {
  async call(id: string, n: number, deps: {}): globalThis.Promise<void> {
    return __makeCounter(id).note(n, deps);
  },
};

export const read = {
  async call(id: string, deps: {}): globalThis.Promise<number> {
    return __makeCounter(id).read(deps);
  },
};

export function __resetAgents(): void {
  __CounterRegistry.reset();
}

export interface __RoomDeps {
}

export function __makeSurface(deps: __RoomDeps) {
  return {
    async bump(id: string, n: number): globalThis.Promise<void> {
      return bump.call(id, n, deps);
    },
    async note(id: string, n: number): globalThis.Promise<void> {
      return note.call(id, n, deps);
    },
    async read(id: string): globalThis.Promise<number> {
      return read.call(id, deps);
    },
  };
}
