// Generated by bynkc — do not edit by hand.
// context catalog

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type __JsonValue, type __BoundaryError, type __ServiceBinding, __callService, __boundaryError } from "../../runtime.js";

export interface Order {
  readonly id: string;
  readonly total: number;
  readonly tags: ReadonlyMap<string, number>;
}

export const Order = {
};

export const orders = {
  async call(ids: readonly string[], deps: {}): globalThis.Promise<Result<readonly Order[], void>> {
    const none: ReadonlyMap<string, number> = new globalThis.Map<string, number>();
    return Ok([{ id: "a", total: 1, tags: none }, { id: "b", total: 2, tags: none }]);
  },
};

export function __serialise_Order(value: Order): __JsonValue {
  return {
    id: value.id as __JsonValue,
    total: ((v: number) => { if (!globalThis.Number.isSafeInteger(v)) throw new globalThis.Error("Int outside the safe-integer range at boundary"); return v as __JsonValue; })(value.total),
    tags: __serialise_Map_String_Int(value.tags),
  };
}

export function __deserialise_Order(json: __JsonValue, path: string = "$"): Result<Order, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  if (typeof obj["id"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.id`, expected: "string", actual: typeof obj["id"] });
  }
  const __id = obj["id"];
  if (typeof obj["total"] !== "number") {
    return Err({ kind: "StructuralMismatch", path: `${path}.total`, expected: "number", actual: typeof obj["total"] });
  }
  if (!globalThis.Number.isSafeInteger(obj["total"])) {
    return Err({ kind: "StructuralMismatch", path: `${path}.total`, expected: "safe integer", actual: String(obj["total"]) });
  }
  const __total = obj["total"];
  const __r_tags = __deserialise_Map_String_Int(obj["tags"], `${path}.tags`);
  if (__r_tags.tag === "Err") return __r_tags;
  const __tags = __r_tags.value;
  return Ok({ id: __id, total: __total, tags: __tags } as Order);
}


export function __serialise_List_String(value: readonly string[]): __JsonValue {
  return value.map((v) => v as __JsonValue);
}

export function __deserialise_List_String(json: __JsonValue, path: string = "$"): Result<readonly string[], __BoundaryError> {
  if (!globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "array", actual: typeof json });
  }
  const out: string[] = [];
  for (let i = 0; i < json.length; i++) {
  const item = json[i];
  if (typeof item !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}[${i}]`, expected: "string", actual: typeof item });
  }
  const __el = item;
  out.push(__el as string);
  }
  return Ok(out);
}

export function __serialise_Result_List_Order_Unit(value: Result<readonly Order[], void>): __JsonValue {
  if (value.tag === "Ok") return { kind: "Ok", value: __serialise_List_Order(value.value) };
  return { kind: "Err", error: null };
}

export function __deserialise_Result_List_Order_Unit(json: __JsonValue, path: string = "$"): Result<Result<readonly Order[], void>, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  if (obj["kind"] === "Ok") {
  const __r_v = __deserialise_List_Order(obj["value"], `${path}.value`);
  if (__r_v.tag === "Err") return __r_v;
  const __v = __r_v.value;
    return Ok(Ok(__v) as Result<readonly Order[], void>);
  } else if (obj["kind"] === "Err") {
  const __e = undefined;
    return Ok(Err(__e) as Result<readonly Order[], void>);
  }
  return Err({ kind: "StructuralMismatch", path, expected: "Ok | Err", actual: String(obj["kind"]) });
}

export function __serialise_List_Order(value: readonly Order[]): __JsonValue {
  return value.map((v) => __serialise_Order(v));
}

export function __deserialise_List_Order(json: __JsonValue, path: string = "$"): Result<readonly Order[], __BoundaryError> {
  if (!globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "array", actual: typeof json });
  }
  const out: Order[] = [];
  for (let i = 0; i < json.length; i++) {
  const item = json[i];
  const __r_el = __deserialise_Order(item, `${path}[${i}]`);
  if (__r_el.tag === "Err") return __r_el;
  const __el = __r_el.value;
  out.push(__el as Order);
  }
  return Ok(out);
}

export function __serialise_Map_String_Int(value: ReadonlyMap<string, number>): __JsonValue {
  const entries: __JsonValue[] = [];
  for (const [k, v] of value) {
    entries.push([k as __JsonValue, ((v: number) => { if (!globalThis.Number.isSafeInteger(v)) throw new globalThis.Error("Int outside the safe-integer range at boundary"); return v as __JsonValue; })(v)]);
  }
  return entries;
}

export function __deserialise_Map_String_Int(json: __JsonValue, path: string = "$"): Result<ReadonlyMap<string, number>, __BoundaryError> {
  if (!globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "array", actual: typeof json });
  }
  const out = new globalThis.Map<string, number>();
  for (let i = 0; i < json.length; i++) {
  const entry = json[i];
  if (!globalThis.Array.isArray(entry) || entry.length !== 2) {
    return Err({ kind: "StructuralMismatch", path: `${path}[${i}]`, expected: "[key, value] entry", actual: typeof entry });
  }
  const entryK = entry[0];
  const entryV = entry[1];
  if (typeof entryK !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}[${i}][0]`, expected: "string", actual: typeof entryK });
  }
  const __k = entryK;
  if (typeof entryV !== "number") {
    return Err({ kind: "StructuralMismatch", path: `${path}[${i}][1]`, expected: "number", actual: typeof entryV });
  }
  if (!globalThis.Number.isSafeInteger(entryV)) {
    return Err({ kind: "StructuralMismatch", path: `${path}[${i}][1]`, expected: "safe integer", actual: String(entryV) });
  }
  const __v = entryV;
  out.set(__k as string, __v as number);
  }
  return Ok(out);
}
