// Generated by bynkc — do not edit by hand.
// commons t.app

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

import { Run, first } from "./model.js";

/**
 * #1824: `t.app` declares its own `Repo` beside a `uses` of `t.core`, whose
 * `Repo` `t.model`'s `Run` names. The shadow is legal, and so is every use here:
 * `retag` moves a `t.core` `Repo` from one imported position (`first`'s result)
 * straight into another (`Run.repo`), and the rest touch only `Run.n` and the
 * local `Repo`. Neither `Repo` ever meets the other.
 */

export type Repo = number & { readonly __brand: "Repo" };

export const Repo = {
  of(value: number): Result<Repo, ValidationError> {
    if (!globalThis.Number.isSafeInteger(value)) {
      return Err({ field: "Repo", message: "must be a safe integer", value });
    }
    return Ok(value as Repo);
  },
};

export function retag(r: Run): Run {
  return { repo: first(r), n: r.n + 1 };
}

export function size(r: Run): number {
  return r.n;
}

export function mine(): Repo {
  return (7 as Repo);
}
