// Generated by bynkc — do not edit by hand.
// test target: demo.g

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";
import * as demo_g from "./../demo/g.js";
import * as demo_shapes from "./../demo/shapes.js";

class ExpectationError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number, detail: string) {
    super(`${detail}\n  at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkExpectFailure(location: string, start: number, end: number, detail: string) {
  return new ExpectationError(location, start, end, detail);
}
function __bynkExpect(cond: boolean, location: string, start: number, end: number, detail: string): void {
  if (!cond) { throw __bynkExpectFailure(location, start, end, detail); }
}
function __bynkShow(v: unknown): string {
  try { return typeof v === "bigint" ? String(v) : (JSON.stringify(v) ?? String(v)); } catch { return String(v); }
}

function makeTestDeps() {
  return {  };
}

// case tier: unit
async function test_a_case_that_never_mentions_a_generic_type() {
  try {
    const deps = {};
    const { Box, Plain, Tagged, boxed, one, swapped, tagged } = demo_g;
    type Box<A> = demo_g.Box<A>;
    type Plain = demo_g.Plain;
    type Tagged<T, U> = demo_g.Tagged<T, U>;
    const { Pair, pairOf } = demo_shapes;
    type Pair<A, B> = demo_shapes.Pair<A, B>;
    if (!(one() === 1)) { throw __bynkExpectFailure("tests/demo/g.bynk:4:10", 74, 84, "expect one() == 1\n  expected: one() == 1\n  actual:   " + __bynkShow((one())) + " == " + __bynkShow((1))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_generic_type_the_target_declares() {
  try {
    const deps = {};
    const { Box, Plain, Tagged, boxed, one, swapped, tagged } = demo_g;
    type Box<A> = demo_g.Box<A>;
    type Plain = demo_g.Plain;
    type Tagged<T, U> = demo_g.Tagged<T, U>;
    const { Pair, pairOf } = demo_shapes;
    type Pair<A, B> = demo_shapes.Pair<A, B>;
    if (!(boxed(3).value === 3)) { throw __bynkExpectFailure("tests/demo/g.bynk:8:10", 141, 160, "expect boxed(3).value == 3\n  expected: boxed(3).value == 3\n  actual:   " + __bynkShow((boxed(3).value)) + " == " + __bynkShow((3))); }
    if (!(tagged(4).body === 4)) { throw __bynkExpectFailure("tests/demo/g.bynk:9:10", 170, 189, "expect tagged(4).body == 4\n  expected: tagged(4).body == 4\n  actual:   " + __bynkShow((tagged(4).body)) + " == " + __bynkShow((4))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_generic_type_built_in_the_case_body() {
  try {
    const deps = {};
    const { Box, Plain, Tagged, boxed, one, swapped, tagged } = demo_g;
    type Box<A> = demo_g.Box<A>;
    type Plain = demo_g.Plain;
    type Tagged<T, U> = demo_g.Tagged<T, U>;
    const { Pair, pairOf } = demo_shapes;
    type Pair<A, B> = demo_shapes.Pair<A, B>;
    const b = { value: "x" };
    if (!(b.value === "x")) { throw __bynkExpectFailure("tests/demo/g.bynk:14:10", 278, 292, "expect b.value == \"x\"\n  expected: b.value == \"x\"\n  actual:   " + __bynkShow((b.value)) + " == " + __bynkShow(("x"))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_generic_type_reached_through_uses() {
  try {
    const deps = {};
    const { Box, Plain, Tagged, boxed, one, swapped, tagged } = demo_g;
    type Box<A> = demo_g.Box<A>;
    type Plain = demo_g.Plain;
    type Tagged<T, U> = demo_g.Tagged<T, U>;
    const { Pair, pairOf } = demo_shapes;
    type Pair<A, B> = demo_shapes.Pair<A, B>;
    const p = swapped(pairOf(7, "seven"));
    if (!(p.first === "seven")) { throw __bynkExpectFailure("tests/demo/g.bynk:19:10", 388, 406, "expect p.first == \"seven\"\n  expected: p.first == \"seven\"\n  actual:   " + __bynkShow((p.first)) + " == " + __bynkShow(("seven"))); }
    if (!(p.second === 7)) { throw __bynkExpectFailure("tests/demo/g.bynk:20:10", 416, 429, "expect p.second == 7\n  expected: p.second == 7\n  actual:   " + __bynkShow((p.second)) + " == " + __bynkShow((7))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run(only?: string) {
  const results = [];
  const want = (n: string): boolean => only === undefined || only === n;
  if (want("a case that never mentions a generic type")) results.push({ name: "a case that never mentions a generic type", ...(await test_a_case_that_never_mentions_a_generic_type()) });
  if (want("a generic type the target declares")) results.push({ name: "a generic type the target declares", ...(await test_a_generic_type_the_target_declares()) });
  if (want("a generic type built in the case body")) results.push({ name: "a generic type built in the case body", ...(await test_a_generic_type_built_in_the_case_body()) });
  if (want("a generic type reached through uses")) results.push({ name: "a generic type reached through uses", ...(await test_a_generic_type_reached_through_uses()) });
  return results;
}
