// Generated by bynkc — do not edit by hand.
// Worker entry point for context `jobs`.

import { Ok, Err, type Result, type __JsonValue, type __BoundaryError, __boundaryError } from "../../runtime.js";
import { compose, type Env } from "./compose.js";
import * as handlers from "./handlers.js";

export default {
  async fetch(request: globalThis.Request, env: Env): globalThis.Promise<globalThis.Response> {
    const url = new globalThis.URL(request.url);
    const path = url.pathname;
    const method = request.method;
    const surface = compose(env);
    try {
      if (path.startsWith("/_bynk/call/")) {
        const servicePath = path.slice("/_bynk/call/".length);
        switch (servicePath) {
          default:
            return new globalThis.Response("Not found", { status: 404 });
        }
      }

      return new globalThis.Response("Not Found", { status: 404 });
    } catch {
      return new globalThis.Response("Internal Server Error", { status: 500 });
    }
  },
  async queue(batch: { readonly queue: string; readonly messages: ReadonlyArray<{ readonly body: unknown; ack(): void; retry(): void }> }, env: Env): globalThis.Promise<void> {
    const surface = compose(env);
    switch (batch.queue) {
      case "high-priority": {
        for (const msg of batch.messages) {
          try {
            const __r = handlers.__deserialise_Job((msg.body as __JsonValue), "$");
            if (__r.tag === "Err") { globalThis.console.error("queue high-priority deserialise failed", __r.error); msg.retry(); continue; }
            const result = await surface.queue_highWorker_0(__r.value);
            if (result.tag === "Ack") msg.ack();
            else { globalThis.console.error("queue high-priority retry", result.reason); msg.retry(); }
          } catch (e) {
            globalThis.console.error("queue high-priority threw", e); msg.retry();
          }
        }
        return;
      }
      case "low-priority": {
        for (const msg of batch.messages) {
          try {
            const __r = handlers.__deserialise_Job((msg.body as __JsonValue), "$");
            if (__r.tag === "Err") { globalThis.console.error("queue low-priority deserialise failed", __r.error); msg.retry(); continue; }
            const result = await surface.queue_lowWorker_0(__r.value);
            if (result.tag === "Ack") msg.ack();
            else { globalThis.console.error("queue low-priority retry", result.reason); msg.retry(); }
          } catch (e) {
            globalThis.console.error("queue low-priority threw", e); msg.retry();
          }
        }
        return;
      }
      default:
        return;
    }
  },
};
