// Generated by bynkc — do not edit by hand.
// context shop.gate

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type __JsonValue, type __BoundaryError, type __ServiceBinding, __callService, __boundaryError } from "../../runtime.js";

import type * as shop_tokens from "../shop-tokens/handlers.js";

/**
 * Gate context. Admits a request by minting a grant through the tokens context.
 * It consumes `shop.tokens` and calls `issue`, so under `--target workers` it
 * generates its **own** codecs for the callee-owned boundary types
 * (`Token`, `Score`, `Grant`, `TokenError`) rather than importing the callee's
 * module as a value.
 */

export type GateError =
    { readonly tag: "Rejected" };

export const GateError = {
  Rejected: { tag: "Rejected" } as GateError,
};

export const enter = {
  /**
   * Admit a request. Maps every token failure onto the gate's own error, so the
   * callee's `TokenError` never appears in this context's own signature — it is
   * reached only inside the generated `deserialise_Result_Grant_TokenError`.
   */
  async call(seed: string, deps: { env: { SHOP_TOKENS: __ServiceBinding } }): globalThis.Promise<Result<void, GateError>> {
    const g = await __callService(deps.env.SHOP_TOKENS, "issue", seed as __JsonValue, __deserialise_Result_Grant_TokenError, "shop.gate", "096e27188255617a");
    switch (g.tag) {
      case "Ok": {
        return Ok(undefined);
      }
      case "Err": {
        return Err(GateError.Rejected);
      }
    }
    throw new globalThis.Error("non-exhaustive match");
  },
};

export function __serialise_GateError(value: GateError): __JsonValue {
  switch (value.tag) {
    case "Rejected":
      return { kind: "Rejected" };
  }
}

export function __deserialise_GateError(json: __JsonValue, path: string = "$"): Result<GateError, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  const kind = obj["kind"];
  switch (kind) {
    case "Rejected":
      return Ok({ tag: "Rejected" } as GateError);
    default:
      return Err({ kind: "StructuralMismatch", path, expected: "sum variant kind", actual: String(kind) });
  }
}


export function __serialise_Result_Unit_GateError(value: Result<void, GateError>): __JsonValue {
  if (value.tag === "Ok") return { kind: "Ok", value: null };
  return { kind: "Err", error: __serialise_GateError(value.error) };
}

export function __deserialise_Result_Unit_GateError(json: __JsonValue, path: string = "$"): Result<Result<void, GateError>, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  if (obj["kind"] === "Ok") {
  const __v = undefined;
    return Ok(Ok(__v) as Result<void, GateError>);
  } else if (obj["kind"] === "Err") {
  const __r_e = __deserialise_GateError(obj["error"], `${path}.error`);
  if (__r_e.tag === "Err") return __r_e;
  const __e = __r_e.value;
    return Ok(Err(__e) as Result<void, GateError>);
  }
  return Err({ kind: "StructuralMismatch", path, expected: "Ok | Err", actual: String(obj["kind"]) });
}

export function __serialise_Grant(value: shop_tokens.Grant): __JsonValue {
  return {
    token: __serialise_Token(value.token),
    score: __serialise_Score(value.score),
  };
}

export function __deserialise_Grant(json: __JsonValue, path: string = "$"): Result<shop_tokens.Grant, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  const __r_token = __deserialise_Token(obj["token"], `${path}.token`);
  if (__r_token.tag === "Err") return __r_token;
  const __token = __r_token.value;
  const __r_score = __deserialise_Score(obj["score"], `${path}.score`);
  if (__r_score.tag === "Err") return __r_score;
  const __score = __r_score.value;
  return Ok({ token: __token, score: __score } as shop_tokens.Grant);
}

export function __serialise_Score(value: shop_tokens.Score): __JsonValue {
  return value as unknown as number;
}

export function __deserialise_Score(json: __JsonValue, path: string = "$"): Result<shop_tokens.Score, __BoundaryError> {
  if (typeof json !== "number") {
    return Err({ kind: "StructuralMismatch", path, expected: "number", actual: typeof json });
  }
  if (!globalThis.Number.isSafeInteger(json)) {
    return Err({ kind: "RefinementViolation", path, violation: { field: "Score", message: "must be a safe integer", value: json } });
  }
  if (!(json >= 0 && json <= 100)) {
    return Err({ kind: "RefinementViolation", path, violation: { field: "Score", message: "must be in range [0, 100]", value: json } });
  }
  return Ok(json as unknown as shop_tokens.Score);
}

export function __serialise_Token(value: shop_tokens.Token): __JsonValue {
  return value as unknown as string;
}

export function __deserialise_Token(json: __JsonValue, path: string = "$"): Result<shop_tokens.Token, __BoundaryError> {
  if (typeof json !== "string") {
    return Err({ kind: "StructuralMismatch", path, expected: "string", actual: typeof json });
  }
  return Ok(json as unknown as shop_tokens.Token);
}

export function __serialise_TokenError(value: shop_tokens.TokenError): __JsonValue {
  switch (value.tag) {
    case "Denied":
      return { kind: "Denied" };
    case "Expired":
      return { kind: "Expired" };
  }
}

export function __deserialise_TokenError(json: __JsonValue, path: string = "$"): Result<shop_tokens.TokenError, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  const kind = obj["kind"];
  switch (kind) {
    case "Denied":
      return Ok({ tag: "Denied" } as shop_tokens.TokenError);
    case "Expired":
      return Ok({ tag: "Expired" } as shop_tokens.TokenError);
    default:
      return Err({ kind: "StructuralMismatch", path, expected: "sum variant kind", actual: String(kind) });
  }
}


export function __serialise_Result_Grant_TokenError(value: Result<shop_tokens.Grant, shop_tokens.TokenError>): __JsonValue {
  if (value.tag === "Ok") return { kind: "Ok", value: __serialise_Grant(value.value) };
  return { kind: "Err", error: __serialise_TokenError(value.error) };
}

export function __deserialise_Result_Grant_TokenError(json: __JsonValue, path: string = "$"): Result<Result<shop_tokens.Grant, shop_tokens.TokenError>, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  if (obj["kind"] === "Ok") {
  const __r_v = __deserialise_Grant(obj["value"], `${path}.value`);
  if (__r_v.tag === "Err") return __r_v;
  const __v = __r_v.value;
    return Ok(Ok(__v) as Result<shop_tokens.Grant, shop_tokens.TokenError>);
  } else if (obj["kind"] === "Err") {
  const __r_e = __deserialise_TokenError(obj["error"], `${path}.error`);
  if (__r_e.tag === "Err") return __r_e;
  const __e = __r_e.value;
    return Ok(Err(__e) as Result<shop_tokens.Grant, shop_tokens.TokenError>);
  }
  return Err({ kind: "StructuralMismatch", path, expected: "Ok | Err", actual: String(obj["kind"]) });
}

