// Generated by bynkc — do not edit by hand.
// commons demo.or_patterns

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export type BookingState =
    { readonly tag: "Held"; readonly guest: string; readonly room: number; readonly days: number; readonly rsv: number; readonly note: string }
  | { readonly tag: "Confirmed"; readonly who: string; readonly room: number; readonly days: number; readonly rsv: number; readonly note: string }
  | { readonly tag: "Cancelled"; readonly reason: string };

export const BookingState = {
  Held: (guest: string, room: number, days: number, rsv: number, note: string): BookingState => ({ tag: "Held", guest, room, days, rsv, note }),
  Confirmed: (who: string, room: number, days: number, rsv: number, note: string): BookingState => ({ tag: "Confirmed", who, room, days, rsv, note }),
  Cancelled: (reason: string): BookingState => ({ tag: "Cancelled", reason }),
};

export type Command =
    { readonly tag: "Login"; readonly user: string; readonly pass: string }
  | { readonly tag: "Register"; readonly user: string; readonly pass: string }
  | { readonly tag: "Logout" };

export const Command = {
  Login: (user: string, pass: string): Command => ({ tag: "Login", user, pass }),
  Register: (user: string, pass: string): Command => ({ tag: "Register", user, pass }),
  Logout: { tag: "Logout" } as Command,
};

export type Status =
    { readonly tag: "Pending" }
  | { readonly tag: "Active" }
  | { readonly tag: "Done" };

export const Status = {
  Pending: { tag: "Pending" } as Status,
  Active: { tag: "Active" } as Status,
  Done: { tag: "Done" } as Status,
};

export function roomOf(s: BookingState): number {
  if ((s.tag === "Held" || s.tag === "Confirmed")) {
    let r, rsv;
    if (s.tag === "Held") {
      r = s.room;
      rsv = s.rsv;
    } else {
      r = s.room;
      rsv = s.rsv;
    }
    if (rsv > 0) {
      return r + rsv;
    }
  }
  if ((s.tag === "Held" || s.tag === "Confirmed")) {
    let r;
    if (s.tag === "Held") {
      r = s.room;
    } else {
      r = s.room;
    }
    return r;
  }
  if (s.tag === "Cancelled") {
    return 0;
  }
  throw new Error("non-exhaustive match");
}

export function small(n: number): string {
  switch (n) {
    case 1:
    case 2:
    case 3: {
      return "small";
    }
    case 4:
    case 5:
    case 6: {
      return "medium";
    }
    default: {
      return "large";
    }
  }
  throw new Error("non-exhaustive match");
}

export function route(c: Command): string {
  if ((c.tag === "Login" || c.tag === "Register")) {
    let u;
    if (c.tag === "Login") {
      u = c.user;
    } else {
      u = c.user;
    }
    if (u === "admin") {
      return "admin path";
    }
  }
  if ((c.tag === "Login" || c.tag === "Register")) {
    return "user path";
  }
  if (c.tag === "Logout") {
    return "bye";
  }
  throw new Error("non-exhaustive match");
}

export function smallOption(o: Option<number>): string {
  if (o.tag === "Some" && (o.value === 1 || o.value === 2)) {
    return "small";
  }
  if (o.tag === "Some") {
    return "other";
  }
  if (o.tag === "None") {
    return "none";
  }
  throw new Error("non-exhaustive match");
}

export function describe(s: BookingState): string {
  if ((s.tag === "Held" || s.tag === "Confirmed")) {
    let r, rsv;
    if (s.tag === "Held") {
      r = s.room;
      rsv = s.rsv;
    } else {
      r = s.room;
      rsv = s.rsv;
    }
    return `room ${String(r)} rsv ${String(rsv)}`;
  } else {
    return "cancelled";
  }
}

export function isActive(s: BookingState): boolean {
  return (s.tag === "Held" || s.tag === "Confirmed");
}

export function classify(s: Status): string {
  switch (s.tag) {
    case "Done": {
      return "done";
    }
    default: {
      return "not done";
    }
  }
  throw new Error("non-exhaustive match");
}

