// Generated by karnc — do not edit by hand.
// commons test

export function compute(a: number, b: number): number {
  const sum = a + b;
  const product = a * b;
  const combined = sum + product;
  return combined;
}

