// Generated by bynkc — do not edit by hand.
// context probe

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type __DurableObjectState, type __DurableObjectNamespace, __StateRegistry, __makeAgent, __rehydrationViolation, type __JsonValue, type __BoundaryError } from "./runtime.js";

export interface Reservation {
  readonly id: string;
  readonly qty: number;
}

export const Reservation = {
};

export interface InventoryState {
  readonly reservations: globalThis.Record<string, Reservation>;
}

const __InventoryRegistry = new __StateRegistry();
function __zeroOfInventoryState(): InventoryState { return { reservations: {} }; }

function __rehydrateInventoryState(s: InventoryState, stored: InventoryState): void {
  if (globalThis.Object.prototype.hasOwnProperty.call(stored, "reservations")) for (const __k of globalThis.Object.keys(s.reservations)) { const __r = __deserialise_Reservation((s.reservations[__k] as unknown as __JsonValue), "reservations"); if (__r.tag === "Err") throw __rehydrationViolation("Inventory", __r.error); s.reservations[__k] = __r.value as unknown as (typeof s.reservations)[string]; }
  for (const __k of globalThis.Object.keys(s.reservations)) { const __r = ((__v) => typeof __v === "string" ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "reservations", expected: "string", actual: typeof __v } as __BoundaryError))((__k as unknown as __JsonValue)); if (__r.tag === "Err") throw __rehydrationViolation("Inventory", __r.error); }
}

function __encodeInventoryState(s: InventoryState): globalThis.Record<string, unknown> {
  return { ...s, reservations: globalThis.Object.fromEntries(globalThis.Object.entries(s.reservations).map(([__k, __v]) => [__k, __serialise_Reservation(__v)])) };
}

export class Inventory {
  state: __DurableObjectState;
  constructor(state: __DurableObjectState) {
    this.state = state;
  }

  private async loadState(): globalThis.Promise<InventoryState> {
    const stored = await this.state.storage.get<InventoryState>("state");
    if (stored === undefined) return __zeroOfInventoryState();
    const __merged = { ...__zeroOfInventoryState(), ...stored };
    __rehydrateInventoryState(__merged, stored);
    return __merged;
  }

  private async commitState(s: InventoryState): globalThis.Promise<void> {
    await this.state.storage.put("state", __encodeInventoryState(s));
  }

  async pending(deps: {}): globalThis.Promise<readonly Reservation[]> {
    const __state = await this.loadState();
    const q: (() => readonly Reservation[]) = (() => globalThis.Object.values(__state.reservations).filter((__x) => ((r) => r.qty > 0)(__x)));
    return (q)();
  }

}

export function __makeInventory(key: string, env?: { INVENTORY?: __DurableObjectNamespace }): Inventory {
  return __makeAgent(__InventoryRegistry, env?.INVENTORY, key, (state) => new Inventory(state));
}

export function __resetAgents(): void {
  __InventoryRegistry.reset();
}

export function __serialise_Reservation(value: Reservation): __JsonValue {
  return {
    id: value.id as __JsonValue,
    qty: ((v: number) => { if (!globalThis.Number.isSafeInteger(v)) throw new globalThis.Error("Int outside the safe-integer range at boundary"); return v as __JsonValue; })(value.qty),
  };
}

export function __deserialise_Reservation(json: __JsonValue, path: string = "$"): Result<Reservation, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  if (typeof obj["id"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.id`, expected: "string", actual: typeof obj["id"] });
  }
  const __id = obj["id"];
  if (typeof obj["qty"] !== "number") {
    return Err({ kind: "StructuralMismatch", path: `${path}.qty`, expected: "number", actual: typeof obj["qty"] });
  }
  if (!globalThis.Number.isSafeInteger(obj["qty"])) {
    return Err({ kind: "StructuralMismatch", path: `${path}.qty`, expected: "safe integer", actual: String(obj["qty"]) });
  }
  const __qty = obj["qty"];
  return Ok({ id: __id, qty: __qty } as Reservation);
}

