// Generated by bynkc — do not edit by hand.
// commons bynk.locale.types

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../../runtime.js";

/**
 * A well-formed BCP-47 language tag: `language[-extlang][-Script][-REGION]
 * [-variant]*[-extension]*[-privateuse]`, or a standalone `x-...` private-use
 * tag (e.g. `en`, `pt-BR`, `zh-Hans-CN`, `zh-yue`, `ca-valencia`,
 * `de-CH-1996`, `en-US-u-ca-buddhist`, `de-CH-x-phonebk`, `x-custom`).
 * Casing is canonical by construction: language/extlang/variant/extension/
 * private-use lowercase, script Titlecase, region uppercase (or 3 digits).
 * Grandfathered/irregular tags (`i-klingon`, `en-GB-oed`) don't fit this
 * productive shape and are rejected. This checks well-formedness only, not
 * registry membership — `en-abc` (a made-up extlang shape) is well-formed
 * and accepted, and extlang position isn't restricted to a 2-letter primary
 * the way RFC 5646 restricts it.
 */
export type LocaleTag = string & { readonly __brand: "LocaleTag" };

export const LocaleTag = {
  of(value: string): Result<LocaleTag, ValidationError> {
    if (!(new RegExp("^(?:" + "(?:[a-z]{2,3}(?:-[a-z]{3}){0,3}(?:-[A-Z][a-z]{3})?(?:-(?:[A-Z]{2}|[0-9]{3}))?(?:-(?:[a-z0-9]{5,8}|[0-9][a-z0-9]{3}))*(?:-[a-wy-z0-9](?:-[a-z0-9]{2,8}){1,8})*(?:-x(?:-[a-z0-9]{1,8}){1,8})?|x(?:-[a-z0-9]{1,8}){1,8})" + ")$").test(value))) {
      return Err({ field: "LocaleTag", message: "must match /(?:[a-z]{2,3}(?:-[a-z]{3}){0,3}(?:-[A-Z][a-z]{3})?(?:-(?:[A-Z]{2}|[0-9]{3}))?(?:-(?:[a-z0-9]{5,8}|[0-9][a-z0-9]{3}))*(?:-[a-wy-z0-9](?:-[a-z0-9]{2,8}){1,8})*(?:-x(?:-[a-z0-9]{1,8}){1,8})?|x(?:-[a-z0-9]{1,8}){1,8})/", value });
    }
    return Ok(value as LocaleTag);
  },
};

/**
 * One value substitutable into a rendered message.
 */
export type MessageArg =
    { readonly tag: "Text"; readonly value: string }
  | { readonly tag: "Whole"; readonly value: number }
  | { readonly tag: "Num"; readonly value: number }
  | { readonly tag: "Moment"; readonly value: number };

export const MessageArg = {
  Text: (value: string): MessageArg => ({ tag: "Text", value }),
  Whole: (value: number): MessageArg => ({ tag: "Whole", value }),
  Num: (value: number): MessageArg => ({ tag: "Num", value }),
  Moment: (value: number): MessageArg => ({ tag: "Moment", value }),
};

/**
 * A message to render: a lookup code plus its named substitution values.
 */
export interface Message {
  readonly code: string;
  readonly params: ReadonlyMap<string, MessageArg>;
}

export const Message = {
};

