// Generated by bynkc — do not edit by hand.
// test target: demo.receivers

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";
import * as demo_receivers from "./../demo/receivers.js";

class ExpectationError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number, detail: string) {
    super(`${detail}\n  at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkExpectFailure(location: string, start: number, end: number, detail: string) {
  return new ExpectationError(location, start, end, detail);
}
function __bynkExpect(cond: boolean, location: string, start: number, end: number, detail: string): void {
  if (!cond) { throw __bynkExpectFailure(location, start, end, detail); }
}
function __bynkShow(v: unknown): string {
  try { return typeof v === "bigint" ? String(v) : (JSON.stringify(v) ?? String(v)); } catch { return String(v); }
}

function __makeTestDeps() {
  return {  };
}

// case tier: unit
async function test_a_negated____binds_both_tests_in_its_else_branch() {
  try {
    const deps = {};
    const { Booking, Q, andChain, book, id, implication, inLambda, negatedElse, negatedOr, negatedOrRightNested, negatedOrThree, negatedOrValue, nestedReceiver, orPattern, plainAnd, plainImplies, refinement, same, stmtIf, valueIf } = demo_receivers;
    type Booking = demo_receivers.Booking;
    type Q = demo_receivers.Q;
    if (!(negatedOr(Some(1), Some(2)) === 3)) { throw __bynkExpectFailure("demo/receivers_test.bynk:3:12", 94, 126, "expect negatedOr(Some(1), Some(2)) == 3\n  expected: negatedOr(Some(1), Some(2)) == 3\n  actual:   " + __bynkShow((negatedOr(Some(1), Some(2)))) + " == " + __bynkShow((3))); }
    if (!(negatedOr(None, Some(2)) === 0)) { throw __bynkExpectFailure("demo/receivers_test.bynk:4:12", 138, 167, "expect negatedOr(None, Some(2)) == 0\n  expected: negatedOr(None, Some(2)) == 0\n  actual:   " + __bynkShow((negatedOr(None, Some(2)))) + " == " + __bynkShow((0))); }
    if (!(negatedOr(Some(1), None) === 0)) { throw __bynkExpectFailure("demo/receivers_test.bynk:5:12", 179, 208, "expect negatedOr(Some(1), None) == 0\n  expected: negatedOr(Some(1), None) == 0\n  actual:   " + __bynkShow((negatedOr(Some(1), None))) + " == " + __bynkShow((0))); }
    if (!(negatedOrValue(Some(1), Some(2)) === 3)) { throw __bynkExpectFailure("demo/receivers_test.bynk:6:12", 220, 257, "expect negatedOrValue(Some(1), Some(2)) == 3\n  expected: negatedOrValue(Some(1), Some(2)) == 3\n  actual:   " + __bynkShow((negatedOrValue(Some(1), Some(2)))) + " == " + __bynkShow((3))); }
    if (!(negatedOrValue(Some(1), None) === 0)) { throw __bynkExpectFailure("demo/receivers_test.bynk:7:12", 269, 303, "expect negatedOrValue(Some(1), None) == 0\n  expected: negatedOrValue(Some(1), None) == 0\n  actual:   " + __bynkShow((negatedOrValue(Some(1), None))) + " == " + __bynkShow((0))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_negated____of_three_binds_all_three() {
  try {
    const deps = {};
    const { Booking, Q, andChain, book, id, implication, inLambda, negatedElse, negatedOr, negatedOrRightNested, negatedOrThree, negatedOrValue, nestedReceiver, orPattern, plainAnd, plainImplies, refinement, same, stmtIf, valueIf } = demo_receivers;
    type Booking = demo_receivers.Booking;
    type Q = demo_receivers.Q;
    if (!(negatedOrThree(Some(1), Some(2), Some(3)) === 6)) { throw __bynkExpectFailure("demo/receivers_test.bynk:11:12", 369, 415, "expect negatedOrThree(Some(1), Some(2), Some(3)) == 6\n  expected: negatedOrThree(Some(1), Some(2), Some(3)) == 6\n  actual:   " + __bynkShow((negatedOrThree(Some(1), Some(2), Some(3)))) + " == " + __bynkShow((6))); }
    if (!(negatedOrThree(Some(1), Some(2), None) === 0)) { throw __bynkExpectFailure("demo/receivers_test.bynk:12:12", 427, 470, "expect negatedOrThree(Some(1), Some(2), None) == 0\n  expected: negatedOrThree(Some(1), Some(2), None) == 0\n  actual:   " + __bynkShow((negatedOrThree(Some(1), Some(2), None))) + " == " + __bynkShow((0))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_right_nested____binds_all_three() {
  try {
    const deps = {};
    const { Booking, Q, andChain, book, id, implication, inLambda, negatedElse, negatedOr, negatedOrRightNested, negatedOrThree, negatedOrValue, nestedReceiver, orPattern, plainAnd, plainImplies, refinement, same, stmtIf, valueIf } = demo_receivers;
    type Booking = demo_receivers.Booking;
    type Q = demo_receivers.Q;
    if (!(negatedOrRightNested(Some(1), Some(2), Some(3)) === 6)) { throw __bynkExpectFailure("demo/receivers_test.bynk:16:12", 532, 584, "expect negatedOrRightNested(Some(1), Some(2), Some(3)) == 6\n  expected: negatedOrRightNested(Some(1), Some(2), Some(3)) == 6\n  actual:   " + __bynkShow((negatedOrRightNested(Some(1), Some(2), Some(3)))) + " == " + __bynkShow((6))); }
    if (!(negatedOrRightNested(Some(1), None, Some(3)) === 0)) { throw __bynkExpectFailure("demo/receivers_test.bynk:17:12", 596, 645, "expect negatedOrRightNested(Some(1), None, Some(3)) == 0\n  expected: negatedOrRightNested(Some(1), None, Some(3)) == 0\n  actual:   " + __bynkShow((negatedOrRightNested(Some(1), None, Some(3)))) + " == " + __bynkShow((0))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_plain____and_implies_bind_the_right_operand() {
  try {
    const deps = {};
    const { Booking, Q, andChain, book, id, implication, inLambda, negatedElse, negatedOr, negatedOrRightNested, negatedOrThree, negatedOrValue, nestedReceiver, orPattern, plainAnd, plainImplies, refinement, same, stmtIf, valueIf } = demo_receivers;
    type Booking = demo_receivers.Booking;
    type Q = demo_receivers.Q;
    if (!(plainAnd(true, Some(5)) === 5)) { throw __bynkExpectFailure("demo/receivers_test.bynk:21:12", 719, 747, "expect plainAnd(true, Some(5)) == 5\n  expected: plainAnd(true, Some(5)) == 5\n  actual:   " + __bynkShow((plainAnd(true, Some(5)))) + " == " + __bynkShow((5))); }
    if (!(plainAnd(false, Some(5)) === 0)) { throw __bynkExpectFailure("demo/receivers_test.bynk:22:12", 759, 788, "expect plainAnd(false, Some(5)) == 0\n  expected: plainAnd(false, Some(5)) == 0\n  actual:   " + __bynkShow((plainAnd(false, Some(5)))) + " == " + __bynkShow((0))); }
    if (!(plainAnd(true, None) === 0)) { throw __bynkExpectFailure("demo/receivers_test.bynk:23:12", 800, 825, "expect plainAnd(true, None) == 0\n  expected: plainAnd(true, None) == 0\n  actual:   " + __bynkShow((plainAnd(true, None))) + " == " + __bynkShow((0))); }
    if (!(plainImplies(true, Some(5)) === 5)) { throw __bynkExpectFailure("demo/receivers_test.bynk:24:12", 837, 869, "expect plainImplies(true, Some(5)) == 5\n  expected: plainImplies(true, Some(5)) == 5\n  actual:   " + __bynkShow((plainImplies(true, Some(5)))) + " == " + __bynkShow((5))); }
    if (!(plainImplies(false, Some(5)) === 0)) { throw __bynkExpectFailure("demo/receivers_test.bynk:25:12", 881, 914, "expect plainImplies(false, Some(5)) == 0\n  expected: plainImplies(false, Some(5)) == 0\n  actual:   " + __bynkShow((plainImplies(false, Some(5)))) + " == " + __bynkShow((0))); }
    if (!(plainImplies(true, None) === 0)) { throw __bynkExpectFailure("demo/receivers_test.bynk:26:12", 926, 955, "expect plainImplies(true, None) == 0\n  expected: plainImplies(true, None) == 0\n  actual:   " + __bynkShow((plainImplies(true, None))) + " == " + __bynkShow((0))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_lambda_s_temp_stays_in_the_lambda() {
  try {
    const deps = {};
    const { Booking, Q, andChain, book, id, implication, inLambda, negatedElse, negatedOr, negatedOrRightNested, negatedOrThree, negatedOrValue, nestedReceiver, orPattern, plainAnd, plainImplies, refinement, same, stmtIf, valueIf } = demo_receivers;
    type Booking = demo_receivers.Booking;
    type Q = demo_receivers.Q;
    if (!(inLambda(false, Some(2), [1, 2, 3]))) { throw __bynkExpectFailure("demo/receivers_test.bynk:30:12", 1019, 1054, "expect inLambda(false, Some(2), [1, 2, 3])"); }
    if (!(!inLambda(false, Some(9), [1, 2, 3]))) { throw __bynkExpectFailure("demo/receivers_test.bynk:31:12", 1066, 1102, "expect !inLambda(false, Some(9), [1, 2, 3])"); }
    if (!(inLambda(true, None, []))) { throw __bynkExpectFailure("demo/receivers_test.bynk:32:12", 1114, 1138, "expect inLambda(true, None, [])"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_the_other_gather_sites_still_read_their_temps() {
  try {
    const deps = {};
    const { Booking, Q, andChain, book, id, implication, inLambda, negatedElse, negatedOr, negatedOrRightNested, negatedOrThree, negatedOrValue, nestedReceiver, orPattern, plainAnd, plainImplies, refinement, same, stmtIf, valueIf } = demo_receivers;
    type Booking = demo_receivers.Booking;
    type Q = demo_receivers.Q;
    if (!(stmtIf(Some(4)) === 4)) { throw __bynkExpectFailure("demo/receivers_test.bynk:36:12", 1212, 1232, "expect stmtIf(Some(4)) == 4\n  expected: stmtIf(Some(4)) == 4\n  actual:   " + __bynkShow((stmtIf(Some(4)))) + " == " + __bynkShow((4))); }
    if (!(negatedElse(Some(4)) === 4)) { throw __bynkExpectFailure("demo/receivers_test.bynk:37:12", 1244, 1269, "expect negatedElse(Some(4)) == 4\n  expected: negatedElse(Some(4)) == 4\n  actual:   " + __bynkShow((negatedElse(Some(4)))) + " == " + __bynkShow((4))); }
    if (!(andChain(Booking.Held("g", 200)))) { throw __bynkExpectFailure("demo/receivers_test.bynk:38:12", 1281, 1305, "expect andChain(Held(\"g\", 200))"); }
    if (!(orPattern(Booking.Waitlisted("w")) === "w")) { throw __bynkExpectFailure("demo/receivers_test.bynk:39:12", 1317, 1350, "expect orPattern(Waitlisted(\"w\")) == \"w\"\n  expected: orPattern(Waitlisted(\"w\")) == \"w\"\n  actual:   " + __bynkShow((orPattern(Booking.Waitlisted("w")))) + " == " + __bynkShow(("w"))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run(only?: string) {
  const results = [];
  const want = (n: string): boolean => only === undefined || only === n;
  if (want("a negated || binds both tests in its else-branch")) results.push({ name: "a negated || binds both tests in its else-branch", ...(await test_a_negated____binds_both_tests_in_its_else_branch()) });
  if (want("a negated || of three binds all three")) results.push({ name: "a negated || of three binds all three", ...(await test_a_negated____of_three_binds_all_three()) });
  if (want("a right-nested || binds all three")) results.push({ name: "a right-nested || binds all three", ...(await test_a_right_nested____binds_all_three()) });
  if (want("a plain && and implies bind the right operand")) results.push({ name: "a plain && and implies bind the right operand", ...(await test_a_plain____and_implies_bind_the_right_operand()) });
  if (want("a lambda's temp stays in the lambda")) results.push({ name: "a lambda's temp stays in the lambda", ...(await test_a_lambda_s_temp_stays_in_the_lambda()) });
  if (want("the other gather sites still read their temps")) results.push({ name: "the other gather sites still read their temps", ...(await test_the_other_gather_sites_still_read_their_temps()) });
  return results;
}
