// Generated by bynkc — do not edit by hand.
// context app.greet

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

import { message, render, withText, withWhole } from "../bynk/locale.js";
import { Message as __CommonsMessage } from "../bynk/locale/types.js";

import * as bynk from "../bynk.js";

export type Message = __CommonsMessage & { readonly __ctxBrand: "app.greet" };

export const greeting = {
  async call(deps: { Locale: bynk.Locale }): Promise<string> {
    const tag = await deps.Locale.current();
    return render(tag, (message("hello") as Message));
  },
};

export const greetingWithName = {
  async call(name: string, deps: { Locale: bynk.Locale }): Promise<string> {
    const tag = await deps.Locale.current();
    const msg = (withText((message("greeting") as Message), "name", name) as Message);
    return render(tag, msg);
  },
};

export const greetingWithCountAndName = {
  async call(name: string, count: number, deps: { Locale: bynk.Locale }): Promise<string> {
    const tag = await deps.Locale.current();
    const msg = (withWhole((withText((message("greeting") as Message), "name", name) as Message), "count", count) as Message);
    return render(tag, msg);
  },
};

export interface AppGreetDeps {
  readonly Locale: bynk.Locale;
}

export function makeSurface(deps: AppGreetDeps) {
  return {
    async greeting(): Promise<string> {
      return greeting.call(deps);
    },
    async greetingWithName(name: string): Promise<string> {
      return greetingWithName.call(name, deps);
    },
    async greetingWithCountAndName(name: string, count: number): Promise<string> {
      return greetingWithCountAndName.call(name, count, deps);
    },
  };
}

