// Generated by bynkc — do not edit by hand.
// system test: demo.api

import { Ok, Err, Some, None, callService, type Result, type Option, type ValidationError, type JsonError, type JsonValue, type BoundaryError, type ServiceBinding, responseToHttpResult, responseToHttpOutcome, responseToUnauthOutcome, makeIntegrationDoNamespace, type DurableObjectState, type DurableObjectNamespace } from "../runtime.js";
import * as demo_api from "../workers/demo-api/handlers.js";
import worker_demo_api from "../workers/demo-api/index.js";
import * as demo_counter from "../workers/demo-counter/handlers.js";
import worker_demo_counter from "../workers/demo-counter/index.js";

class ExpectationError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number, detail: string) {
    super(`${detail}\n  at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkExpectFailure(location: string, start: number, end: number, detail: string) {
  return new ExpectationError(location, start, end, detail);
}
function __bynkExpect(cond: boolean, location: string, start: number, end: number, detail: string): void {
  if (!cond) { throw __bynkExpectFailure(location, start, end, detail); }
}
function __bynkShow(v: unknown): string {
  try { return typeof v === "bigint" ? String(v) : (JSON.stringify(v) ?? String(v)); } catch { return String(v); }
}

function makeHarness() {
  const env_demo_api: any = {};
  const env_demo_counter: any = {};
  env_demo_api.DEMO_COUNTER = { fetch: (req: Request) => worker_demo_counter.fetch(req, env_demo_counter) } as ServiceBinding;
  env_demo_counter.COUNTER = makeIntegrationDoNamespace((state) => new demo_counter.Counter(state));
  const rootEnv: any = {};
  rootEnv.DEMO_API = { fetch: (req: Request) => worker_demo_api.fetch(req, env_demo_api) } as ServiceBinding;
  rootEnv.DEMO_COUNTER = { fetch: (req: Request) => worker_demo_counter.fetch(req, env_demo_counter) } as ServiceBinding;
  return { env: rootEnv };
}

async function test_two_ticks_on_the_same_id_accumulate_across_the_wire() {
  try {
    const deps = makeHarness();
    const a = await callService(deps.env.DEMO_API, "tick", "c1" as JsonValue, demo_api.deserialise_Result_Int_ApiError, "integration", "309a1117c5ee9379");
    const b = await callService(deps.env.DEMO_API, "tick", "c1" as JsonValue, demo_api.deserialise_Result_Int_ApiError, "integration", "309a1117c5ee9379");
    void (((__d) => {
        switch (__d.tag) {
          case "Ok": {
            const n = __d.value;
            return __bynkExpect((n === 2), "check.bynk:7:24", 194, 200, "expect n == 2");
          }
          case "Err": {
            return __bynkExpect((false), "check.bynk:8:24", 224, 229, "expect false");
          }
        }
        throw new Error("non-exhaustive match");
      })(b));
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

async function test_a_fresh_id_starts_from_zero_in_a_new_case() {
  try {
    const deps = makeHarness();
    const a = await callService(deps.env.DEMO_API, "tick", "c2" as JsonValue, demo_api.deserialise_Result_Int_ApiError, "integration", "309a1117c5ee9379");
    void (((__d) => {
        switch (__d.tag) {
          case "Ok": {
            const n = __d.value;
            return __bynkExpect((n === 1), "check.bynk:15:24", 364, 370, "expect n == 1");
          }
          case "Err": {
            return __bynkExpect((false), "check.bynk:16:24", 394, 399, "expect false");
          }
        }
        throw new Error("non-exhaustive match");
      })(a));
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run(only?: string) {
  const results = [];
  const want = (n: string): boolean => only === undefined || only === n;
  if (want("two ticks on the same id accumulate across the wire")) results.push({ name: "two ticks on the same id accumulate across the wire", ...(await test_two_ticks_on_the_same_id_accumulate_across_the_wire()) });
  if (want("a fresh id starts from zero in a new case")) results.push({ name: "a fresh id starts from zero in a new case", ...(await test_a_fresh_id_starts_from_zero_in_a_new_case()) });
  return results;
}
