// Generated by bynkc — do not edit by hand.
// context demo.keys

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type __DurableObjectState, type __DurableObjectNamespace, __StateRegistry, __makeAgent, __rehydrationViolation, type __JsonValue, type __BoundaryError } from "../runtime.js";

/**
 * #1685: a store collection is a map over arbitrary `String` keys, and its keys
 * often come from request input. Its runtime form is a plain object, so before
 * #1685 a `__proto__` write was dropped (or reassigned the prototype) and an
 * inherited name such as `constructor` read as present. Each agent here is driven
 * with those keys by the suite.
 */

export interface Pt {
  readonly x: number;
  readonly y: number;
}

export const Pt = {
};

export interface Entry {
  readonly id: string;
  readonly tag: string;
}

export const Entry = {
};

export interface Line {
  readonly orderId: string;
  readonly qty: number;
}

export const Line = {
};

export interface Order {
  readonly id: string;
  readonly customer: string;
}

export const Order = {
};

export interface Total {
  readonly orderId: string;
  readonly total: number;
}

export const Total = {
};

export interface Clock {
  now(): globalThis.Promise<number>;
}

export const __ClockToken: symbol = globalThis.Symbol("Clock");

export class FixedClock implements Clock {
  async now(): globalThis.Promise<number> {
    return 0;
  }
}

export const __FixedClockProvider = { token: __ClockToken, factory: () => new FixedClock() };

export interface BagState {
  readonly items: globalThis.Record<string, number>;
}

const __BagRegistry = new __StateRegistry();
function __zeroOfBagState(): BagState { return { items: {} }; }

function __rehydrateBagState(s: BagState, stored: BagState): void {
  if (globalThis.Object.prototype.hasOwnProperty.call(stored, "items")) for (const __k of globalThis.Object.keys(s.items)) { const __r = ((__v) => typeof __v !== "number" ? Err({ kind: "StructuralMismatch", path: "items", expected: "safe integer", actual: typeof __v } as __BoundaryError) : globalThis.Number.isSafeInteger(__v) ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "items", expected: "safe integer", actual: String(__v) } as __BoundaryError))((s.items[__k] as unknown as __JsonValue)); if (__r.tag === "Err") throw __rehydrationViolation("Bag", __r.error); s.items[__k] = __r.value as unknown as (typeof s.items)[string]; }
  for (const __k of globalThis.Object.keys(s.items)) { const __r = ((__v) => typeof __v === "string" ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "items", expected: "string", actual: typeof __v } as __BoundaryError))((__k as unknown as __JsonValue)); if (__r.tag === "Err") throw __rehydrationViolation("Bag", __r.error); }
}

function __encodeBagState(s: BagState): globalThis.Record<string, unknown> {
  return { ...s, items: globalThis.Object.fromEntries(globalThis.Object.entries(s.items).map(([__k, __v]) => [__k, ((v: number) => { if (!globalThis.Number.isSafeInteger(v)) throw new globalThis.Error("Int outside the safe-integer range at boundary"); return v as __JsonValue; })(__v)])) };
}

export class Bag {
  state: __DurableObjectState;
  constructor(state: __DurableObjectState) {
    this.state = state;
  }

  private async loadState(): globalThis.Promise<BagState> {
    const stored = await this.state.storage.get<BagState>("state");
    if (stored === undefined) return __zeroOfBagState();
    const __merged = { ...__zeroOfBagState(), ...stored };
    __rehydrateBagState(__merged, stored);
    return __merged;
  }

  private async commitState(s: BagState): globalThis.Promise<void> {
    await this.state.storage.put("state", __encodeBagState(s));
  }

  async put(k: string, v: number, deps: {}): globalThis.Promise<void> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = await (globalThis.Object.defineProperty(__state.items, k, { value: v, writable: true, enumerable: true, configurable: true }), undefined);
      return undefined;
    })();
    await this.commitState(__state);
    return __result;
  }

  async get(k: string, deps: {}): globalThis.Promise<Option<number>> {
    const __state = await this.loadState();
    const r = await (() => { const __k = k; return globalThis.Object.hasOwn(__state.items, __k) ? Some(__state.items[__k]) : None; })();
    return r;
  }

  async has(k: string, deps: {}): globalThis.Promise<boolean> {
    const __state = await this.loadState();
    const r = await globalThis.Object.hasOwn(__state.items, k);
    return r;
  }

  async count(deps: {}): globalThis.Promise<number> {
    const __state = await this.loadState();
    const n = await globalThis.Object.keys(__state.items).length;
    return n;
  }

  async drop(k: string, deps: {}): globalThis.Promise<void> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = await ((delete __state.items[k]), undefined);
      return undefined;
    })();
    await this.commitState(__state);
    return __result;
  }

  async bump(k: string, deps: {}): globalThis.Promise<void> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = await (() => { const __k = k; globalThis.Object.defineProperty(__state.items, __k, { value: ((n) => n + 1)(globalThis.Object.hasOwn(__state.items, __k) ? __state.items[__k] : (0)), writable: true, enumerable: true, configurable: true }); return undefined; })();
      return undefined;
    })();
    await this.commitState(__state);
    return __result;
  }

  async add10(k: string, deps: {}): globalThis.Promise<void> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = await (() => { const __k = k; if (!globalThis.Object.hasOwn(__state.items, __k)) { throw new globalThis.Error("Map.update: key absent"); } __state.items[__k] = ((n) => n + 10)(__state.items[__k]); return undefined; })();
      return undefined;
    })();
    await this.commitState(__state);
    return __result;
  }

}

export function __makeBag(key: string, env?: { BAG?: __DurableObjectNamespace }): Bag {
  return __makeAgent(__BagRegistry, env?.BAG, key, (state) => new Bag(state));
}

export interface PointsState {
  readonly pts: globalThis.Record<string, Pt>;
}

const __PointsRegistry = new __StateRegistry();
function __zeroOfPointsState(): PointsState { return { pts: {} }; }

function __rehydratePointsState(s: PointsState, stored: PointsState): void {
  if (globalThis.Object.prototype.hasOwnProperty.call(stored, "pts")) for (const __k of globalThis.Object.keys(s.pts)) { const __r = __deserialise_Pt((s.pts[__k] as unknown as __JsonValue), "pts"); if (__r.tag === "Err") throw __rehydrationViolation("Points", __r.error); s.pts[__k] = __r.value as unknown as (typeof s.pts)[string]; }
  for (const __k of globalThis.Object.keys(s.pts)) { const __r = ((__v) => typeof __v === "string" ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "pts", expected: "string", actual: typeof __v } as __BoundaryError))((__k as unknown as __JsonValue)); if (__r.tag === "Err") throw __rehydrationViolation("Points", __r.error); }
}

function __encodePointsState(s: PointsState): globalThis.Record<string, unknown> {
  return { ...s, pts: globalThis.Object.fromEntries(globalThis.Object.entries(s.pts).map(([__k, __v]) => [__k, __serialise_Pt(__v)])) };
}

export class Points {
  state: __DurableObjectState;
  constructor(state: __DurableObjectState) {
    this.state = state;
  }

  private async loadState(): globalThis.Promise<PointsState> {
    const stored = await this.state.storage.get<PointsState>("state");
    if (stored === undefined) return __zeroOfPointsState();
    const __merged = { ...__zeroOfPointsState(), ...stored };
    __rehydratePointsState(__merged, stored);
    return __merged;
  }

  private async commitState(s: PointsState): globalThis.Promise<void> {
    await this.state.storage.put("state", __encodePointsState(s));
  }

  async put(k: string, x: number, deps: {}): globalThis.Promise<void> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = await (globalThis.Object.defineProperty(__state.pts, k, { value: { x: x, y: 0 }, writable: true, enumerable: true, configurable: true }), undefined);
      return undefined;
    })();
    await this.commitState(__state);
    return __result;
  }

  async count(deps: {}): globalThis.Promise<number> {
    const __state = await this.loadState();
    const n = await globalThis.Object.keys(__state.pts).length;
    return n;
  }

  async has(k: string, deps: {}): globalThis.Promise<boolean> {
    const __state = await this.loadState();
    const r = await globalThis.Object.hasOwn(__state.pts, k);
    return r;
  }

}

export function __makePoints(key: string, env?: { POINTS?: __DurableObjectNamespace }): Points {
  return __makeAgent(__PointsRegistry, env?.POINTS, key, (state) => new Points(state));
}

export interface TagsState {
  readonly tags: globalThis.Record<string, boolean>;
}

const __TagsRegistry = new __StateRegistry();
function __zeroOfTagsState(): TagsState { return { tags: {} }; }

function __rehydrateTagsState(s: TagsState, stored: TagsState): void {
  for (const __k of globalThis.Object.keys(s.tags)) { const __r = ((__v) => typeof __v === "string" ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "tags", expected: "string", actual: typeof __v } as __BoundaryError))((__k as unknown as __JsonValue)); if (__r.tag === "Err") throw __rehydrationViolation("Tags", __r.error); }
}

function __encodeTagsState(s: TagsState): globalThis.Record<string, unknown> {
  return { ...s };
}

export class Tags {
  state: __DurableObjectState;
  constructor(state: __DurableObjectState) {
    this.state = state;
  }

  private async loadState(): globalThis.Promise<TagsState> {
    const stored = await this.state.storage.get<TagsState>("state");
    if (stored === undefined) return __zeroOfTagsState();
    const __merged = { ...__zeroOfTagsState(), ...stored };
    __rehydrateTagsState(__merged, stored);
    return __merged;
  }

  private async commitState(s: TagsState): globalThis.Promise<void> {
    await this.state.storage.put("state", __encodeTagsState(s));
  }

  async add(k: string, deps: {}): globalThis.Promise<void> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = await (globalThis.Object.defineProperty(__state.tags, k, { value: true, writable: true, enumerable: true, configurable: true }), undefined);
      return undefined;
    })();
    await this.commitState(__state);
    return __result;
  }

  async has(k: string, deps: {}): globalThis.Promise<boolean> {
    const __state = await this.loadState();
    const r = await globalThis.Object.hasOwn(__state.tags, k);
    return r;
  }

  async count(deps: {}): globalThis.Promise<number> {
    const __state = await this.loadState();
    const n = await globalThis.Object.keys(__state.tags).length;
    return n;
  }

  async drop(k: string, deps: {}): globalThis.Promise<void> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = await ((delete __state.tags[k]), undefined);
      return undefined;
    })();
    await this.commitState(__state);
    return __result;
  }

}

export function __makeTags(key: string, env?: { TAGS?: __DurableObjectNamespace }): Tags {
  return __makeAgent(__TagsRegistry, env?.TAGS, key, (state) => new Tags(state));
}

export interface MemoState {
  readonly c: globalThis.Record<string, { v: number; exp: number }>;
}

const __MemoRegistry = new __StateRegistry();
function __zeroOfMemoState(): MemoState { return { c: {} }; }

function __rehydrateMemoState(s: MemoState, stored: MemoState): void {
  if (globalThis.Object.prototype.hasOwnProperty.call(stored, "c")) for (const __e of globalThis.Object.values(s.c)) { const __r = ((__v) => typeof __v !== "number" ? Err({ kind: "StructuralMismatch", path: "c", expected: "safe integer", actual: typeof __v } as __BoundaryError) : globalThis.Number.isSafeInteger(__v) ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "c", expected: "safe integer", actual: String(__v) } as __BoundaryError))((__e.v as unknown as __JsonValue)); if (__r.tag === "Err") throw __rehydrationViolation("Memo", __r.error); __e.v = __r.value as unknown as typeof __e.v; }
}

function __encodeMemoState(s: MemoState): globalThis.Record<string, unknown> {
  return { ...s, c: globalThis.Object.fromEntries(globalThis.Object.entries(s.c).map(([__k, __e]) => [__k, { ...__e, v: ((v: number) => { if (!globalThis.Number.isSafeInteger(v)) throw new globalThis.Error("Int outside the safe-integer range at boundary"); return v as __JsonValue; })(__e.v) }])) };
}

export class Memo {
  state: __DurableObjectState;
  constructor(state: __DurableObjectState) {
    this.state = state;
  }

  private async loadState(): globalThis.Promise<MemoState> {
    const stored = await this.state.storage.get<MemoState>("state");
    if (stored === undefined) return __zeroOfMemoState();
    const __merged = { ...__zeroOfMemoState(), ...stored };
    __rehydrateMemoState(__merged, stored);
    return __merged;
  }

  private async commitState(s: MemoState): globalThis.Promise<void> {
    await this.state.storage.put("state", __encodeMemoState(s));
  }

  async put(k: string, v: number, deps: { Clock: Clock }): globalThis.Promise<void> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = await (async () => { const __now = await deps.Clock.now(); globalThis.Object.defineProperty(__state.c, k, { value: { v: v, exp: __now + 300000 }, writable: true, enumerable: true, configurable: true }); return undefined; })();
      return undefined;
    })();
    await this.commitState(__state);
    return __result;
  }

  async get(k: string, deps: { Clock: Clock }): globalThis.Promise<Option<number>> {
    const __state = await this.loadState();
    const r = await (async () => { const __now = await deps.Clock.now(); const __k = k; return (globalThis.Object.hasOwn(__state.c, __k) && __state.c[__k].exp > __now) ? Some(__state.c[__k].v) : None; })();
    return r;
  }

  async has(k: string, deps: { Clock: Clock }): globalThis.Promise<boolean> {
    const __state = await this.loadState();
    const r = await (async () => { const __now = await deps.Clock.now(); const __k = k; return globalThis.Object.hasOwn(__state.c, __k) && __state.c[__k].exp > __now; })();
    return r;
  }

  async count(deps: { Clock: Clock }): globalThis.Promise<number> {
    const __state = await this.loadState();
    const n = await (async () => { const __now = await deps.Clock.now(); return globalThis.Object.values(__state.c).filter((__e) => __e.exp > __now).length; })();
    return n;
  }

  async drop(k: string, deps: {}): globalThis.Promise<void> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = await ((delete __state.c[k]), undefined);
      return undefined;
    })();
    await this.commitState(__state);
    return __result;
  }

  async add10(k: string, deps: { Clock: Clock }): globalThis.Promise<void> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = await (async () => { const __now = await deps.Clock.now(); const __k = k; if (!(globalThis.Object.hasOwn(__state.c, __k) && __state.c[__k].exp > __now)) { throw new globalThis.Error("Cache.update: key absent"); } __state.c[__k] = { v: ((n) => n + 10)(__state.c[__k].v), exp: __now + 300000 }; return undefined; })();
      return undefined;
    })();
    await this.commitState(__state);
    return __result;
  }

}

export function __makeMemo(key: string, env?: { MEMO?: __DurableObjectNamespace }): Memo {
  return __makeAgent(__MemoRegistry, env?.MEMO, key, (state) => new Memo(state));
}

export interface LedgerState {
  readonly entries: globalThis.Record<string, Entry>;
  readonly entries__idx_tag: globalThis.Record<string, string[]>;
}

const __LedgerRegistry = new __StateRegistry();
function __zeroOfLedgerState(): LedgerState { return { entries: {}, entries__idx_tag: {} }; }

function __rehydrateLedgerState(s: LedgerState, stored: LedgerState): void {
  if (globalThis.Object.prototype.hasOwnProperty.call(stored, "entries")) for (const __k of globalThis.Object.keys(s.entries)) { const __r = __deserialise_Entry((s.entries[__k] as unknown as __JsonValue), "entries"); if (__r.tag === "Err") throw __rehydrationViolation("Ledger", __r.error); s.entries[__k] = __r.value as unknown as (typeof s.entries)[string]; }
  for (const __k of globalThis.Object.keys(s.entries)) { const __r = ((__v) => typeof __v === "string" ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "entries", expected: "string", actual: typeof __v } as __BoundaryError))((__k as unknown as __JsonValue)); if (__r.tag === "Err") throw __rehydrationViolation("Ledger", __r.error); }
}

function __encodeLedgerState(s: LedgerState): globalThis.Record<string, unknown> {
  return { ...s, entries: globalThis.Object.fromEntries(globalThis.Object.entries(s.entries).map(([__k, __v]) => [__k, __serialise_Entry(__v)])) };
}

export class Ledger {
  state: __DurableObjectState;
  constructor(state: __DurableObjectState) {
    this.state = state;
  }

  private async loadState(): globalThis.Promise<LedgerState> {
    const stored = await this.state.storage.get<LedgerState>("state");
    if (stored === undefined) return __zeroOfLedgerState();
    const __merged = { ...__zeroOfLedgerState(), ...stored };
    __rehydrateLedgerState(__merged, stored);
    return __merged;
  }

  private async commitState(s: LedgerState): globalThis.Promise<void> {
    await this.state.storage.put("state", __encodeLedgerState(s));
  }

  async add(id: string, tag: string, deps: {}): globalThis.Promise<void> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = await (() => { const __k = String(id); const __v = { id: id, tag: tag }; const __o = globalThis.Object.hasOwn(__state.entries, __k) ? __state.entries[__k] : undefined; if (__o !== undefined) { { const __ik = String((__o).tag); const __ia = globalThis.Object.hasOwn(__state.entries__idx_tag, __ik) ? __state.entries__idx_tag[__ik] : undefined; if (__ia) { const __ii = __ia.indexOf(__k); if (__ii >= 0) __ia.splice(__ii, 1); if (__ia.length === 0) delete __state.entries__idx_tag[__ik]; } } } globalThis.Object.defineProperty(__state.entries, __k, { value: __v, writable: true, enumerable: true, configurable: true }); { const __ik = String((__v).tag); if (!globalThis.Object.hasOwn(__state.entries__idx_tag, __ik)) globalThis.Object.defineProperty(__state.entries__idx_tag, __ik, { value: [], writable: true, enumerable: true, configurable: true }); __state.entries__idx_tag[__ik].push(__k); } return undefined; })();
      return undefined;
    })();
    await this.commitState(__state);
    return __result;
  }

  async drop(id: string, deps: {}): globalThis.Promise<void> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = await (() => { const __k = String(id); const __o = globalThis.Object.hasOwn(__state.entries, __k) ? __state.entries[__k] : undefined; if (__o !== undefined) { { const __ik = String((__o).tag); const __ia = globalThis.Object.hasOwn(__state.entries__idx_tag, __ik) ? __state.entries__idx_tag[__ik] : undefined; if (__ia) { const __ii = __ia.indexOf(__k); if (__ii >= 0) __ia.splice(__ii, 1); if (__ia.length === 0) delete __state.entries__idx_tag[__ik]; } } delete __state.entries[__k]; } return undefined; })();
      return undefined;
    })();
    await this.commitState(__state);
    return __result;
  }

  async retag(id: string, tag: string, deps: {}): globalThis.Promise<void> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = await (() => { const __k = String(id); if (!globalThis.Object.hasOwn(__state.entries, __k)) { throw new globalThis.Error("Map.update: key absent"); } const __o = __state.entries[__k]; { const __ik = String((__o).tag); const __ia = globalThis.Object.hasOwn(__state.entries__idx_tag, __ik) ? __state.entries__idx_tag[__ik] : undefined; if (__ia) { const __ii = __ia.indexOf(__k); if (__ii >= 0) __ia.splice(__ii, 1); if (__ia.length === 0) delete __state.entries__idx_tag[__ik]; } } const __v = ((e) => ({ ...e, tag: tag }))(__o); __state.entries[__k] = __v; { const __ik = String((__v).tag); if (!globalThis.Object.hasOwn(__state.entries__idx_tag, __ik)) globalThis.Object.defineProperty(__state.entries__idx_tag, __ik, { value: [], writable: true, enumerable: true, configurable: true }); __state.entries__idx_tag[__ik].push(__k); } return undefined; })();
      return undefined;
    })();
    await this.commitState(__state);
    return __result;
  }

  async countTag(tag: string, deps: {}): globalThis.Promise<number> {
    const __state = await this.loadState();
    return ((() => { const __s = String(tag); const __ia = __state.entries__idx_tag; return (globalThis.Object.hasOwn(__ia, __s) ? __ia[__s] : []).map((__pk) => __state.entries[__pk]); }))().length;
  }

}

export function __makeLedger(key: string, env?: { LEDGER?: __DurableObjectNamespace }): Ledger {
  return __makeAgent(__LedgerRegistry, env?.LEDGER, key, (state) => new Ledger(state));
}

export interface SalesState {
  readonly orders: globalThis.Record<string, Order>;
  readonly lines: globalThis.Record<string, Line>;
}

const __SalesRegistry = new __StateRegistry();
function __zeroOfSalesState(): SalesState { return { orders: {}, lines: {} }; }

function __rehydrateSalesState(s: SalesState, stored: SalesState): void {
  if (globalThis.Object.prototype.hasOwnProperty.call(stored, "orders")) for (const __k of globalThis.Object.keys(s.orders)) { const __r = __deserialise_Order((s.orders[__k] as unknown as __JsonValue), "orders"); if (__r.tag === "Err") throw __rehydrationViolation("Sales", __r.error); s.orders[__k] = __r.value as unknown as (typeof s.orders)[string]; }
  for (const __k of globalThis.Object.keys(s.orders)) { const __r = ((__v) => typeof __v === "string" ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "orders", expected: "string", actual: typeof __v } as __BoundaryError))((__k as unknown as __JsonValue)); if (__r.tag === "Err") throw __rehydrationViolation("Sales", __r.error); }
  if (globalThis.Object.prototype.hasOwnProperty.call(stored, "lines")) for (const __k of globalThis.Object.keys(s.lines)) { const __r = __deserialise_Line((s.lines[__k] as unknown as __JsonValue), "lines"); if (__r.tag === "Err") throw __rehydrationViolation("Sales", __r.error); s.lines[__k] = __r.value as unknown as (typeof s.lines)[string]; }
  for (const __k of globalThis.Object.keys(s.lines)) { const __r = ((__v) => typeof __v === "string" ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "lines", expected: "string", actual: typeof __v } as __BoundaryError))((__k as unknown as __JsonValue)); if (__r.tag === "Err") throw __rehydrationViolation("Sales", __r.error); }
}

function __encodeSalesState(s: SalesState): globalThis.Record<string, unknown> {
  return { ...s, orders: globalThis.Object.fromEntries(globalThis.Object.entries(s.orders).map(([__k, __v]) => [__k, __serialise_Order(__v)])), lines: globalThis.Object.fromEntries(globalThis.Object.entries(s.lines).map(([__k, __v]) => [__k, __serialise_Line(__v)])) };
}

export class Sales {
  state: __DurableObjectState;
  constructor(state: __DurableObjectState) {
    this.state = state;
  }

  private async loadState(): globalThis.Promise<SalesState> {
    const stored = await this.state.storage.get<SalesState>("state");
    if (stored === undefined) return __zeroOfSalesState();
    const __merged = { ...__zeroOfSalesState(), ...stored };
    __rehydrateSalesState(__merged, stored);
    return __merged;
  }

  private async commitState(s: SalesState): globalThis.Promise<void> {
    await this.state.storage.put("state", __encodeSalesState(s));
  }

  async order(id: string, customer: string, deps: {}): globalThis.Promise<void> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = await (globalThis.Object.defineProperty(__state.orders, id, { value: { id: id, customer: customer }, writable: true, enumerable: true, configurable: true }), undefined);
      return undefined;
    })();
    await this.commitState(__state);
    return __result;
  }

  async line(k: string, orderId: string, qty: number, deps: {}): globalThis.Promise<void> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = await (globalThis.Object.defineProperty(__state.lines, k, { value: { orderId: orderId, qty: qty }, writable: true, enumerable: true, configurable: true }), undefined);
      return undefined;
    })();
    await this.commitState(__state);
    return __result;
  }

  async totals(deps: {}): globalThis.Promise<readonly Total[]> {
    const __state = await this.loadState();
    return ((() => { const __h: globalThis.Record<string, Line[]> = globalThis.Object.create(null); const __order: string[] = []; for (const __t of globalThis.Object.values(__state.lines)) { const __k = String(((l) => l.orderId)(__t)); if (!(__k in __h)) { __h[__k] = []; __order.push(__k); } __h[__k].push(__t); } return __order.map((__k) => { const __rows = __h[__k]; return ((oid, rows) => ({ orderId: oid, total: (rows).reduce((__s: number, __x: Line) => __s + ((r) => r.qty)(__x), 0) }))(((l) => l.orderId)(__rows[0]), __rows); }); }))();
  }

  async joined(deps: {}): globalThis.Promise<number> {
    const __state = await this.loadState();
    return ((() => { const __h: globalThis.Record<string, Order[]> = globalThis.Object.create(null); for (const __u of ((() => globalThis.Object.values(__state.orders)))()) { const __k = String(((o) => o.id)(__u)); (__h[__k] = __h[__k] ?? []).push(__u); } return globalThis.Object.values(__state.lines).flatMap((__t: Line) => { const __m = __h[String(((l) => l.orderId)(__t))] ?? []; return __m.map((__u: Order) => ((l, o) => l.qty)(__t, __u)); }); }))().length;
  }

}

export function __makeSales(key: string, env?: { SALES?: __DurableObjectNamespace }): Sales {
  return __makeAgent(__SalesRegistry, env?.SALES, key, (state) => new Sales(state));
}

export function __resetAgents(): void {
  __BagRegistry.reset();
  __PointsRegistry.reset();
  __TagsRegistry.reset();
  __MemoRegistry.reset();
  __LedgerRegistry.reset();
  __SalesRegistry.reset();
}

export function __serialise_Entry(value: Entry): __JsonValue {
  return {
    id: value.id as __JsonValue,
    tag: value.tag as __JsonValue,
  };
}

export function __deserialise_Entry(json: __JsonValue, path: string = "$"): Result<Entry, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  if (typeof obj["id"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.id`, expected: "string", actual: typeof obj["id"] });
  }
  const __id = obj["id"];
  if (typeof obj["tag"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.tag`, expected: "string", actual: typeof obj["tag"] });
  }
  const __tag = obj["tag"];
  return Ok({ id: __id, tag: __tag } as Entry);
}

export function __serialise_Line(value: Line): __JsonValue {
  return {
    orderId: value.orderId as __JsonValue,
    qty: ((v: number) => { if (!globalThis.Number.isSafeInteger(v)) throw new globalThis.Error("Int outside the safe-integer range at boundary"); return v as __JsonValue; })(value.qty),
  };
}

export function __deserialise_Line(json: __JsonValue, path: string = "$"): Result<Line, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  if (typeof obj["orderId"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.orderId`, expected: "string", actual: typeof obj["orderId"] });
  }
  const __orderId = obj["orderId"];
  if (typeof obj["qty"] !== "number") {
    return Err({ kind: "StructuralMismatch", path: `${path}.qty`, expected: "number", actual: typeof obj["qty"] });
  }
  if (!globalThis.Number.isSafeInteger(obj["qty"])) {
    return Err({ kind: "StructuralMismatch", path: `${path}.qty`, expected: "safe integer", actual: String(obj["qty"]) });
  }
  const __qty = obj["qty"];
  return Ok({ orderId: __orderId, qty: __qty } as Line);
}

export function __serialise_Order(value: Order): __JsonValue {
  return {
    id: value.id as __JsonValue,
    customer: value.customer as __JsonValue,
  };
}

export function __deserialise_Order(json: __JsonValue, path: string = "$"): Result<Order, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  if (typeof obj["id"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.id`, expected: "string", actual: typeof obj["id"] });
  }
  const __id = obj["id"];
  if (typeof obj["customer"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.customer`, expected: "string", actual: typeof obj["customer"] });
  }
  const __customer = obj["customer"];
  return Ok({ id: __id, customer: __customer } as Order);
}

export function __serialise_Pt(value: Pt): __JsonValue {
  return {
    x: ((v: number) => { if (!globalThis.Number.isSafeInteger(v)) throw new globalThis.Error("Int outside the safe-integer range at boundary"); return v as __JsonValue; })(value.x),
    y: ((v: number) => { if (!globalThis.Number.isSafeInteger(v)) throw new globalThis.Error("Int outside the safe-integer range at boundary"); return v as __JsonValue; })(value.y),
  };
}

export function __deserialise_Pt(json: __JsonValue, path: string = "$"): Result<Pt, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  if (typeof obj["x"] !== "number") {
    return Err({ kind: "StructuralMismatch", path: `${path}.x`, expected: "number", actual: typeof obj["x"] });
  }
  if (!globalThis.Number.isSafeInteger(obj["x"])) {
    return Err({ kind: "StructuralMismatch", path: `${path}.x`, expected: "safe integer", actual: String(obj["x"]) });
  }
  const __x = obj["x"];
  if (typeof obj["y"] !== "number") {
    return Err({ kind: "StructuralMismatch", path: `${path}.y`, expected: "number", actual: typeof obj["y"] });
  }
  if (!globalThis.Number.isSafeInteger(obj["y"])) {
    return Err({ kind: "StructuralMismatch", path: `${path}.y`, expected: "safe integer", actual: String(obj["y"]) });
  }
  const __y = obj["y"];
  return Ok({ x: __x, y: __y } as Pt);
}

