// Generated by bynkc — do not edit by hand.
// context app.web

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type JsonError, type __DurableObjectState, type __DurableObjectNamespace, __StateRegistry, __makeAgent, __rehydrationViolation, type __JsonValue, type __BoundaryError } from "../runtime.js";

import { Item as __CommonsItem, Label as __CommonsLabel, Name as __CommonsName, Note as __CommonsNote, Tag as __CommonsTag } from "./model.js";

export type Item = __CommonsItem & { readonly __ctxBrand?: "app.web" };
export type Label = __CommonsLabel & { readonly __ctxBrand?: "app.web" };
export type Name = __CommonsName & { readonly __ctxBrand?: "app.web" };
export const Name = {
  of(value: string): Result<Name, ValidationError> { return __CommonsName.of(value); },
};
export type Note = __CommonsNote & { readonly __ctxBrand?: "app.web" };
export const Note = {
  of(value: string): Result<Note, ValidationError> { return __CommonsNote.of(value); },
};
export type Tag = __CommonsTag & { readonly __ctxBrand?: "app.web" };
export const Tag = {
  of(value: string): Result<Tag, ValidationError> { return __CommonsTag.of(value); },
};

export function label_json(l: Label): string {
  return globalThis.JSON.stringify(__serialise_Label(l));
}

export interface ShelfState {
  readonly items: globalThis.Record<string, Item>;
}

const __ShelfRegistry = new __StateRegistry();
function __zeroOfShelfState(): ShelfState { return { items: {} }; }

function __rehydrateShelfState(s: ShelfState, stored: ShelfState): void {
  if (globalThis.Object.prototype.hasOwnProperty.call(stored, "items")) for (const __k of globalThis.Object.keys(s.items)) { const __r = __deserialise_Item((s.items[__k] as unknown as __JsonValue), "items"); if (__r.tag === "Err") throw __rehydrationViolation("Shelf", __r.error); s.items[__k] = __r.value as unknown as (typeof s.items)[string]; }
  for (const __k of globalThis.Object.keys(s.items)) { const __r = ((__v) => typeof __v === "string" ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "items", expected: "string", actual: typeof __v } as __BoundaryError))((__k as unknown as __JsonValue)); if (__r.tag === "Err") throw __rehydrationViolation("Shelf", __r.error); }
}

function __encodeShelfState(s: ShelfState): globalThis.Record<string, unknown> {
  return { ...s, items: globalThis.Object.fromEntries(globalThis.Object.entries(s.items).map(([__k, __v]) => [__k, __serialise_Item(__v)])) };
}

export class Shelf {
  state: __DurableObjectState;
  constructor(state: __DurableObjectState) {
    this.state = state;
  }

  private async loadState(): globalThis.Promise<ShelfState> {
    const stored = await this.state.storage.get<ShelfState>("state");
    if (stored === undefined) return __zeroOfShelfState();
    const __merged = { ...__zeroOfShelfState(), ...stored };
    __rehydrateShelfState(__merged, stored);
    return __merged;
  }

  private async commitState(s: ShelfState): globalThis.Promise<void> {
    await this.state.storage.put("state", __encodeShelfState(s));
  }

  async put(item: Item, deps: {}): globalThis.Promise<boolean> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = await (globalThis.Object.defineProperty(__state.items, item.name, { value: item, writable: true, enumerable: true, configurable: true }), undefined);
      return true;
    })();
    await this.commitState(__state);
    return __result;
  }

}

export function __makeShelf(key: string, env?: { SHELF?: __DurableObjectNamespace }): Shelf {
  return __makeAgent(__ShelfRegistry, env?.SHELF, key, (state) => new Shelf(state));
}

export function __resetAgents(): void {
  __ShelfRegistry.reset();
}

export function __serialise_Item(value: Item): __JsonValue {
  return {
    name: __serialise_Name(value.name),
    note: __serialise_Note(value.note),
  };
}

export function __deserialise_Item(json: __JsonValue, path: string = "$"): Result<Item, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  const __r_name = __deserialise_Name(obj["name"], `${path}.name`);
  if (__r_name.tag === "Err") return __r_name;
  const __name = __r_name.value;
  const __r_note = __deserialise_Note(obj["note"], `${path}.note`);
  if (__r_note.tag === "Err") return __r_note;
  const __note = __r_note.value;
  return Ok({ name: __name, note: __note } as Item);
}

export function __serialise_Name(value: Name): __JsonValue {
  return value as unknown as string;
}

export function __deserialise_Name(json: __JsonValue, path: string = "$"): Result<Name, __BoundaryError> {
  if (typeof json !== "string") {
    return Err({ kind: "StructuralMismatch", path, expected: "string", actual: typeof json });
  }
  const validated = (typeof (Name as unknown as { of?: (json: unknown) => Result<unknown, ValidationError> }).of === "function")
    ? (Name as unknown as { of: (json: unknown) => Result<unknown, ValidationError> }).of(json)
    : (Ok(json as unknown as Name) as Result<unknown, ValidationError>);
  if (validated.tag === "Err") {
    return Err({ kind: "RefinementViolation", path, violation: validated.error });
  }
  return Ok(validated.value as Name);
}

export function __serialise_Note(value: Note): __JsonValue {
  return value as unknown as string;
}

export function __deserialise_Note(json: __JsonValue, path: string = "$"): Result<Note, __BoundaryError> {
  if (typeof json !== "string") {
    return Err({ kind: "StructuralMismatch", path, expected: "string", actual: typeof json });
  }
  const validated = (typeof (Note as unknown as { of?: (json: unknown) => Result<unknown, ValidationError> }).of === "function")
    ? (Note as unknown as { of: (json: unknown) => Result<unknown, ValidationError> }).of(json)
    : (Ok(json as unknown as Note) as Result<unknown, ValidationError>);
  if (validated.tag === "Err") {
    return Err({ kind: "RefinementViolation", path, violation: validated.error });
  }
  return Ok(validated.value as Note);
}


export function __serialise_Label(value: Label): __JsonValue {
  return {
    text: value.text as __JsonValue,
    tag: __serialise_Tag(value.tag),
  };
}

export function __deserialise_Label(json: __JsonValue, path: string = "$"): Result<Label, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  if (typeof obj["text"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.text`, expected: "string", actual: typeof obj["text"] });
  }
  const __text = obj["text"];
  const __r_tag = __deserialise_Tag(obj["tag"], `${path}.tag`);
  if (__r_tag.tag === "Err") return __r_tag;
  const __tag = __r_tag.value;
  return Ok({ text: __text, tag: __tag } as Label);
}

export function __serialise_Tag(value: Tag): __JsonValue {
  return value as unknown as string;
}

export function __deserialise_Tag(json: __JsonValue, path: string = "$"): Result<Tag, __BoundaryError> {
  if (typeof json !== "string") {
    return Err({ kind: "StructuralMismatch", path, expected: "string", actual: typeof json });
  }
  const validated = (typeof (Tag as unknown as { of?: (json: unknown) => Result<unknown, ValidationError> }).of === "function")
    ? (Tag as unknown as { of: (json: unknown) => Result<unknown, ValidationError> }).of(json)
    : (Ok(json as unknown as Tag) as Result<unknown, ValidationError>);
  if (validated.tag === "Err") {
    return Err({ kind: "RefinementViolation", path, violation: validated.error });
  }
  return Ok(validated.value as Tag);
}

