// Generated by bynkc — do not edit by hand.
// commons demo.shadow

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

export function bump(x: number): number {
  const n = x;
  const __r0 = n + 1;
  const __r1 = __r0 + 1;
  return __r1;
}

export function describe(x: number): string {
  const v = x;
  const __r0 = v > 0;
  const __r1 = (__r0 ? "positive" : "non-positive");
  return __r1;
}

