// Generated by bynkc — do not edit by hand.
// test target: demo.chain

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";
import * as demo_chain from "./../demo/chain.js";

class ExpectationError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number, detail: string) {
    super(`${detail}\n  at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkExpectFailure(location: string, start: number, end: number, detail: string) {
  return new ExpectationError(location, start, end, detail);
}
function __bynkExpect(cond: boolean, location: string, start: number, end: number, detail: string): void {
  if (!cond) { throw __bynkExpectFailure(location, start, end, detail); }
}
function __bynkShow(v: unknown): string {
  try { return typeof v === "bigint" ? String(v) : (JSON.stringify(v) ?? String(v)); } catch { return String(v); }
}

function __makeTestDeps() {
  return {  };
}

// case tier: unit
async function test_a_then_branch_reads_the_right_operand_s_binding() {
  try {
    const deps = {};
    const { Booking, four, implied, middle, negated, rooms, two } = demo_chain;
    type Booking = demo_chain.Booking;
    if (!(two(Some(1), Some(2)) === 3)) { throw __bynkExpectFailure("demo/chain_test.bynk:3:12", 89, 115, "expect two(Some(1), Some(2)) == 3\n  expected: two(Some(1), Some(2)) == 3\n  actual:   " + __bynkShow((two(Some(1), Some(2)))) + " == " + __bynkShow((3))); }
    if (!(two(Some(1), None) === 0)) { throw __bynkExpectFailure("demo/chain_test.bynk:4:12", 127, 150, "expect two(Some(1), None) == 0\n  expected: two(Some(1), None) == 0\n  actual:   " + __bynkShow((two(Some(1), None))) + " == " + __bynkShow((0))); }
    if (!(two(None, Some(2)) === 0)) { throw __bynkExpectFailure("demo/chain_test.bynk:5:12", 162, 185, "expect two(None, Some(2)) == 0\n  expected: two(None, Some(2)) == 0\n  actual:   " + __bynkShow((two(None, Some(2)))) + " == " + __bynkShow((0))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_later_operand_reads_a_middle_operand_s_binding() {
  try {
    const deps = {};
    const { Booking, four, implied, middle, negated, rooms, two } = demo_chain;
    type Booking = demo_chain.Booking;
    if (!(middle(Some(1), Some(2)))) { throw __bynkExpectFailure("demo/chain_test.bynk:9:12", 262, 286, "expect middle(Some(1), Some(2))"); }
    if (!(!middle(Some(2), Some(1)))) { throw __bynkExpectFailure("demo/chain_test.bynk:10:12", 298, 323, "expect !middle(Some(2), Some(1))"); }
    if (!(!middle(Some(1), None))) { throw __bynkExpectFailure("demo/chain_test.bynk:11:12", 335, 357, "expect !middle(Some(1), None)"); }
    if (!(four(Some(1), Some(2), Some(3)))) { throw __bynkExpectFailure("demo/chain_test.bynk:12:12", 369, 400, "expect four(Some(1), Some(2), Some(3))"); }
    if (!(!four(Some(1), Some(3), Some(2)))) { throw __bynkExpectFailure("demo/chain_test.bynk:13:12", 412, 444, "expect !four(Some(1), Some(3), Some(2))"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_field_bindings_of_a_user_sum() {
  try {
    const deps = {};
    const { Booking, four, implied, middle, negated, rooms, two } = demo_chain;
    type Booking = demo_chain.Booking;
    if (!(rooms(Booking.Held("a", 1), Booking.Held("b", 2)))) { throw __bynkExpectFailure("demo/chain_test.bynk:17:12", 501, 534, "expect rooms(Held(\"a\", 1), Held(\"b\", 2))"); }
    if (!(!rooms(Booking.Held("a", 1), Booking.Held("a", 2)))) { throw __bynkExpectFailure("demo/chain_test.bynk:18:12", 546, 580, "expect !rooms(Held(\"a\", 1), Held(\"a\", 2))"); }
    if (!(!rooms(Booking.Held("a", 1), Booking.Released))) { throw __bynkExpectFailure("demo/chain_test.bynk:19:12", 592, 622, "expect !rooms(Held(\"a\", 1), Released)"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_negated____and_an_implies() {
  try {
    const deps = {};
    const { Booking, four, implied, middle, negated, rooms, two } = demo_chain;
    type Booking = demo_chain.Booking;
    if (!(negated(Some(1), Some(2)) === 3)) { throw __bynkExpectFailure("demo/chain_test.bynk:23:12", 678, 708, "expect negated(Some(1), Some(2)) == 3\n  expected: negated(Some(1), Some(2)) == 3\n  actual:   " + __bynkShow((negated(Some(1), Some(2)))) + " == " + __bynkShow((3))); }
    if (!(negated(Some(1), None) === 0)) { throw __bynkExpectFailure("demo/chain_test.bynk:24:12", 720, 747, "expect negated(Some(1), None) == 0\n  expected: negated(Some(1), None) == 0\n  actual:   " + __bynkShow((negated(Some(1), None))) + " == " + __bynkShow((0))); }
    if (!(implied(Some(1), Some(2)))) { throw __bynkExpectFailure("demo/chain_test.bynk:25:12", 759, 784, "expect implied(Some(1), Some(2))"); }
    if (!(!implied(Some(2), Some(1)))) { throw __bynkExpectFailure("demo/chain_test.bynk:26:12", 796, 822, "expect !implied(Some(2), Some(1))"); }
    if (!(implied(None, None))) { throw __bynkExpectFailure("demo/chain_test.bynk:27:12", 834, 853, "expect implied(None, None)"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run(only?: string) {
  const results = [];
  const want = (n: string): boolean => only === undefined || only === n;
  if (want("a then-branch reads the right operand's binding")) results.push({ name: "a then-branch reads the right operand's binding", ...(await test_a_then_branch_reads_the_right_operand_s_binding()) });
  if (want("a later operand reads a middle operand's binding")) results.push({ name: "a later operand reads a middle operand's binding", ...(await test_a_later_operand_reads_a_middle_operand_s_binding()) });
  if (want("field bindings of a user sum")) results.push({ name: "field bindings of a user sum", ...(await test_field_bindings_of_a_user_sum()) });
  if (want("a negated || and an implies")) results.push({ name: "a negated || and an implies", ...(await test_a_negated____and_an_implies()) });
  return results;
}
