// Generated by bynkc — do not edit by hand.
// commons pricing

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, __bynkIntDiv, __bynkToInt } from "./runtime.js";

export type Price = number & { readonly __brand: "Price" };

export const Price = {
  of(value: number): Result<Price, ValidationError> {
    if (!Number.isFinite(value)) {
      return Err({ field: "Price", message: "must be a finite number", value });
    }
    if (!(value > 0)) {
      return Err({ field: "Price", message: "must be positive", value });
    }
    return Ok(value as Price);
  },
};

export type Ratio = number & { readonly __brand: "Ratio" };

export const Ratio = {
  of(value: number): Result<Ratio, ValidationError> {
    if (!Number.isFinite(value)) {
      return Err({ field: "Ratio", message: "must be a finite number", value });
    }
    if (!(value >= 0.0 && value <= 1.0)) {
      return Err({ field: "Ratio", message: "must be in range [0.0, 1.0]", value });
    }
    return Ok(value as Ratio);
  },
};

export function toCents(p: number): number {
  return __bynkToInt(Math.round((p * 100.0)), "round");
}

export function fromCents(c: number): number {
  return c / 100.0;
}

export function roundings(f: number): number {
  return __bynkToInt(Math.round(f), "round") + __bynkToInt(Math.floor(f), "floor") + __bynkToInt(Math.ceil(f), "ceil") + __bynkToInt(Math.trunc(f), "truncate");
}

export function mkPrice(raw: number): Result<Price, ValidationError> {
  return Price.of(raw);
}

export function discounted(p: Price, r: Ratio): number {
  return p * r;
}

export function demo(): boolean {
  const half: Ratio = (0.5 as Ratio);
  const __r0 = mkPrice(19.99);
  switch (__r0.tag) {
    case "Ok": {
      const p = __r0.value;
      return discounted(p, half) > 9.0;
    }
    case "Err": {
      return false;
    }
  }
  throw new Error("non-exhaustive match");
}

