// Generated by bynkc — do not edit by hand.
// composition root

import * as demo_prec from "./demo/prec.js";
import * as bynk_cloudflare__binding from "./bynk/cloudflare.binding.js";

export function composeApp(env?: unknown) {
  const demo_precDeps = { Kv: new bynk_cloudflare__binding.WorkersKv(env) };
  const demo_precSurface = demo_prec.makeSurface(demo_precDeps);

  return {
    prec: demo_precSurface,
  };
}
