// Generated by bynkc — do not edit by hand.
// context quote

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type __JsonValue, type __BoundaryError, type __ServiceBinding, __callService, __boundaryError } from "../../runtime.js";

export interface Quote {
  readonly sku: string;
  readonly price: number;
  readonly qty: number;
}

export const Quote = {
};

export const quotes = {
  async call(sku: string, price: number, deps: {}): globalThis.Promise<Result<Quote, void>> {
    return Ok({ sku: sku, price: price * 1.2, qty: 1 });
  },
};

export function __serialise_Quote(value: Quote): __JsonValue {
  return {
    sku: value.sku as __JsonValue,
    price: ((v: number) => { if (!globalThis.Number.isFinite(v)) throw new globalThis.Error("non-finite Float at boundary"); return v as __JsonValue; })(value.price),
    qty: ((v: number) => { if (!globalThis.Number.isSafeInteger(v)) throw new globalThis.Error("Int outside the safe-integer range at boundary"); return v as __JsonValue; })(value.qty),
  };
}

export function __deserialise_Quote(json: __JsonValue, path: string = "$"): Result<Quote, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  if (typeof obj["sku"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.sku`, expected: "string", actual: typeof obj["sku"] });
  }
  const __sku = obj["sku"];
  if (typeof obj["price"] !== "number") {
    return Err({ kind: "StructuralMismatch", path: `${path}.price`, expected: "number", actual: typeof obj["price"] });
  }
  if (!globalThis.Number.isFinite(obj["price"])) {
    return Err({ kind: "StructuralMismatch", path: `${path}.price`, expected: "finite number", actual: String(obj["price"]) });
  }
  const __price = obj["price"];
  if (typeof obj["qty"] !== "number") {
    return Err({ kind: "StructuralMismatch", path: `${path}.qty`, expected: "number", actual: typeof obj["qty"] });
  }
  if (!globalThis.Number.isSafeInteger(obj["qty"])) {
    return Err({ kind: "StructuralMismatch", path: `${path}.qty`, expected: "safe integer", actual: String(obj["qty"]) });
  }
  const __qty = obj["qty"];
  return Ok({ sku: __sku, price: __price, qty: __qty } as Quote);
}


export function __serialise_Result_Quote_Unit(value: Result<Quote, void>): __JsonValue {
  if (value.tag === "Ok") return { kind: "Ok", value: __serialise_Quote(value.value) };
  return { kind: "Err", error: null };
}

export function __deserialise_Result_Quote_Unit(json: __JsonValue, path: string = "$"): Result<Result<Quote, void>, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  if (obj["kind"] === "Ok") {
  const __r_v = __deserialise_Quote(obj["value"], `${path}.value`);
  if (__r_v.tag === "Err") return __r_v;
  const __v = __r_v.value;
    return Ok(Ok(__v) as Result<Quote, void>);
  } else if (obj["kind"] === "Err") {
  const __e = undefined;
    return Ok(Err(__e) as Result<Quote, void>);
  }
  return Err({ kind: "StructuralMismatch", path, expected: "Ok | Err", actual: String(obj["kind"]) });
}
