// Generated by bynkc — do not edit by hand.
// context demo

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type __JsonValue, type __BoundaryError, type __ServiceBinding, __callService, __boundaryError } from "../../runtime.js";

export interface Logger {
  info(message: string): globalThis.Promise<void>;
}

export const __LoggerToken: symbol = globalThis.Symbol("Logger");

export interface Greeter {
  greet(): globalThis.Promise<void>;
}

export const __GreeterToken: symbol = globalThis.Symbol("Greeter");

export class ConsoleLogger implements Logger {
  async info(message: string): globalThis.Promise<void> {
    return undefined;
  }
}

export const __ConsoleLoggerProvider = { token: __LoggerToken, factory: () => new ConsoleLogger() };

export class PoliteGreeter implements Greeter {
  private deps: { Logger: Logger };
  constructor(deps: { Logger: Logger }) { this.deps = deps; }
  async greet(): globalThis.Promise<void> {
    const __r0 = await this.deps.Logger.info("hello");
    return undefined;
  }
}

export const __PoliteGreeterProvider = { token: __GreeterToken, factory: (deps: { Logger: Logger }) => new PoliteGreeter(deps) };

export const hello = {
  async call(deps: { Greeter: Greeter }): globalThis.Promise<void> {
    const __r0 = await deps.Greeter.greet();
    return undefined;
  },
};

