// Generated by bynkc — do not edit by hand.
// context shop.orders

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../../runtime.js";

import { __makeTally } from "./tally.js";

export const count = {
  async call(id: string, deps: {}): globalThis.Promise<number> {
    return __makeTally(id).hit(deps);
  },
};

export interface __ShopOrdersDeps {
}

export function __makeSurface(deps: __ShopOrdersDeps) {
  return {
    async count(id: string): globalThis.Promise<number> {
      return count.call(id, deps);
    },
  };
}
