// Generated by bynkc — do not edit by hand.
// composition root for `commerce.notifications` Worker.

import { type ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";
import * as bynk__binding from "../../bynk-cloudflare.js";

export interface Env {
  COMMERCE_ORDER: ServiceBinding;
}

export function compose(env: Env) {
  const Logger = new bynk__binding.LoggerProvider();
  const deps = { Logger, env };
  return {
    async OnAny(payload: unknown, envelope: unknown) {
      return handlers.OnAny.event(payload as any, envelope as any, deps);
    },
    async OnMid(payload: unknown, envelope: unknown) {
      return handlers.OnMid.event(payload as any, envelope as any, deps);
    },
  };
}
