// Generated by bynkc — do not edit by hand.
// test target: demo.codes

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";
import * as demo_codes from "./../demo/codes.js";

class ExpectationError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number, detail: string) {
    super(`${detail}\n  at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkExpectFailure(location: string, start: number, end: number, detail: string) {
  return new ExpectationError(location, start, end, detail);
}
function __bynkExpect(cond: boolean, location: string, start: number, end: number, detail: string): void {
  if (!cond) { throw __bynkExpectFailure(location, start, end, detail); }
}
function __bynkShow(v: unknown): string {
  try { return typeof v === "bigint" ? String(v) : (JSON.stringify(v) ?? String(v)); } catch { return String(v); }
}

function makeTestDeps() {
  return {  };
}

// case tier: unit
async function test_a_value_within_the_bound_and_the_pattern_is_accepted() {
  try {
    const deps = {};
    const { Code, accepts, admits } = demo_codes;
    type Code = demo_codes.Code;
    if (!(accepts("12-34"))) { throw __bynkExpectFailure("tests/demo/codes.bynk:7:10", 151, 167, "expect accepts(\"12-34\")"); }
    if (!(admits("12-34"))) { throw __bynkExpectFailure("tests/demo/codes.bynk:8:10", 177, 192, "expect admits(\"12-34\")"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_value_outside_the_pattern_is_rejected() {
  try {
    const deps = {};
    const { Code, accepts, admits } = demo_codes;
    type Code = demo_codes.Code;
    if (!(!accepts("12-ab"))) { throw __bynkExpectFailure("tests/demo/codes.bynk:12:10", 254, 271, "expect !accepts(\"12-ab\")"); }
    if (!(!admits("12-ab"))) { throw __bynkExpectFailure("tests/demo/codes.bynk:13:10", 281, 297, "expect !admits(\"12-ab\")"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_value_over_the_length_bound_is_rejected() {
  try {
    const deps = {};
    const { Code, accepts, admits } = demo_codes;
    type Code = demo_codes.Code;
    if (!(!accepts("12345678901234567"))) { throw __bynkExpectFailure("tests/demo/codes.bynk:17:10", 361, 390, "expect !accepts(\"12345678901234567\")"); }
    if (!(!admits("12345678901234567"))) { throw __bynkExpectFailure("tests/demo/codes.bynk:18:10", 400, 428, "expect !admits(\"12345678901234567\")"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run(only?: string) {
  const results = [];
  const want = (n: string): boolean => only === undefined || only === n;
  if (want("a value within the bound and the pattern is accepted")) results.push({ name: "a value within the bound and the pattern is accepted", ...(await test_a_value_within_the_bound_and_the_pattern_is_accepted()) });
  if (want("a value outside the pattern is rejected")) results.push({ name: "a value outside the pattern is rejected", ...(await test_a_value_outside_the_pattern_is_rejected()) });
  if (want("a value over the length bound is rejected")) results.push({ name: "a value over the length bound is rejected", ...(await test_a_value_over_the_length_bound_is_rejected()) });
  return results;
}
