// Generated by bynkc — do not edit by hand.
// context wire.auth

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type JsonValue, type BoundaryError, type ServiceBinding, callService, boundaryError } from "../../runtime.js";

/**
 * #855 anti-drift fixture (`bynkc/tests/wire_shape_drift.rs`): the callee whose
 * boundary types a consuming context must generate its own codecs for. A
 * transparent refined type with **two** predicates in a specific declaration
 * order (`ClientId` — exercises `Revalidation::ViaConstructor` here, and
 * `Revalidation::Inline` at the consumer, one `if (!(` per predicate in
 * declaration order), and an opaque type (`AuthId` — exercises
 * `Revalidation::StructuralOnly` at the consumer, no predicate check at all).
 * `LoginError` is a plain sum crossing the same boundary, for the sum-codec
 * cross-check (`obj["kind"]` deserialising, `value.tag` serialising).
 */

export type ClientId = string & { readonly __brand: "wire.auth.ClientId" };

export const ClientId = {
  of(value: string): Result<ClientId, ValidationError> {
    if (!(value.length > 0)) {
      return Err({ field: "ClientId", message: "must be non-empty", value });
    }
    if (!(value.length <= 20)) {
      return Err({ field: "ClientId", message: "length must be at most 20", value });
    }
    return Ok(value as ClientId);
  },
};

export type AuthId = string & { readonly __brand: "wire.auth.AuthId" };

export const AuthId = {
  of(value: string): Result<AuthId, ValidationError> {
    if (!(value.length > 0)) {
      return Err({ field: "AuthId", message: "must be non-empty", value });
    }
    return Ok(value as AuthId);
  },
  unsafe(value: string): AuthId {
    return value as AuthId;
  },
};

export interface Session {
  readonly client: ClientId;
  readonly auth: AuthId;
}

export const Session = {
};

export type LoginError =
    { readonly tag: "Invalid" };

export const LoginError = {
  Invalid: { tag: "Invalid" } as LoginError,
};

export const login = {
  /**
   * Mint a session for a seed. The single cross-context entry point.
   */
  async call(seed: string, deps: {}): Promise<Result<Session, LoginError>> {
    const __r0 = ClientId.of(seed);
    switch (__r0.tag) {
      case "Ok": {
        const c = __r0.value;
        return Ok({ client: c, auth: AuthId.unsafe(seed) });
      }
      case "Err": {
        return Err(LoginError.Invalid);
      }
    }
    throw new Error("non-exhaustive match");
  },
};

export function serialise_AuthId(value: AuthId): JsonValue {
  return value as unknown as string;
}

export function deserialise_AuthId(json: JsonValue, path: string = "$"): Result<AuthId, BoundaryError> {
  if (typeof json !== "string") {
    return Err({ kind: "StructuralMismatch", path, expected: "string", actual: typeof json });
  }
  const validated = (typeof (AuthId as any).of === "function")
    ? (AuthId as any).of(json)
    : Ok(json as unknown as AuthId);
  if (validated.tag === "Err") {
    return Err({ kind: "RefinementViolation", path, violation: validated.error });
  }
  return Ok(validated.value as AuthId);
}

export function serialise_ClientId(value: ClientId): JsonValue {
  return value as unknown as string;
}

export function deserialise_ClientId(json: JsonValue, path: string = "$"): Result<ClientId, BoundaryError> {
  if (typeof json !== "string") {
    return Err({ kind: "StructuralMismatch", path, expected: "string", actual: typeof json });
  }
  const validated = (typeof (ClientId as any).of === "function")
    ? (ClientId as any).of(json)
    : Ok(json as unknown as ClientId);
  if (validated.tag === "Err") {
    return Err({ kind: "RefinementViolation", path, violation: validated.error });
  }
  return Ok(validated.value as ClientId);
}

export function serialise_LoginError(value: LoginError): JsonValue {
  switch (value.tag) {
    case "Invalid":
      return { kind: "Invalid" };
  }
}

export function deserialise_LoginError(json: JsonValue, path: string = "$"): Result<LoginError, BoundaryError> {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: JsonValue };
  const kind = obj["kind"];
  switch (kind) {
    case "Invalid":
      return Ok({ tag: "Invalid" } as LoginError);
    default:
      return Err({ kind: "StructuralMismatch", path, expected: "sum variant kind", actual: String(kind) });
  }
}

export function serialise_Session(value: Session): JsonValue {
  return {
    client: serialise_ClientId(value.client),
    auth: serialise_AuthId(value.auth),
  };
}

export function deserialise_Session(json: JsonValue, path: string = "$"): Result<Session, BoundaryError> {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: JsonValue };
  const __r_client = deserialise_ClientId(obj["client"], `${path}.client`);
  if (__r_client.tag === "Err") return __r_client;
  const __client = __r_client.value;
  const __r_auth = deserialise_AuthId(obj["auth"], `${path}.auth`);
  if (__r_auth.tag === "Err") return __r_auth;
  const __auth = __r_auth.value;
  return Ok({ client: __client, auth: __auth } as Session);
}


export function serialise_Result_Session_LoginError(value: Result<Session, LoginError>): JsonValue {
  if (value.tag === "Ok") return { kind: "Ok", value: serialise_Session(value.value) };
  return { kind: "Err", error: serialise_LoginError(value.error) };
}

export function deserialise_Result_Session_LoginError(json: JsonValue, path: string = "$"): Result<Result<Session, LoginError>, BoundaryError> {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: JsonValue };
  if (obj["kind"] === "Ok") {
  const __r_v = deserialise_Session(obj["value"], `${path}.value`);
  if (__r_v.tag === "Err") return __r_v;
  const __v = __r_v.value;
    return Ok(Ok(__v) as Result<Session, LoginError>);
  } else if (obj["kind"] === "Err") {
  const __r_e = deserialise_LoginError(obj["error"], `${path}.error`);
  if (__r_e.tag === "Err") return __r_e;
  const __e = __r_e.value;
    return Ok(Err(__e) as Result<Session, LoginError>);
  }
  return Err({ kind: "StructuralMismatch", path, expected: "Ok | Err", actual: String(obj["kind"]) });
}

