// Generated by bynkc — do not edit by hand.
// test target: commerce.payment

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";
import * as commerce_payment from "./../commerce/payment.js";

class ExpectationError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number, detail: string) {
    super(`${detail}\n  at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkExpectFailure(location: string, start: number, end: number, detail: string) {
  return new ExpectationError(location, start, end, detail);
}
function __bynkExpect(cond: boolean, location: string, start: number, end: number, detail: string): void {
  if (!cond) { throw __bynkExpectFailure(location, start, end, detail); }
}
function __bynkShow(v: unknown): string {
  try { return typeof v === "bigint" ? String(v) : (JSON.stringify(v) ?? String(v)); } catch { return String(v); }
}

class __Stub_Logger {
  async log(msg: string): globalThis.Promise<void> {
    const { AuthId, PaymentError } = commerce_payment;
    type AuthId = commerce_payment.AuthId;
    type PaymentError = commerce_payment.PaymentError;
    if (true) {
      return undefined;
    }
    throw new globalThis.Error("bynk: no stub clause matched for Logger.log");
  }
}

function __bynkOverlay(base: unknown, stub: object, cap: string): unknown {
  return new globalThis.Proxy(stub, {
    get(target, prop) {
      const t = target as Record<PropertyKey, unknown> & { __applies?: (op: string) => boolean };
      // An own property (the stub's state, or a wrapper the recording proxy
      // installed) always answers; a stubbed operation answers when it applies
      // to the running case.
      if (globalThis.Object.prototype.hasOwnProperty.call(t, prop)) return t[prop];
      if (prop in t && (t.__applies === undefined || typeof prop !== "string" || t.__applies(prop))) return t[prop];
      if (base !== undefined) {
        const v = (base as Record<PropertyKey, unknown>)[prop];
        return typeof v === "function" ? v.bind(base) : v;
      }
      return () => {
        throw new globalThis.Error(`bynk: ${cap}.${String(prop)} is not stubbed, and the capability has no provider in this test`);
      };
    },
  });
}

function makeTestDeps() {
  return { Logger: __bynkOverlay(new commerce_payment.NoOpLogger(), new __Stub_Logger(), "Logger") as commerce_payment.Logger };
}

// case tier: unit
async function test_positive_amount_authorises() {
  try {
    const deps = makeTestDeps();
    const { AuthId, PaymentError, authorise } = commerce_payment;
    type AuthId = commerce_payment.AuthId;
    type PaymentError = commerce_payment.PaymentError;
    const result = await authorise.call(100, deps);
    if (!(result.tag === "Ok")) { throw __bynkExpectFailure("tests/payment.test.bynk:6:12", 145, 160, "expect result is Ok(_)"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_zero_amount_is_declined() {
  try {
    const deps = makeTestDeps();
    const { AuthId, PaymentError, authorise } = commerce_payment;
    type AuthId = commerce_payment.AuthId;
    type PaymentError = commerce_payment.PaymentError;
    const result = await authorise.call(0, deps);
    if (!(result.tag === "Err")) { throw __bynkExpectFailure("tests/payment.test.bynk:11:12", 248, 264, "expect result is Err(_)"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run(only?: string) {
  const results = [];
  const want = (n: string): boolean => only === undefined || only === n;
  if (want("positive amount authorises")) results.push({ name: "positive amount authorises", ...(await test_positive_amount_authorises()) });
  if (want("zero amount is declined")) results.push({ name: "zero amount is declined", ...(await test_zero_amount_is_declined()) });
  return results;
}
