// Generated by bynkc — do not edit by hand.
// test target: t.web

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, __bynkEq } from "../runtime.js";
import * as __ns_t_web from "./../t/web.js";
import * as __ns_t_core from "./../t/core.js";
import * as __ns_t_model from "./../t/model.js";

class ExpectationError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number, detail: string) {
    super(`${detail}\n  at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkExpectFailure(location: string, start: number, end: number, detail: string) {
  return new ExpectationError(location, start, end, detail);
}
function __bynkExpect(cond: boolean, location: string, start: number, end: number, detail: string): void {
  if (!cond) { throw __bynkExpectFailure(location, start, end, detail); }
}
function __bynkShow(v: unknown): string {
  try { return typeof v === "bigint" ? String(v) : (JSON.stringify(v) ?? String(v)); } catch { return String(v); }
}

function __makeTestDeps() {
  return {  };
}

// case tier: unit
async function test_a_suite_maps_a_reached_refined_field() {
  try {
    const deps = __makeTestDeps();
    const { api } = __ns_t_web;
    const { Run, first } = __ns_t_model;
    type Run = __ns_t_model.Run;
    const { Repo, Status } = __ns_t_core;
    type Repo = __ns_t_core.Repo;
    type Status = __ns_t_core.Status;
    const runs = [{ repo: ("a" as any), status: Status.Pending }, { repo: ("b" as any), status: Status.Done }];
    if (!(__bynkEq(((runs).map((__x: Run) => ((r) => r.repo)(__x))).map((__x: Repo) => ((n) => Repo.shout(n))(__x)), ["a!", "b!"]))) { throw __bynkExpectFailure("tests/t/web.bynk:9:10", 303, 364, "expect runs.map((r) => r.repo).map((n) => n.shout()) == [\"a!\", \"b!\"]\n  expected: runs.map((r) => r.repo).map((n) => n.shout()) == [\"a!\", \"b!\"]\n  actual:   " + __bynkShow((((runs).map((__x: Run) => ((r) => r.repo)(__x))).map((__x: Repo) => ((n) => Repo.shout(n))(__x)))) + " == " + __bynkShow((["a!", "b!"]))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_suite_reads_a_reached_field_through_an_imported_fn() {
  try {
    const deps = __makeTestDeps();
    const { api } = __ns_t_web;
    const { Run, first } = __ns_t_model;
    type Run = __ns_t_model.Run;
    const { Repo, Status } = __ns_t_core;
    type Repo = __ns_t_core.Repo;
    type Status = __ns_t_core.Status;
    const r = first([{ repo: ("x" as any), status: Status.Done }]);
    if (!(__bynkEq(((__o: Option<Repo>, __f: (x: Repo) => string) => __o.tag === "Some" ? Some(__f(__o.value)) : None)(r, (n) => Repo.shout(n)), Some("x!")))) { throw __bynkExpectFailure("tests/t/web.bynk:14:10", 490, 527, "expect r.map((n) => n.shout()) == Some(\"x!\")\n  expected: r.map((n) => n.shout()) == Some(\"x!\")\n  actual:   " + __bynkShow((((__o: Option<Repo>, __f: (x: Repo) => string) => __o.tag === "Some" ? Some(__f(__o.value)) : None)(r, (n) => Repo.shout(n)))) + " == " + __bynkShow((Some("x!")))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_suite_matches_a_reached_sum() {
  try {
    const deps = __makeTestDeps();
    const { api } = __ns_t_web;
    const { Run, first } = __ns_t_model;
    type Run = __ns_t_model.Run;
    const { Repo, Status } = __ns_t_core;
    type Repo = __ns_t_core.Repo;
    type Status = __ns_t_core.Status;
    const r = { repo: ("y" as any), status: Status.Done };
    const done = ((__d) => {
        switch (__d.tag) {
          case "Pending": {
            return false;
          }
          case "Done": {
            return true;
          }
        }
        throw new globalThis.Error("non-exhaustive match");
      })(r.status);
    if (!(done)) { throw __bynkExpectFailure("tests/t/web.bynk:23:10", 695, 699, "expect done"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run(only?: string) {
  const results = [];
  const want = (n: string): boolean => only === undefined || only === n;
  if (want("a suite maps a reached refined field")) results.push({ name: "a suite maps a reached refined field", ...(await test_a_suite_maps_a_reached_refined_field()) });
  if (want("a suite reads a reached field through an imported fn")) results.push({ name: "a suite reads a reached field through an imported fn", ...(await test_a_suite_reads_a_reached_field_through_an_imported_fn()) });
  if (want("a suite matches a reached sum")) results.push({ name: "a suite matches a reached sum", ...(await test_a_suite_matches_a_reached_sum()) });
  return results;
}
