// Generated by bynkc — do not edit by hand.
// commons app.bundle

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

import { LocaleTag, Message, MessageArg } from "../bynk/locale/types.js";
import { render as __bynkLocaleRender, renderArg } from "../bynk/locale.js";

const messagesByLocale: Record<string, Record<string, (params: ReadonlyMap<string, MessageArg>) => string>> = {
  /**
   * #899: a region-subtagged locale tag (`"pt-BR"`) is now declarable — the tag
   * is a `LocaleTag` string literal, not a bare identifier, so it flows through
   * to the emitted `messagesLocales` set and renders like any other locale. Before
   * #899, `messages pt-BR` was a parse error and `messagesLocales` could never
   * carry a subtag'd tag for `negotiateLocale`'s RFC 4647 filtering to match.
   */
  "en": {
    "greeting": (params: ReadonlyMap<string, MessageArg>): string => "Hello, " + (params.get("name") !== undefined ? renderArg(params.get("name") as MessageArg) : "{name}") + "!",
  },
  "pt-BR": {
    "greeting": (params: ReadonlyMap<string, MessageArg>): string => "Olá, " + (params.get("name") !== undefined ? renderArg(params.get("name") as MessageArg) : "{name}") + "!",
  },
};

export const messagesReferenceLocale: LocaleTag = ("en" as string) as LocaleTag;
export const messagesLocales: readonly LocaleTag[] = [("en" as string) as LocaleTag, ("pt-BR" as string) as LocaleTag];

export function render(tag: LocaleTag, msg: Message): string {
  const __localeTable = messagesByLocale[tag];
  const __referenceTable = messagesByLocale[messagesReferenceLocale];
  const __entry = (__localeTable !== undefined ? __localeTable[msg.code] : undefined) ?? __referenceTable[msg.code];
  if (__entry !== undefined) {
    return __entry(msg.params);
  }
  return __bynkLocaleRender(tag, msg);
}

