// Generated by bynkc — do not edit by hand.
// context demo.order

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type __DurableObjectState, type __DurableObjectNamespace, __StateRegistry, __makeAgent, __invariantViolation, __rehydrationViolation, type __JsonValue, type __BoundaryError, __bynkEq } from "../runtime.js";

export type AuthId = string & { readonly __brand: "demo.order.AuthId" };

export const AuthId = {
  of(value: string): Result<AuthId, ValidationError> {
    if (!(value.length > 0)) {
      return Err({ field: "AuthId", message: "must be non-empty", value });
    }
    return Ok(value as AuthId);
  },
};

export type OrderStatus =
    { readonly tag: "Pending" }
  | { readonly tag: "Paid" };

export const OrderStatus = {
  Pending: { tag: "Pending" } as OrderStatus,
  Paid: { tag: "Paid" } as OrderStatus,
};

export interface OrderState {
  readonly status: OrderStatus;
  readonly paymentRef: Option<AuthId>;
}

const __OrderRegistry = new __StateRegistry();
function __zeroOfOrderState(): OrderState { return { status: OrderStatus.Pending, paymentRef: None }; }

function __rehydrateOrderState(s: OrderState, stored: OrderState): void {
  if (globalThis.Object.prototype.hasOwnProperty.call(stored, "status")) { const __r = __deserialise_OrderStatus((s.status as unknown as __JsonValue), "status"); if (__r.tag === "Err") throw __rehydrationViolation("Order", __r.error); (s as { -readonly [K in keyof typeof s]: (typeof s)[K] }).status = __r.value as unknown as (typeof s)["status"]; }
  if (globalThis.Object.prototype.hasOwnProperty.call(stored, "paymentRef")) { const __r = __deserialise_Option_AuthId((s.paymentRef as unknown as __JsonValue), "paymentRef"); if (__r.tag === "Err") throw __rehydrationViolation("Order", __r.error); (s as { -readonly [K in keyof typeof s]: (typeof s)[K] }).paymentRef = __r.value as unknown as (typeof s)["paymentRef"]; }
}

function __encodeOrderState(s: OrderState): globalThis.Record<string, unknown> {
  return { ...s, status: __serialise_OrderStatus(s.status), paymentRef: __serialise_Option_AuthId(s.paymentRef) };
}

export class Order {
  state: __DurableObjectState;
  constructor(state: __DurableObjectState) {
    this.state = state;
  }

  private async loadState(): globalThis.Promise<OrderState> {
    const stored = await this.state.storage.get<OrderState>("state");
    if (stored === undefined) return __zeroOfOrderState();
    const __merged = { ...__zeroOfOrderState(), ...stored };
    __rehydrateOrderState(__merged, stored);
    return __merged;
  }

  private async commitState(s: OrderState): globalThis.Promise<void> {
    if (!((!(__bynkEq(s.status, OrderStatus.Paid)) || (s.paymentRef.tag === "Some")))) {
      globalThis.console.error("InvariantViolation Order.paid_has_payment_ref", { agent: "Order", invariant: "paid_has_payment_ref" });
      throw __invariantViolation("Order", "paid_has_payment_ref");
    }
    await this.state.storage.put("state", __encodeOrderState(s));
  }

  async pay(ref: AuthId, deps: {}): globalThis.Promise<void> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      __state.status = OrderStatus.Paid;
      __state.paymentRef = Some(ref);
      return undefined;
    })();
    await this.commitState(__state);
    return __result;
  }

}

export function __makeOrder(key: string, env?: { ORDER?: __DurableObjectNamespace }): Order {
  return __makeAgent(__OrderRegistry, env?.ORDER, key, (state) => new Order(state));
}

export function __resetAgents(): void {
  __OrderRegistry.reset();
}

export function __serialise_AuthId(value: AuthId): __JsonValue {
  return value as unknown as string;
}

export function __deserialise_AuthId(json: __JsonValue, path: string = "$"): Result<AuthId, __BoundaryError> {
  if (typeof json !== "string") {
    return Err({ kind: "StructuralMismatch", path, expected: "string", actual: typeof json });
  }
  const validated = (typeof (AuthId as unknown as { of?: (json: unknown) => Result<unknown, ValidationError> }).of === "function")
    ? (AuthId as unknown as { of: (json: unknown) => Result<unknown, ValidationError> }).of(json)
    : (Ok(json as unknown as AuthId) as Result<unknown, ValidationError>);
  if (validated.tag === "Err") {
    return Err({ kind: "RefinementViolation", path, violation: validated.error });
  }
  return Ok(validated.value as AuthId);
}

export function __serialise_OrderStatus(value: OrderStatus): __JsonValue {
  switch (value.tag) {
    case "Pending":
      return { kind: "Pending" };
    case "Paid":
      return { kind: "Paid" };
  }
}

export function __deserialise_OrderStatus(json: __JsonValue, path: string = "$"): Result<OrderStatus, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  const kind = obj["kind"];
  switch (kind) {
    case "Pending":
      return Ok({ tag: "Pending" } as OrderStatus);
    case "Paid":
      return Ok({ tag: "Paid" } as OrderStatus);
    default:
      return Err({ kind: "StructuralMismatch", path, expected: "sum variant kind", actual: String(kind) });
  }
}


export function __serialise_Option_AuthId(value: Option<AuthId>): __JsonValue {
  if (value.tag === "Some") return { kind: "Some", value: __serialise_AuthId(value.value) };
  return { kind: "None" };
}

function __option_value_AuthId(raw: __JsonValue, at: string): Result<unknown, __BoundaryError> {
  const __r_v = __deserialise_AuthId(raw, at);
  if (__r_v.tag === "Err") return __r_v;
  const __v = __r_v.value;
  return Ok(__v);
}

export function __deserialise_Option_AuthId(json: __JsonValue, path: string = "$"): Result<Option<AuthId>, __BoundaryError> {
  if (json === undefined || json === null) {
    return Ok(None as Option<AuthId>);
  }
  if (typeof json === "object" && !globalThis.Array.isArray(json)) {
    const obj = json as { [k: string]: __JsonValue };
    const __keys = globalThis.Object.keys(obj);
    if (obj["kind"] === "None" && __keys.length === 1) {
      return Ok(None as Option<AuthId>);
    }
    if (obj["kind"] === "Some" && __keys.length === 2 && "value" in obj) {
      const __t = __option_value_AuthId(obj["value"], `${path}.value`);
      if (__t.tag === "Err") {
        return __t;
      }
      return Ok(Some(__t.value as AuthId) as Option<AuthId>);
    }
  }
  const __b = __option_value_AuthId(json, path);
  if (__b.tag === "Ok") {
    return Ok(Some(__b.value as AuthId) as Option<AuthId>);
  }
  if (__b.error.kind === "StructuralMismatch" && __b.error.path === path) {
    return Err({ ...__b.error, expected: __b.error.expected + " | null | {\"kind\": \"None\"} | {\"kind\": \"Some\", \"value\": ...}" });
  }
  return __b;
}
