// Generated by bynkc — do not edit by hand.
// test target: demo.stubs

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";
import * as demo_stubs from "./../demo/stubs.js";

class ExpectationError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number, detail: string) {
    super(`${detail}\n  at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkExpectFailure(location: string, start: number, end: number, detail: string) {
  return new ExpectationError(location, start, end, detail);
}
function __bynkExpect(cond: boolean, location: string, start: number, end: number, detail: string): void {
  if (!cond) { throw __bynkExpectFailure(location, start, end, detail); }
}
function __bynkShow(v: unknown): string {
  try { return typeof v === "bigint" ? String(v) : (JSON.stringify(v) ?? String(v)); } catch { return String(v); }
}

class __Stub_Vault {
  __seq_0 = 0;
  __seq_1 = 0;
  __case: string | undefined;
  constructor(c?: string) {
    this.__case = c;
  }
  __applies(op: string): boolean {
    if (op === "peek") return this.__case === "a single-outcome returns each" || this.__case === "returns each ending in fails";
    return true;
  }
  async open(): globalThis.Promise<number> {
    if (true) {
      throw new globalThis.Error("bynk: injected capability fault (stubs … fails)");
    }
    throw new globalThis.Error("bynk: no stub clause matched for Vault.open");
  }
  async peek(): globalThis.Promise<number> {
    if (this.__case === "returns each ending in fails") {
      const __k = this.__seq_0;
      if (this.__seq_0 < 1) this.__seq_0++;
      switch (__k) {
        case 0: {
          return 1;
        }
        default: {
          throw new globalThis.Error("bynk: injected capability fault (stubs … fails)");
        }
      }
    }
    if (this.__case === "a single-outcome returns each") {
      const __k = this.__seq_1;
      switch (__k) {
        default: {
          return 42;
        }
      }
    }
    throw new globalThis.Error("bynk: no stub clause matched for Vault.peek");
  }
}

function __bynkOverlay(base: unknown, stub: object, cap: string): unknown {
  return new globalThis.Proxy(stub, {
    get(target, prop) {
      const t = target as Record<PropertyKey, unknown> & { __applies?: (op: string) => boolean };
      // An own property (the stub's state, or a wrapper the recording proxy
      // installed) always answers; a stubbed operation answers when it applies
      // to the running case.
      if (globalThis.Object.prototype.hasOwnProperty.call(t, prop)) return t[prop];
      if (prop in t && (t.__applies === undefined || typeof prop !== "string" || t.__applies(prop))) return t[prop];
      if (base !== undefined) {
        const v = (base as Record<PropertyKey, unknown>)[prop];
        return typeof v === "function" ? v.bind(base) : v;
      }
      return () => {
        throw new globalThis.Error(`bynk: ${cap}.${String(prop)} is not stubbed, and the capability has no provider in this test`);
      };
    },
  });
}

function __makeTestDeps(__case?: string) {
  return { Vault: __bynkOverlay(new demo_stubs.RealVault(), new __Stub_Vault(__case), "Vault") as demo_stubs.Vault };
}

// case tier: unit
async function test_a_direct_fails_clause() {
  try {
    const deps = __makeTestDeps();
    const { box } = demo_stubs;
    const r = await box.call(deps);
    if (!(true)) { throw __bynkExpectFailure("tests/stubs.test.bynk:11:12", 431, 435, "expect true"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_returns_each_ending_in_fails() {
  try {
    const deps = __makeTestDeps("returns each ending in fails");
    const { box } = demo_stubs;
    const r = await box.call(deps);
    if (!(true)) { throw __bynkExpectFailure("tests/stubs.test.bynk:17:12", 562, 566, "expect true"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_single_outcome_returns_each() {
  try {
    const deps = __makeTestDeps("a single-outcome returns each");
    const { box } = demo_stubs;
    const r = await box.call(deps);
    if (!(true)) { throw __bynkExpectFailure("tests/stubs.test.bynk:23:12", 688, 692, "expect true"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run(only?: string) {
  const results = [];
  const want = (n: string): boolean => only === undefined || only === n;
  if (want("a direct fails clause")) results.push({ name: "a direct fails clause", ...(await test_a_direct_fails_clause()) });
  if (want("returns each ending in fails")) results.push({ name: "returns each ending in fails", ...(await test_returns_each_ending_in_fails()) });
  if (want("a single-outcome returns each")) results.push({ name: "a single-outcome returns each", ...(await test_a_single_outcome_returns_each()) });
  return results;
}
