// Generated by bynkc — do not edit by hand.
// context gateway

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type Connection, type __DurableObjectState, type __DurableObjectNamespace, __StateRegistry, __makeAgent, type __AgentWire, __decodeAgentArgs, __encodeAgentResult, __AGENT_WIRE_PASS, __rehydrationViolation, __resolveConnection, __connIdOf, __acceptHibernatableConnection, __newWebSocketPair, __webSocketUpgradeResponse, HttpResult, QueueResult, type __JsonValue, type __BoundaryError, type __ServiceBinding, __callService, __boundaryError } from "../../runtime.js";

export type Tag = string & { readonly __brand: "gateway.Tag" };

export const Tag = {
  of(value: string): Result<Tag, ValidationError> {
    return Ok(value as Tag);
  },
  unsafe(value: string): Tag {
    return value as Tag;
  },
};

export type RoomId = string & { readonly __brand: "gateway.RoomId" };

export const RoomId = {
  of(value: string): Result<RoomId, ValidationError> {
    return Ok(value as RoomId);
  },
  unsafe(value: string): RoomId {
    return value as RoomId;
  },
};

export type UserId = string & { readonly __brand: "gateway.UserId" };

export const UserId = {
  of(value: string): Result<UserId, ValidationError> {
    return Ok(value as UserId);
  },
  unsafe(value: string): UserId {
    return value as UserId;
  },
};

export interface ServerFrame {
  readonly text: string;
}

export const ServerFrame = {
};

export interface ClientFrame {
  readonly text: string;
}

export const ClientFrame = {
};

export const echo = {
  async call(__id_void: string, deps: {}): globalThis.Promise<Result<string, void>> {
    return Ok(__id_void);
  },
};

export const registry = {
  async call(__id_class: string, __id_static: string, deps: {}): globalThis.Promise<Result<string, void>> {
    return Ok(__id_class);
  },
};

export const api = {
  async http_GET_lookup_Param_class(__id_class: string, deps: {}): globalThis.Promise<HttpResult<string>> {
    return HttpResult.Ok(__id_class);
  },
  async http_GET_tag_Param_public(__id_public: Tag, deps: {}): globalThis.Promise<HttpResult<string>> {
    return HttpResult.Ok("ok");
  },
  async http_GET_bearer_Param_delete(__id_delete: string, deps: { identity: UserId }): globalThis.Promise<HttpResult<string>> {
    return HttpResult.Ok(__id_delete);
  },
  async http_GET_oidc_Param_function(__id_function: string, deps: { identity: UserId }): globalThis.Promise<HttpResult<string>> {
    return HttpResult.Ok(__id_function);
  },
  async http_GET_sum_Param_import(__id_import: string, deps: { who: { tag: "Member", identity: UserId } | { tag: "Visitor" } }): globalThis.Promise<HttpResult<string>> {
    switch (deps.who.tag) {
      case "Member": {
        const m = deps.who.identity;
        return HttpResult.Ok(__id_import);
      }
      case "Visitor": {
        return HttpResult.Ok(__id_import);
      }
    }
    throw new globalThis.Error("non-exhaustive match");
  },
};

export const sweeper = {
  async cron_sweeper_0(__id_delete: number, deps: {}): globalThis.Promise<Result<void, void>> {
    return Ok(undefined);
  },
};

export const outbox = {
  async queue_outbox_0(__id_class: string, deps: {}): globalThis.Promise<QueueResult> {
    return QueueResult.Ack;
  },
};

export const ChatGateway = {
};

export interface RoomState {
  readonly conns: globalThis.Record<string, string>;
  readonly members: globalThis.Record<string, boolean>;
}

const __RoomRegistry = new __StateRegistry();
function __zeroOfRoomState(): RoomState { return { conns: {}, members: {} }; }

function __rehydrateRoomState(s: RoomState, stored: RoomState): void {
  for (const __k of globalThis.Object.keys(s.conns)) { const __r = __deserialise_UserId((__k as unknown as __JsonValue), "conns"); if (__r.tag === "Err") throw __rehydrationViolation("Room", __r.error); }
  for (const __k of globalThis.Object.keys(s.members)) { const __r = __deserialise_UserId((__k as unknown as __JsonValue), "members"); if (__r.tag === "Err") throw __rehydrationViolation("Room", __r.error); }
}

function __encodeRoomState(s: RoomState): globalThis.Record<string, unknown> {
  return { ...s };
}

export class Room {
  state: __DurableObjectState;
  constructor(state: __DurableObjectState) {
    this.state = state;
  }

  private async loadState(): globalThis.Promise<RoomState> {
    const stored = await this.state.storage.get<RoomState>("state");
    if (stored === undefined) return __zeroOfRoomState();
    const __merged = { ...__zeroOfRoomState(), ...stored };
    __rehydrateRoomState(__merged, stored);
    return __merged;
  }

  private async commitState(s: RoomState): globalThis.Promise<void> {
    await this.state.storage.put("state", __encodeRoomState(s));
  }

  async join(u: UserId, conn: Connection<ServerFrame>, deps: {}): globalThis.Promise<void> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = await (globalThis.Object.defineProperty(__state.members, u, { value: true, writable: true, enumerable: true, configurable: true }), undefined);
      const __r1 = await (globalThis.Object.defineProperty(__state.conns, String(u), { value: __connIdOf(conn), writable: true, enumerable: true, configurable: true }), undefined);
      return undefined;
    })();
    await this.commitState(__state);
    return __result;
  }

  async __wsOpen_ChatGateway(connection: Connection<ServerFrame>, __id_export: RoomId, deps: { identity: UserId }): globalThis.Promise<void> {
    const __r0 = await this.join(deps.identity, connection, deps);
    return undefined;
  }

  async fetch(request: globalThis.Request): globalThis.Promise<globalThis.Response> {
    const url = new globalThis.URL(request.url);
    if (url.pathname === "/_bynk/ws/open/ChatGateway") {
      const __pair = __newWebSocketPair();
      const __payload = globalThis.JSON.parse(request.headers.get("X-Bynk-Ws-Open") ?? "{}") as { args: unknown[]; identity: string };
      const connection = __acceptHibernatableConnection<ServerFrame>(this.state, __pair.server);
      await this.__wsOpen_ChatGateway(connection, __payload.args[0] as RoomId, { identity: __payload.identity as UserId });
      return __webSocketUpgradeResponse(__pair.client);
    }
    if (url.pathname.startsWith("/_bynk/agent/")) {
      const methodName = url.pathname.slice("/_bynk/agent/".length);
      const { args, deps } = (await request.json()) as { args: unknown[]; deps: unknown };
      const result = await (this as unknown as globalThis.Record<string, (...bynkArgs: unknown[]) => unknown>)[methodName](...__decodeAgentArgs(__RoomWire, methodName, args), deps);
      return new globalThis.Response(globalThis.JSON.stringify(__encodeAgentResult(__RoomWire, methodName, result)), { headers: { "content-type": "application/json" } });
    }
    return new globalThis.Response("Not Found", { status: 404 });
  }

}

const __RoomWire: __AgentWire = {
  join: { args: [{ enc: __serialise_UserId, dec: __deserialise_UserId }, __AGENT_WIRE_PASS], result: { enc: (__v: void) => null, dec: (__j: __JsonValue) => Ok(undefined) as Result<void, __BoundaryError> } },
};

export function __makeRoom(key: RoomId, env?: { ROOM?: __DurableObjectNamespace }): Room {
  return __makeAgent(__RoomRegistry, env?.ROOM, key, (state) => new Room(state), __RoomWire);
}

export function __resetAgents(): void {
  __RoomRegistry.reset();
}

export function __serialise_RoomId(value: RoomId): __JsonValue {
  return value as unknown as string;
}

export function __deserialise_RoomId(json: __JsonValue, path: string = "$"): Result<RoomId, __BoundaryError> {
  if (typeof json !== "string") {
    return Err({ kind: "StructuralMismatch", path, expected: "string", actual: typeof json });
  }
  const validated = (typeof (RoomId as unknown as { of?: (json: unknown) => Result<unknown, ValidationError> }).of === "function")
    ? (RoomId as unknown as { of: (json: unknown) => Result<unknown, ValidationError> }).of(json)
    : (Ok(json as unknown as RoomId) as Result<unknown, ValidationError>);
  if (validated.tag === "Err") {
    return Err({ kind: "RefinementViolation", path, violation: validated.error });
  }
  return Ok(validated.value as RoomId);
}

export function __serialise_Tag(value: Tag): __JsonValue {
  return value as unknown as string;
}

export function __deserialise_Tag(json: __JsonValue, path: string = "$"): Result<Tag, __BoundaryError> {
  if (typeof json !== "string") {
    return Err({ kind: "StructuralMismatch", path, expected: "string", actual: typeof json });
  }
  const validated = (typeof (Tag as unknown as { of?: (json: unknown) => Result<unknown, ValidationError> }).of === "function")
    ? (Tag as unknown as { of: (json: unknown) => Result<unknown, ValidationError> }).of(json)
    : (Ok(json as unknown as Tag) as Result<unknown, ValidationError>);
  if (validated.tag === "Err") {
    return Err({ kind: "RefinementViolation", path, violation: validated.error });
  }
  return Ok(validated.value as Tag);
}

export function __serialise_UserId(value: UserId): __JsonValue {
  return value as unknown as string;
}

export function __deserialise_UserId(json: __JsonValue, path: string = "$"): Result<UserId, __BoundaryError> {
  if (typeof json !== "string") {
    return Err({ kind: "StructuralMismatch", path, expected: "string", actual: typeof json });
  }
  const validated = (typeof (UserId as unknown as { of?: (json: unknown) => Result<unknown, ValidationError> }).of === "function")
    ? (UserId as unknown as { of: (json: unknown) => Result<unknown, ValidationError> }).of(json)
    : (Ok(json as unknown as UserId) as Result<unknown, ValidationError>);
  if (validated.tag === "Err") {
    return Err({ kind: "RefinementViolation", path, violation: validated.error });
  }
  return Ok(validated.value as UserId);
}


export function __serialise_Result_String_Unit(value: Result<string, void>): __JsonValue {
  if (value.tag === "Ok") return { kind: "Ok", value: value.value as __JsonValue };
  return { kind: "Err", error: null };
}

export function __deserialise_Result_String_Unit(json: __JsonValue, path: string = "$"): Result<Result<string, void>, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  if (obj["kind"] === "Ok") {
  if (typeof obj["value"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.value`, expected: "string", actual: typeof obj["value"] });
  }
  const __v = obj["value"];
    return Ok(Ok(__v) as Result<string, void>);
  } else if (obj["kind"] === "Err") {
  const __e = undefined;
    return Ok(Err(__e) as Result<string, void>);
  }
  return Err({ kind: "StructuralMismatch", path, expected: "Ok | Err", actual: String(obj["kind"]) });
}

export function __serialise_Result_Unit_Unit(value: Result<void, void>): __JsonValue {
  if (value.tag === "Ok") return { kind: "Ok", value: null };
  return { kind: "Err", error: null };
}

export function __deserialise_Result_Unit_Unit(json: __JsonValue, path: string = "$"): Result<Result<void, void>, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  if (obj["kind"] === "Ok") {
  const __v = undefined;
    return Ok(Ok(__v) as Result<void, void>);
  } else if (obj["kind"] === "Err") {
  const __e = undefined;
    return Ok(Err(__e) as Result<void, void>);
  }
  return Err({ kind: "StructuralMismatch", path, expected: "Ok | Err", actual: String(obj["kind"]) });
}

