// Generated by bynkc — do not edit by hand.
// Worker entry point for context `gateway`.

import { Ok, Err, type Result, type __JsonValue, type __BoundaryError, __boundaryError, __matchPath, __httpResultToResponse, __headResponse, __notModifiedIfMatch, type __SecurityPolicy, __applySecurityHeaders } from "../../runtime.js";
import { compose, type Env } from "./compose.js";
import * as handlers from "./handlers.js";

export { Room } from "./handlers.js";

export default {
  async fetch(request: globalThis.Request, env: Env): globalThis.Promise<globalThis.Response> {
    const url = new globalThis.URL(request.url);
    const path = url.pathname;
    const method = request.method;
    const surface = compose(env);
    const __security_api: __SecurityPolicy = { nosniff: true, hstsMaxAgeSecs: null };
    let __route: string = "request";
    try {
      if (path.startsWith("/_bynk/call/")) {
        const servicePath = path.slice("/_bynk/call/".length);
        switch (servicePath) {
          case "echo": {
            __route = "call echo";
            const __contract = request.headers.get("X-Bynk-Contract");
            if (__contract !== "d99db46e9a4cfb5e") {
              globalThis.console.error("ContractMismatch gateway call echo", { service: "echo", expected: "d99db46e9a4cfb5e", actual: __contract });
              return new globalThis.Response(globalThis.JSON.stringify({ kind: "ContractMismatch", service: "echo", expected: "d99db46e9a4cfb5e", actual: __contract }), { status: 409, headers: { "content-type": "application/json" } });
            }
            const args = await request.json() as __JsonValue;
            const __r_void = ((__v) => typeof __v === "string" ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "$", expected: "string", actual: typeof __v } as __BoundaryError))(args);
            if (__r_void.tag === "Err") return new globalThis.Response(globalThis.JSON.stringify(__r_void.error), { status: 400, headers: { "content-type": "application/json" } });
            const __id_void = __r_void.value;
            const result = await surface.echo(__id_void);
            const body = handlers.__serialise_Result_String_Unit(result);
            return new globalThis.Response(globalThis.JSON.stringify(body), { status: 200, headers: { "content-type": "application/json" } });
          }
          case "registry": {
            __route = "call registry";
            const __contract = request.headers.get("X-Bynk-Contract");
            if (__contract !== "4410b6f9918570a9") {
              globalThis.console.error("ContractMismatch gateway call registry", { service: "registry", expected: "4410b6f9918570a9", actual: __contract });
              return new globalThis.Response(globalThis.JSON.stringify({ kind: "ContractMismatch", service: "registry", expected: "4410b6f9918570a9", actual: __contract }), { status: 409, headers: { "content-type": "application/json" } });
            }
            const args = await request.json() as __JsonValue;
            if (typeof args !== "object" || args === null || globalThis.Array.isArray(args)) return new globalThis.Response(globalThis.JSON.stringify({ kind: "StructuralMismatch", path: "$", expected: "object", actual: typeof args }), { status: 400, headers: { "content-type": "application/json" } });
            const argsObj = args as { [k: string]: __JsonValue };
            const __r_class = ((__v) => typeof __v === "string" ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "$.class", expected: "string", actual: typeof __v } as __BoundaryError))(argsObj["class"]);
            if (__r_class.tag === "Err") return new globalThis.Response(globalThis.JSON.stringify(__r_class.error), { status: 400, headers: { "content-type": "application/json" } });
            const __id_class = __r_class.value;
            const __r_static = ((__v) => typeof __v === "string" ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "$.static", expected: "string", actual: typeof __v } as __BoundaryError))(argsObj["static"]);
            if (__r_static.tag === "Err") return new globalThis.Response(globalThis.JSON.stringify(__r_static.error), { status: 400, headers: { "content-type": "application/json" } });
            const __id_static = __r_static.value;
            const result = await surface.registry(__id_class, __id_static);
            const body = handlers.__serialise_Result_String_Unit(result);
            return new globalThis.Response(globalThis.JSON.stringify(body), { status: 200, headers: { "content-type": "application/json" } });
          }
          default:
            return new globalThis.Response("Not found", { status: 404 });
        }
      }

      if (request.headers.get("Upgrade") === "websocket") {
        const __ws_export = url.searchParams.get("export");
        if (__ws_export === null) return new globalThis.Response("Missing parameter: export", { status: 400 });
        return surface.ws_ChatGateway_open(request, __ws_export);
      }

      {
        const __m = __matchPath("/bearer/:delete", path);
        if ((method === "GET" || method === "HEAD") && __m) {
          __route = "GET /bearer/:delete";
          const __raw_delete = __m.params["delete"];
          const __id_delete = __raw_delete;
          const result = await surface.http_GET_bearer_Param_delete(request, __id_delete);
          const __response = __applySecurityHeaders(__notModifiedIfMatch(__httpResultToResponse(result, (__v: string) => __v as __JsonValue, { weakEtag: true }), request), __security_api);
          return method === "HEAD" ? __headResponse(__response) : __response;
        }
      }
      {
        const __m = __matchPath("/lookup/:class", path);
        if ((method === "GET" || method === "HEAD") && __m) {
          __route = "GET /lookup/:class";
          const __raw_class = __m.params["class"];
          const __id_class = __raw_class;
          const result = await surface.http_GET_lookup_Param_class(__id_class);
          const __response = __applySecurityHeaders(__notModifiedIfMatch(__httpResultToResponse(result, (__v: string) => __v as __JsonValue, { weakEtag: true }), request), __security_api);
          return method === "HEAD" ? __headResponse(__response) : __response;
        }
      }
      {
        const __m = __matchPath("/oidc/:function", path);
        if ((method === "GET" || method === "HEAD") && __m) {
          __route = "GET /oidc/:function";
          const __raw_function = __m.params["function"];
          const __id_function = __raw_function;
          const result = await surface.http_GET_oidc_Param_function(request, __id_function);
          const __response = __applySecurityHeaders(__notModifiedIfMatch(__httpResultToResponse(result, (__v: string) => __v as __JsonValue, { weakEtag: true }), request), __security_api);
          return method === "HEAD" ? __headResponse(__response) : __response;
        }
      }
      {
        const __m = __matchPath("/sum/:import", path);
        if ((method === "GET" || method === "HEAD") && __m) {
          __route = "GET /sum/:import";
          const __raw_import = __m.params["import"];
          const __id_import = __raw_import;
          const result = await surface.http_GET_sum_Param_import(request, __id_import);
          const __response = __applySecurityHeaders(__notModifiedIfMatch(__httpResultToResponse(result, (__v: string) => __v as __JsonValue, { weakEtag: true }), request), __security_api);
          return method === "HEAD" ? __headResponse(__response) : __response;
        }
      }
      {
        const __m = __matchPath("/tag/:public", path);
        if ((method === "GET" || method === "HEAD") && __m) {
          __route = "GET /tag/:public";
          const __raw_public = __m.params["public"];
          const __r_public = handlers.Tag.of(__raw_public);
          if (__r_public.tag === "Err") return __applySecurityHeaders(new globalThis.Response(globalThis.JSON.stringify({ kind: "RefinementViolation", path: "path.public", violation: __r_public.error }), { status: 400, headers: { "content-type": "application/json" } }), __security_api);
          const __id_public = __r_public.value;
          const result = await surface.http_GET_tag_Param_public(__id_public);
          const __response = __applySecurityHeaders(__notModifiedIfMatch(__httpResultToResponse(result, (__v: string) => __v as __JsonValue, { weakEtag: true }), request), __security_api);
          return method === "HEAD" ? __headResponse(__response) : __response;
        }
      }
      if (__matchPath("/bearer/:delete", path) !== null) {
        const __status = method === "OPTIONS" ? 204 : 405;
        const __res = new globalThis.Response(null, { status: __status, headers: { allow: "GET, HEAD, OPTIONS" } });
        return __applySecurityHeaders(__res, __security_api);
      }
      if (__matchPath("/lookup/:class", path) !== null) {
        const __status = method === "OPTIONS" ? 204 : 405;
        const __res = new globalThis.Response(null, { status: __status, headers: { allow: "GET, HEAD, OPTIONS" } });
        return __applySecurityHeaders(__res, __security_api);
      }
      if (__matchPath("/oidc/:function", path) !== null) {
        const __status = method === "OPTIONS" ? 204 : 405;
        const __res = new globalThis.Response(null, { status: __status, headers: { allow: "GET, HEAD, OPTIONS" } });
        return __applySecurityHeaders(__res, __security_api);
      }
      if (__matchPath("/sum/:import", path) !== null) {
        const __status = method === "OPTIONS" ? 204 : 405;
        const __res = new globalThis.Response(null, { status: __status, headers: { allow: "GET, HEAD, OPTIONS" } });
        return __applySecurityHeaders(__res, __security_api);
      }
      if (__matchPath("/tag/:public", path) !== null) {
        const __status = method === "OPTIONS" ? 204 : 405;
        const __res = new globalThis.Response(null, { status: __status, headers: { allow: "GET, HEAD, OPTIONS" } });
        return __applySecurityHeaders(__res, __security_api);
      }
      return new globalThis.Response("Not Found", { status: 404 });
    } catch (e) {
      globalThis.console.error(`gateway ${__route} faulted`, e);
      return new globalThis.Response("Internal Server Error", { status: 500 });
    }
  },
  async scheduled(event: { readonly cron: string; readonly scheduledTime: number }, env: Env): globalThis.Promise<void> {
    const surface = compose(env);
    switch (event.cron) {
      case "*/5 * * * *": {
        const result = await surface.cron_sweeper_0(event.scheduledTime);
        if (result.tag === "Err") globalThis.console.error("cron */5 * * * * failed", result.error);
        return;
      }
      default:
        return;
    }
  },
  async queue(batch: { readonly queue: string; readonly messages: ReadonlyArray<{ readonly body: unknown; ack(): void; retry(): void }> }, env: Env): globalThis.Promise<void> {
    const surface = compose(env);
    switch (batch.queue) {
      case "jobs": {
        for (const msg of batch.messages) {
          try {
            const __r = ((__v) => typeof __v === "string" ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "$", expected: "string", actual: typeof __v } as __BoundaryError))((msg.body as __JsonValue));
            if (__r.tag === "Err") { globalThis.console.error("queue jobs deserialise failed", __r.error); msg.retry(); continue; }
            const result = await surface.queue_outbox_0(__r.value);
            if (result.tag === "Ack") msg.ack();
            else { globalThis.console.error("queue jobs retry", result.reason); msg.retry(); }
          } catch (e) {
            globalThis.console.error("queue jobs threw", e); msg.retry();
          }
        }
        return;
      }
      default:
        return;
    }
  },
};
