// Generated by bynkc — do not edit by hand.
// composition root for `api` Worker.

import { type ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";

export interface Env {
}

export function compose(env: Env) {
  const Logger = new handlers.ConsoleLogger();
  const deps = { Logger };
  return {
    async http_GET_a() {
      return handlers.api.http_GET_a(deps);
    },
    async http_GET_b() {
      return handlers.api.http_GET_b(deps);
    },
  };
}
