// Generated by bynkc — do not edit by hand.
// context docs.gateway

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

import { Doc as __CommonsDoc } from "./model.js";

import * as docs_archive from "./archive.js";

export type Doc = __CommonsDoc & { readonly __ctxBrand?: "docs.gateway" };

export const submit = {
  async call(d: Doc, deps: { surface: { archive: globalThis.ReturnType<typeof docs_archive.__makeSurface> } }): globalThis.Promise<Result<number, void>> {
    const n = await deps.surface.archive.intake((d as unknown as docs_archive.Doc));
    return n;
  },
};

export interface __DocsGatewayDeps {
  readonly surface: { archive: globalThis.ReturnType<typeof docs_archive.__makeSurface> };
}

export function __makeSurface(deps: __DocsGatewayDeps) {
  return {
    async submit(d: Doc): globalThis.Promise<Result<number, void>> {
      return submit.call(d, deps);
    },
  };
}

