// Generated by karnc — do not edit by hand.
// context commerce.orders

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

import { AuthId } from "./payment.js";

import * as commerce_payment from "./payment.js";

export type OrderError =
    { readonly tag: "PaymentDeclined" }
  | { readonly tag: "PaymentInsufficient" };

export const OrderError = {
  PaymentDeclined: { tag: "PaymentDeclined" } as OrderError,
  PaymentInsufficient: { tag: "PaymentInsufficient" } as OrderError,
};

export const place = {
  async call(amount: number, deps: { surface: { Payment: ReturnType<typeof commerce_payment.makeSurface> } }): Promise<Result<AuthId, OrderError>> {
    const auth = await deps.surface.Payment.authorise(amount);
    switch (auth.tag) {
      case "Ok": {
        const id = auth.value;
        return Promise.resolve(Ok(id));
      }
      case "Err": {
        const error = auth.error;
        return ((__d) => {
    switch (__d.tag) {
      case "Declined": {
        return Promise.resolve(Err(OrderError.PaymentDeclined));
      }
      case "InsufficientFunds": {
        return Promise.resolve(Err(OrderError.PaymentInsufficient));
      }
    }
    throw new Error("non-exhaustive match");
  })(error);
      }
    }
    throw new Error("non-exhaustive match");
  },
};

