// Generated by bynkc — do not edit by hand.
// commons boxes

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export interface Box<A> {
  readonly value: A;
}

export const Box = {
  map<A, U>(self: Box<A>, f: (a0: A) => U): Box<U> {
    return { value: f(self.value) };
  },
  get<A>(self: Box<A>): A {
    return self.value;
  },
};

export function label(b: Box<number>): Box<string> {
  return Box.map(b, (n) => "boxed");
}

export function label_len(b: Box<number>): number {
  return (Box.get(Box.map(b, (n) => "boxed"))).length;
}

export function first(b: Box<readonly number[]>): Option<number> {
  return ((__xs: readonly number[]) => __xs.length > 0 ? Some(__xs[0]) : None)(Box.get(b));
}

