// Generated by bynkc — do not edit by hand.
// commons app.bundle

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

import { message } from "../bynk/locale.js";
import { LocaleTag, Message } from "../bynk/locale/types.js";
import { render as __bynkLocaleRender, renderArg as __bynkRenderArg } from "../bynk/locale.js";
import type { LocaleTag as __bynkLocaleTag, Message as __bynkMessage, MessageArg as __bynkMessageArg } from "../bynk/locale/types.js";

export function greet(tag: LocaleTag): string {
  return render(tag, message("greeting"));
}

const __messagesByLocale: globalThis.Record<string, globalThis.Record<string, (params: ReadonlyMap<string, __bynkMessageArg>) => string>> = {
  /**
   * Locale-negotiation-slice-2 follow-up (#886): the actual scenario slice 2
   * (#882) could never build under one `uses`-clause name collision — a
   * context calling `Locale.current()` (needing `LocaleTag`) and a context
   * `uses`-ing a message-bundle commons (whose synthetic `render` collided
   * with `bynk.locale`'s own) could never coexist. `bynk.locale`'s split into
   * this leaf (`bynk.locale.types`, carrying just the types) plus the
   * value-level `bynk.locale` closes that gap: a consuming context now only
   * ever needs `bynk.locale.types` directly (see `app.web` below), reaching
   * `render`/`message` exclusively through this wrapper — never through its
   * own `uses bynk.locale`, so the collision has nothing left to collide on.
   */
  "en": {
    "greeting": (params: ReadonlyMap<string, __bynkMessageArg>): string => "Hello",
  },
};

export const __messagesReferenceLocale: __bynkLocaleTag = ("en" as string) as __bynkLocaleTag;
export const __messagesLocales: readonly __bynkLocaleTag[] = [("en" as string) as __bynkLocaleTag];

export function render(tag: __bynkLocaleTag, msg: __bynkMessage): string {
  const __localeTable = __messagesByLocale[tag];
  const __referenceTable = __messagesByLocale[__messagesReferenceLocale];
  const __entry = (__localeTable !== undefined ? __localeTable[msg.code] : undefined) ?? __referenceTable[msg.code];
  if (__entry !== undefined) {
    return __entry(msg.params);
  }
  return __bynkLocaleRender(tag, msg);
}
