// Generated by bynkc — do not edit by hand.
// commons app.bundle

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

import { LocaleTag, Message, MessageArg } from "../bynk/locale/types.js";
import { render as __bynkLocaleRender, renderArg } from "../bynk/locale.js";

const messagesByLocale: Record<string, Record<string, (params: ReadonlyMap<string, MessageArg>) => string>> = {
  /**
   * message-bundles track, slice 1 (#859): multiple `messages` blocks in one
   * commons are legal (forward-compatible with slice 2's multi-locale
   * model) as long as exactly one carries `@reference`. Slice 1 emits
   * exactly one `export function render`, built only from the reference
   * block's entries — a non-reference block is checker-validated but
   * contributes nothing to codegen yet (review finding on PR #872: a
   * second block used to emit a second, colliding `export function
   * render`).
   */
  "en": {
    "greeting": (params: ReadonlyMap<string, MessageArg>): string => "Hello, " + (params.get("name") !== undefined ? renderArg(params.get("name") as MessageArg) : "{name}") + "!",
  },
  "fr": {
    "greeting": (params: ReadonlyMap<string, MessageArg>): string => "Bonjour, " + (params.get("name") !== undefined ? renderArg(params.get("name") as MessageArg) : "{name}") + "!",
  },
};

export const messagesReferenceLocale: LocaleTag = ("en" as string) as LocaleTag;
export const messagesLocales: readonly LocaleTag[] = [("en" as string) as LocaleTag, ("fr" as string) as LocaleTag];

export function render(tag: LocaleTag, msg: Message): string {
  const __localeTable = messagesByLocale[tag];
  const __referenceTable = messagesByLocale[messagesReferenceLocale];
  const __entry = (__localeTable !== undefined ? __localeTable[msg.code] : undefined) ?? __referenceTable[msg.code];
  if (__entry !== undefined) {
    return __entry(msg.params);
  }
  return __bynkLocaleRender(tag, msg);
}

