// Generated by bynkc — do not edit by hand.
// commons shop.values

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

export type Money = number & { readonly __brand: "Money" };

export const Money = {
  of(value: number): Result<Money, ValidationError> {
    if (!globalThis.Number.isSafeInteger(value)) {
      return Err({ field: "Money", message: "must be a safe integer", value });
    }
    if (!(value > 0)) {
      return Err({ field: "Money", message: "must be positive", value });
    }
    return Ok(value as Money);
  },
};

export interface Note {
  readonly text: string;
}

export const Note = {
};
