// Generated by bynkc — do not edit by hand.
// composition root for `shop.orders` Worker.

import { type __ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";
import * as handlers_shop_fees from "../shop-fees/handlers.js";

export interface Env {
  SHOP_FEES: __ServiceBinding;
  SHOP_PAYMENT: __ServiceBinding;
  BOOK: __DurableObjectNamespace;
  TALLY: __DurableObjectNamespace;
}

type __DurableObjectNamespace = { idFromName(name: string): { toString(): string }; get(id: any): any };

export function compose(env: Env) {
  const Fees = new handlers_shop_fees.FlatFees();
  const Stamp = new handlers.FixedStamp();
  const deps = { Fees, Stamp, env };
  return {
    async hits() {
      return handlers.hits.call(deps);
    },
    async place(line: handlers.Line) {
      return handlers.place.call(line, deps);
    },
  };
}
