// Generated by bynkc — do not edit by hand.
// Worker entry point for context `shop.orders`.

import { Ok, Err, type Result, type __JsonValue, type __BoundaryError, __boundaryError } from "../../runtime.js";
import { compose, type Env } from "./compose.js";
import * as handlers from "./handlers.js";

export { Book, Tally } from "./handlers.js";

export default {
  async fetch(request: globalThis.Request, env: Env): globalThis.Promise<globalThis.Response> {
    const url = new globalThis.URL(request.url);
    const path = url.pathname;
    const method = request.method;
    const surface = compose(env);
    try {
      if (path.startsWith("/_bynk/call/")) {
        const servicePath = path.slice("/_bynk/call/".length);
        switch (servicePath) {
          case "hits": {
            const __contract = request.headers.get("X-Bynk-Contract");
            if (__contract !== "295c6455d9ef7692") return new globalThis.Response(globalThis.JSON.stringify({ kind: "ContractMismatch", service: "hits", expected: "295c6455d9ef7692", actual: __contract }), { status: 409, headers: { "content-type": "application/json" } });
            const args = await request.json() as __JsonValue;
            if (typeof args !== "object" || args === null || globalThis.Array.isArray(args)) return new globalThis.Response(globalThis.JSON.stringify({ kind: "StructuralMismatch", path: "$", expected: "object", actual: typeof args }), { status: 400, headers: { "content-type": "application/json" } });
            const argsObj = args as { [k: string]: __JsonValue };
            const result = await surface.hits();
            const body = ((v: number) => { if (!globalThis.Number.isSafeInteger(v)) throw new globalThis.Error("Int outside the safe-integer range at boundary"); return v as __JsonValue; })(result);
            return new globalThis.Response(globalThis.JSON.stringify(body), { status: 200, headers: { "content-type": "application/json" } });
          }
          case "place": {
            const __contract = request.headers.get("X-Bynk-Contract");
            if (__contract !== "79c966765bfd2c72") return new globalThis.Response(globalThis.JSON.stringify({ kind: "ContractMismatch", service: "place", expected: "79c966765bfd2c72", actual: __contract }), { status: 409, headers: { "content-type": "application/json" } });
            const args = await request.json() as __JsonValue;
            const __r_line = handlers.__deserialise_Line(args, "$");
            if (__r_line.tag === "Err") return new globalThis.Response(globalThis.JSON.stringify(__r_line.error), { status: 400, headers: { "content-type": "application/json" } });
            const line = __r_line.value;
            const result = await surface.place(line);
            const body = ((v: number) => { if (!globalThis.Number.isSafeInteger(v)) throw new globalThis.Error("Int outside the safe-integer range at boundary"); return v as __JsonValue; })(result);
            return new globalThis.Response(globalThis.JSON.stringify(body), { status: 200, headers: { "content-type": "application/json" } });
          }
          default:
            return new globalThis.Response("Not found", { status: 404 });
        }
      }

      return new globalThis.Response("Not Found", { status: 404 });
    } catch {
      return new globalThis.Response("Internal Server Error", { status: 500 });
    }
  },
};
