// Generated by bynkc — do not edit by hand.
// test target: demo.registry

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";
import * as demo_registry from "./../demo/registry.js";

class ExpectationError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number, detail: string) {
    super(`${detail}\n  at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkExpectFailure(location: string, start: number, end: number, detail: string) {
  return new ExpectationError(location, start, end, detail);
}
function __bynkExpect(cond: boolean, location: string, start: number, end: number, detail: string): void {
  if (!cond) { throw __bynkExpectFailure(location, start, end, detail); }
}
function __bynkShow(v: unknown): string {
  try { return typeof v === "bigint" ? String(v) : (JSON.stringify(v) ?? String(v)); } catch { return String(v); }
}

function __bynkDeepEqual(a: unknown, b: unknown): boolean {
  const s = (v: unknown) => JSON.stringify(v, (_k, val) => typeof val === "bigint" ? "__bigint__" + String(val) : val);
  try { return s(a) === s(b); } catch { return a === b; }
}

class __Provides_Clock {
  async now(): Promise<number> {
    const { Code, RegError, Target } = demo_registry as any;
    if (true) {
      return 7;
    }
    throw new Error("bynk: no provides clause matched for Clock.now");
  }
}

function makeTestDeps() {
  return { Clock: new __Provides_Clock() };
}

// case tier: unit
async function test_create_accepts_two_args_and_threads_deps() {
  try {
    const deps = makeTestDeps();
    const { Code, RegError, Target, create } = demo_registry as any;
    void (await (async (__d) => {
        switch (__d.tag) {
          case "Err": {
            return __bynkExpect((false), "tests/demo/registry.bynk:11:20", 255, 260, "expect false");
          }
          case "Ok": {
            const code = __d.value;
            return await (async (__d) => {
        switch (__d.tag) {
          case "Err": {
            return __bynkExpect((false), "tests/demo/registry.bynk:13:21", 336, 341, "expect false");
          }
          case "Ok": {
            const target = __d.value;
            const outcome = await create.call(code, target, deps);
            switch (outcome.tag) {
              case "Ok": {
                const t = outcome.value;
                return __bynkExpect((t === 7), "tests/demo/registry.bynk:17:23", 448, 454, "expect t == 7");
              }
              case "Err": {
                return __bynkExpect((false), "tests/demo/registry.bynk:18:23", 477, 482, "expect false");
              }
            }
            throw new Error("non-exhaustive match");
          }
        }
        throw new Error("non-exhaustive match");
      })(Target.of("https://example.com"));
          }
        }
        throw new Error("non-exhaustive match");
      })(Code.of("abc123")));
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run() {
  const results = [];
  results.push({ name: "create accepts two args and threads deps", ...(await test_create_accepts_two_args_and_threads_deps()) });
  return results;
}
