// Generated by karnc — do not edit by hand.
// composition root for `commerce.orders` Worker.

import { type ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";

export interface Env {
  COMMERCE_PAYMENT: ServiceBinding;
}

export function compose(env: Env) {
  const deps = { env };
  return {
    async orders(total: any) {
      return handlers.orders.call(total, deps);
    },
    async http_POST_orders(body: any) {
      return handlers.orders.http_POST_orders(body, deps);
    },
  };
}
