// Generated by bynkc — do not edit by hand.
// context canvas

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type __DurableObjectState, type __DurableObjectNamespace, __StateRegistry, __makeAgent, __rehydrationViolation, type __JsonValue, type __BoundaryError } from "./runtime.js";

import { Line as __CommonsLine, Point as __CommonsPoint, origin } from "./shapes.js";

export type Line = __CommonsLine & { readonly __ctxBrand?: "canvas" };
export type Point = __CommonsPoint & { readonly __ctxBrand?: "canvas" };

export interface BoardState {
  readonly total: number;
  readonly last: Option<Line>;
}

const __BoardRegistry = new __StateRegistry();
function __zeroOfBoardState(): BoardState { return { total: 0, last: None }; }

function __rehydrateBoardState(s: BoardState, stored: BoardState): void {
  if (globalThis.Object.prototype.hasOwnProperty.call(stored, "total")) { const __r = ((__v) => typeof __v !== "number" ? Err({ kind: "StructuralMismatch", path: "total", expected: "safe integer", actual: typeof __v } as __BoundaryError) : globalThis.Number.isSafeInteger(__v) ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "total", expected: "safe integer", actual: String(__v) } as __BoundaryError))((s.total as unknown as __JsonValue)); if (__r.tag === "Err") throw __rehydrationViolation("Board", __r.error); (s as { -readonly [K in keyof typeof s]: (typeof s)[K] }).total = __r.value as unknown as (typeof s)["total"]; }
  if (globalThis.Object.prototype.hasOwnProperty.call(stored, "last")) { const __r = __deserialise_Option_Line((s.last as unknown as __JsonValue), "last"); if (__r.tag === "Err") throw __rehydrationViolation("Board", __r.error); (s as { -readonly [K in keyof typeof s]: (typeof s)[K] }).last = __r.value as unknown as (typeof s)["last"]; }
}

function __encodeBoardState(s: BoardState): globalThis.Record<string, unknown> {
  return { ...s, total: ((v: number) => { if (!globalThis.Number.isSafeInteger(v)) throw new globalThis.Error("Int outside the safe-integer range at boundary"); return v as __JsonValue; })(s.total), last: __serialise_Option_Line(s.last) };
}

export class Board {
  state: __DurableObjectState;
  constructor(state: __DurableObjectState) {
    this.state = state;
  }

  private async loadState(): globalThis.Promise<BoardState> {
    const stored = await this.state.storage.get<BoardState>("state");
    if (stored === undefined) return __zeroOfBoardState();
    const __merged = { ...__zeroOfBoardState(), ...stored };
    __rehydrateBoardState(__merged, stored);
    return __merged;
  }

  private async commitState(s: BoardState): globalThis.Promise<void> {
    await this.state.storage.put("state", __encodeBoardState(s));
  }

  async add(p: Point, deps: {}): globalThis.Promise<number> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const cur = __state.total;
      __state.total = cur + p.x + p.y;
      return __state.total;
    })();
    await this.commitState(__state);
    return __result;
  }

  async draw(l: Line, deps: {}): globalThis.Promise<number> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      __state.last = Some(l);
      return l.end.x - l.start.x;
    })();
    await this.commitState(__state);
    return __result;
  }

}

export function __makeBoard(key: string, env?: { BOARD?: __DurableObjectNamespace }): Board {
  return __makeAgent(__BoardRegistry, env?.BOARD, key, (state) => new Board(state));
}

export const api = {
  async call(deps: {}): globalThis.Promise<number> {
    const p = { x: 1, y: 2 };
    const moved = { ...p, x: 3 };
    const __r0 = await __makeBoard("svc").add(origin(), deps);
    const __r1 = await __makeBoard("svc").add(moved, deps);
    return __makeBoard("svc").draw({ start: p, end: { x: 9, y: 9 } }, deps);
  },
};

export function __resetAgents(): void {
  __BoardRegistry.reset();
}

export interface __CanvasDeps {
}

export function __makeSurface(deps: __CanvasDeps) {
  return {
    async api(): globalThis.Promise<number> {
      return api.call(deps);
    },
  };
}

export function __serialise_Line(value: Line): __JsonValue {
  return {
    start: __serialise_Point(value.start),
    end: __serialise_Point(value.end),
  };
}

export function __deserialise_Line(json: __JsonValue, path: string = "$"): Result<Line, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  const __r_start = __deserialise_Point(obj["start"], `${path}.start`);
  if (__r_start.tag === "Err") return __r_start;
  const __start = __r_start.value;
  const __r_end = __deserialise_Point(obj["end"], `${path}.end`);
  if (__r_end.tag === "Err") return __r_end;
  const __end = __r_end.value;
  return Ok({ start: __start, end: __end } as Line);
}

export function __serialise_Point(value: Point): __JsonValue {
  return {
    x: ((v: number) => { if (!globalThis.Number.isSafeInteger(v)) throw new globalThis.Error("Int outside the safe-integer range at boundary"); return v as __JsonValue; })(value.x),
    y: ((v: number) => { if (!globalThis.Number.isSafeInteger(v)) throw new globalThis.Error("Int outside the safe-integer range at boundary"); return v as __JsonValue; })(value.y),
  };
}

export function __deserialise_Point(json: __JsonValue, path: string = "$"): Result<Point, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  if (typeof obj["x"] !== "number") {
    return Err({ kind: "StructuralMismatch", path: `${path}.x`, expected: "number", actual: typeof obj["x"] });
  }
  if (!globalThis.Number.isSafeInteger(obj["x"])) {
    return Err({ kind: "StructuralMismatch", path: `${path}.x`, expected: "safe integer", actual: String(obj["x"]) });
  }
  const __x = obj["x"];
  if (typeof obj["y"] !== "number") {
    return Err({ kind: "StructuralMismatch", path: `${path}.y`, expected: "number", actual: typeof obj["y"] });
  }
  if (!globalThis.Number.isSafeInteger(obj["y"])) {
    return Err({ kind: "StructuralMismatch", path: `${path}.y`, expected: "safe integer", actual: String(obj["y"]) });
  }
  const __y = obj["y"];
  return Ok({ x: __x, y: __y } as Point);
}


export function __serialise_Option_Line(value: Option<Line>): __JsonValue {
  if (value.tag === "Some") return { kind: "Some", value: __serialise_Line(value.value) };
  return { kind: "None" };
}

function __option_value_Line(raw: __JsonValue, at: string): Result<unknown, __BoundaryError> {
  const __r_v = __deserialise_Line(raw, at);
  if (__r_v.tag === "Err") return __r_v;
  const __v = __r_v.value;
  return Ok(__v);
}

export function __deserialise_Option_Line(json: __JsonValue, path: string = "$"): Result<Option<Line>, __BoundaryError> {
  if (json === undefined || json === null) {
    return Ok(None as Option<Line>);
  }
  if (typeof json === "object" && !globalThis.Array.isArray(json)) {
    const obj = json as { [k: string]: __JsonValue };
    const __keys = globalThis.Object.keys(obj);
    if (obj["kind"] === "None" && __keys.length === 1) {
      return Ok(None as Option<Line>);
    }
    if (obj["kind"] === "Some" && __keys.length === 2 && "value" in obj) {
      const __t = __option_value_Line(obj["value"], `${path}.value`);
      if (__t.tag === "Err") {
        return __t;
      }
      return Ok(Some(__t.value as Line) as Option<Line>);
    }
  }
  const __b = __option_value_Line(json, path);
  if (__b.tag === "Ok") {
    return Ok(Some(__b.value as Line) as Option<Line>);
  }
  if (__b.error.kind === "StructuralMismatch" && __b.error.path === path) {
    return Err({ ...__b.error, expected: __b.error.expected + " | null | {\"kind\": \"None\"} | {\"kind\": \"Some\", \"value\": ...}" });
  }
  return __b;
}
