// Generated by bynkc — do not edit by hand.
// commons probe

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export type Outcome =
    { readonly tag: "Hit"; readonly score: number }
  | { readonly tag: "Miss" };

export const Outcome = {
  Hit: (score: number): Outcome => ({ tag: "Hit", score }),
  Miss: { tag: "Miss" } as Outcome,
};

export function helper(): Outcome {
  return Outcome.Hit(1);
}

export function check(x: boolean): boolean {
  return x && (() => { const __r0 = helper(); return __r0.tag === "Hit"; })();
}

