// Generated by bynkc — do not edit by hand.
// Worker entry point for context `hooks`.

import { Ok, Err, type Result, type __JsonValue, type __BoundaryError, __boundaryError, __matchPath, __httpResultToResponse, type __SecurityPolicy, __applySecurityHeaders, __verifySignatureHmacSha256 } from "../../runtime.js";
import { compose, type Env } from "./compose.js";
import * as handlers from "./handlers.js";

export default {
  async fetch(request: globalThis.Request, env: Env): globalThis.Promise<globalThis.Response> {
    const url = new globalThis.URL(request.url);
    const path = url.pathname;
    const method = request.method;
    const surface = compose(env);
    const __security_api: __SecurityPolicy = { nosniff: true, hstsMaxAgeSecs: null };
    try {
      if (path.startsWith("/_bynk/call/")) {
        const servicePath = path.slice("/_bynk/call/".length);
        switch (servicePath) {
          default:
            return new globalThis.Response("Not found", { status: 404 });
        }
      }

      {
        if (method === "POST" && path === "/hooks/event") {
          let __body_json: __JsonValue;
          let __raw: string;
          try {
            __raw = await request.text();
          } catch {
            return __applySecurityHeaders(new globalThis.Response(globalThis.JSON.stringify({ kind: "MalformedJson", details: "Invalid request body" }), { status: 400, headers: { "content-type": "application/json" } }), __security_api);
          }
          const __secret = (env as unknown as globalThis.Record<string, unknown>)["WEBHOOK_SECRET"] ?? (globalThis as { process?: { env?: globalThis.Record<string, unknown> } }).process?.env?.["WEBHOOK_SECRET"];
          if (typeof __secret !== "string") return __applySecurityHeaders(new globalThis.Response(null, { status: 401 }), __security_api);
          const __ts = request.headers.get("X-Timestamp");
          if (__ts === null) return __applySecurityHeaders(new globalThis.Response(null, { status: 401 }), __security_api);
          const __ok = await __verifySignatureHmacSha256(__raw, __secret, request.headers.get("X-Signature"), __ts, 300);
          if (!__ok) return __applySecurityHeaders(new globalThis.Response(null, { status: 401 }), __security_api);
          try {
            __body_json = globalThis.JSON.parse(__raw) as __JsonValue;
          } catch {
            return __applySecurityHeaders(new globalThis.Response(globalThis.JSON.stringify({ kind: "MalformedJson", details: "Invalid request body" }), { status: 400, headers: { "content-type": "application/json" } }), __security_api);
          }
          const __r_body = handlers.__deserialise_Event(__body_json, "$");
          if (__r_body.tag === "Err") return __applySecurityHeaders(new globalThis.Response(globalThis.JSON.stringify(__r_body.error), { status: 400, headers: { "content-type": "application/json" } }), __security_api);
          const body = __r_body.value;
          const result = await surface.http_POST_hooks_event(body);
          return __applySecurityHeaders(__httpResultToResponse(result, (__v: string) => __v as __JsonValue), __security_api);
        }
      }
      if (path === "/hooks/event") {
        const __status = method === "OPTIONS" ? 204 : 405;
        const __res = new globalThis.Response(null, { status: __status, headers: { allow: "OPTIONS, POST" } });
        return __applySecurityHeaders(__res, __security_api);
      }
      return new globalThis.Response("Not Found", { status: 404 });
    } catch {
      return new globalThis.Response("Internal Server Error", { status: 500 });
    }
  },
};
