// Generated by bynkc — do not edit by hand.
// commons money

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type __JsonValue, type __BoundaryError, type __ServiceBinding, __callService, __boundaryError } from "../runtime.js";

export type Amount = number & { readonly __brand: "Amount" };

export const Amount = {
  of(value: number): Result<Amount, ValidationError> {
    if (!globalThis.Number.isSafeInteger(value)) {
      return Err({ field: "Amount", message: "must be a safe integer", value });
    }
    if (!(value > 0)) {
      return Err({ field: "Amount", message: "must be positive", value });
    }
    return Ok(value as Amount);
  },
};

export function __serialise_Amount(value: Amount): __JsonValue {
  return value as unknown as number;
}

export function __deserialise_Amount(json: __JsonValue, path: string = "$"): Result<Amount, __BoundaryError> {
  if (typeof json !== "number") {
    return Err({ kind: "StructuralMismatch", path, expected: "number", actual: typeof json });
  }
  const validated = (typeof (Amount as unknown as { of?: (json: unknown) => Result<unknown, ValidationError> }).of === "function")
    ? (Amount as unknown as { of: (json: unknown) => Result<unknown, ValidationError> }).of(json)
    : (Ok(json as unknown as Amount) as Result<unknown, ValidationError>);
  if (validated.tag === "Err") {
    return Err({ kind: "RefinementViolation", path, violation: validated.error });
  }
  return Ok(validated.value as Amount);
}

