// Generated by bynkc — do not edit by hand.
// system test: shop.orders

import { Ok, Err, Some, None, callService, type Result, type Option, type ValidationError, type JsonError, type JsonValue, type BoundaryError, type ServiceBinding, responseToHttpResult, responseToHttpOutcome, responseToUnauthOutcome } from "../runtime.js";
import * as shop_orders from "../workers/shop-orders/handlers.js";
import worker_shop_orders from "../workers/shop-orders/index.js";
import * as shop_payment from "../workers/shop-payment/handlers.js";
import worker_shop_payment from "../workers/shop-payment/index.js";
import * as money from "./../money.js";

class ExpectationError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number, detail: string) {
    super(`${detail}\n  at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkExpectFailure(location: string, start: number, end: number, detail: string) {
  return new ExpectationError(location, start, end, detail);
}
function __bynkExpect(cond: boolean, location: string, start: number, end: number, detail: string): void {
  if (!cond) { throw __bynkExpectFailure(location, start, end, detail); }
}
function __bynkShow(v: unknown): string {
  try { return typeof v === "bigint" ? String(v) : (JSON.stringify(v) ?? String(v)); } catch { return String(v); }
}

function makeHarness() {
  const env_shop_orders: any = {};
  const env_shop_payment: any = {};
  env_shop_orders.SHOP_PAYMENT = { fetch: (req: Request) => worker_shop_payment.fetch(req, env_shop_payment) } as ServiceBinding;
  const rootEnv: any = {};
  rootEnv.SHOP_ORDERS = { fetch: (req: Request) => worker_shop_orders.fetch(req, env_shop_orders) } as ServiceBinding;
  rootEnv.SHOP_PAYMENT = { fetch: (req: Request) => worker_shop_payment.fetch(req, env_shop_payment) } as ServiceBinding;
  return { env: rootEnv };
}

async function test_small_order_authorises_across_the_wire() {
  try {
    const deps = makeHarness();
    const { cents, withFee } = money as any;
    const total = withFee(cents(1));
    if (!(total === 105)) { throw __bynkExpectFailure("checkout.bynk:15:12", 701, 713, "expect total == 105\n  expected: total == 105\n  actual:   " + __bynkShow((total)) + " == " + __bynkShow((105))); }
    const r = await callService(deps.env.SHOP_ORDERS, "place", total as JsonValue, shop_orders.deserialise_Result_Int_OrderError, "integration", "3a273aec9f70d0b4");
    if (!(r.tag === "Ok")) { throw __bynkExpectFailure("checkout.bynk:17:12", 763, 773, "expect r is Ok(_)"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

async function test_large_order_is_rejected_end_to_end() {
  try {
    const deps = makeHarness();
    const { cents, withFee } = money as any;
    const r = await callService(deps.env.SHOP_ORDERS, "place", 50000 as JsonValue, shop_orders.deserialise_Result_Int_OrderError, "integration", "3a273aec9f70d0b4");
    if (!(r.tag === "Err")) { throw __bynkExpectFailure("checkout.bynk:22:12", 874, 885, "expect r is Err(_)"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run(only?: string) {
  const results = [];
  const want = (n: string): boolean => only === undefined || only === n;
  if (want("small order authorises across the wire")) results.push({ name: "small order authorises across the wire", ...(await test_small_order_authorises_across_the_wire()) });
  if (want("large order is rejected end to end")) results.push({ name: "large order is rejected end to end", ...(await test_large_order_is_rejected_end_to_end()) });
  return results;
}
