// Generated by bynkc — do not edit by hand.
// context cart

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type __DurableObjectState, type __DurableObjectNamespace, __StateRegistry, __makeAgent, __rehydrationViolation, type __JsonValue, type __BoundaryError } from "./runtime.js";

export interface Item {
  readonly name: string;
  readonly qty: number;
}

export const Item = {
};

export interface CartState {
  readonly items: globalThis.Record<string, Item>;
}

const __CartRegistry = new __StateRegistry();
function __zeroOfCartState(): CartState { return { items: {} }; }

function __rehydrateCartState(s: CartState, stored: CartState): void {
  if (globalThis.Object.prototype.hasOwnProperty.call(stored, "items")) for (const __k of globalThis.Object.keys(s.items)) { const __r = __deserialise_Item((s.items[__k] as unknown as __JsonValue), "items"); if (__r.tag === "Err") throw __rehydrationViolation("Cart", __r.error); s.items[__k] = __r.value as unknown as (typeof s.items)[string]; }
  for (const __k of globalThis.Object.keys(s.items)) { const __r = ((__v) => typeof __v === "string" ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "items", expected: "string", actual: typeof __v } as __BoundaryError))((__k as unknown as __JsonValue)); if (__r.tag === "Err") throw __rehydrationViolation("Cart", __r.error); }
}

function __encodeCartState(s: CartState): globalThis.Record<string, unknown> {
  return { ...s, items: globalThis.Object.fromEntries(globalThis.Object.entries(s.items).map(([__k, __v]) => [__k, __serialise_Item(__v)])) };
}

export class Cart {
  state: __DurableObjectState;
  constructor(state: __DurableObjectState) {
    this.state = state;
  }

  private async loadState(): globalThis.Promise<CartState> {
    const stored = await this.state.storage.get<CartState>("state");
    if (stored === undefined) return __zeroOfCartState();
    const __merged = { ...__zeroOfCartState(), ...stored };
    __rehydrateCartState(__merged, stored);
    return __merged;
  }

  private async commitState(s: CartState): globalThis.Promise<void> {
    await this.state.storage.put("state", __encodeCartState(s));
  }

  async sumIfPresent(items: ReadonlyMap<string, number>, k: string, deps: {}): globalThis.Promise<number> {
    const __state = await this.loadState();
    const __r0 = ((__m: ReadonlyMap<string, number>, __k: string) => __m.has(__k) ? Some(__m.get(__k) as number) : None)(items, k);
    switch (__r0.tag) {
      case "Some": {
        const n = __r0.value;
        return n;
      }
      case "None": {
        return 0;
      }
    }
    throw new globalThis.Error("non-exhaustive match");
  }

}

export function __makeCart(key: string, env?: { CART?: __DurableObjectNamespace }): Cart {
  return __makeAgent(__CartRegistry, env?.CART, key, (state) => new Cart(state));
}

export function __resetAgents(): void {
  __CartRegistry.reset();
}

export function __serialise_Item(value: Item): __JsonValue {
  return {
    name: value.name as __JsonValue,
    qty: ((v: number) => { if (!globalThis.Number.isSafeInteger(v)) throw new globalThis.Error("Int outside the safe-integer range at boundary"); return v as __JsonValue; })(value.qty),
  };
}

export function __deserialise_Item(json: __JsonValue, path: string = "$"): Result<Item, __BoundaryError> {
  if (typeof json !== "object" || json === null || globalThis.Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: __JsonValue };
  if (typeof obj["name"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.name`, expected: "string", actual: typeof obj["name"] });
  }
  const __name = obj["name"];
  if (typeof obj["qty"] !== "number") {
    return Err({ kind: "StructuralMismatch", path: `${path}.qty`, expected: "number", actual: typeof obj["qty"] });
  }
  if (!globalThis.Number.isSafeInteger(obj["qty"])) {
    return Err({ kind: "StructuralMismatch", path: `${path}.qty`, expected: "safe integer", actual: String(obj["qty"]) });
  }
  const __qty = obj["qty"];
  return Ok({ name: __name, qty: __qty } as Item);
}

