// Generated by bynkc — do not edit by hand.
// test target: demo.opt

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, __bynkEq } from "../runtime.js";
import * as __ns_demo_opt from "./../demo/opt.js";

class ExpectationError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number, detail: string) {
    super(`${detail}\n  at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkExpectFailure(location: string, start: number, end: number, detail: string) {
  return new ExpectationError(location, start, end, detail);
}
function __bynkExpect(cond: boolean, location: string, start: number, end: number, detail: string): void {
  if (!cond) { throw __bynkExpectFailure(location, start, end, detail); }
}
function __bynkShow(v: unknown): string {
  try { return typeof v === "bigint" ? String(v) : (JSON.stringify(v) ?? String(v)); } catch { return String(v); }
}

function __makeTestDeps() {
  return {  };
}

// case tier: unit
async function test_the_issue_s_five_rows_decode() {
  try {
    const deps = {};
    const { Boxed, Holder, Name, Named, Nested, Pair, Repo, Wrapped, boxed, boxedRoundTrips, holder, holderRoundTrips, named, nested, nestedError, nestedRoundTrips, repo, repoError } = __ns_demo_opt;
    type Boxed = __ns_demo_opt.Boxed;
    type Holder = __ns_demo_opt.Holder;
    type Name = __ns_demo_opt.Name;
    type Named = __ns_demo_opt.Named;
    type Nested = __ns_demo_opt.Nested;
    type Pair = __ns_demo_opt.Pair;
    type Repo = __ns_demo_opt.Repo;
    type Wrapped = __ns_demo_opt.Wrapped;
    if (!(__bynkEq(repo("{\"repo\": \"a\"}"), Some({ repo: "a", description: None })))) { throw __bynkExpectFailure("tests/demo/opt.bynk:7:10", 127, 199, "expect repo(\"{\\\"repo\\\": \\\"a\\\"}\") == Some(Repo { repo: \"a\", description: None })\n  expected: repo(\"{\\\"repo\\\": \\\"a\\\"}\") == Some(Repo { repo: \"a\", description: None })\n  actual:   " + __bynkShow((repo("{\"repo\": \"a\"}"))) + " == " + __bynkShow((Some({ repo: "a", description: None })))); }
    if (!(__bynkEq(repo("{\"repo\": \"a\", \"description\": null}"), Some({ repo: "a", description: None })))) { throw __bynkExpectFailure("tests/demo/opt.bynk:8:10", 209, 304, "expect repo(\"{\\\"repo\\\": \\\"a\\\", \\\"description\\\": null}\") == Some(Repo { repo: \"a\", description: None })\n  expected: repo(\"{\\\"repo\\\": \\\"a\\\", \\\"description\\\": null}\") == Some(Repo { repo: \"a\", description: None })\n  actual:   " + __bynkShow((repo("{\"repo\": \"a\", \"description\": null}"))) + " == " + __bynkShow((Some({ repo: "a", description: None })))); }
    if (!(__bynkEq(repo("{\"repo\": \"a\", \"description\": \"d\"}"), Some({ repo: "a", description: Some("d") })))) { throw __bynkExpectFailure("tests/demo/opt.bynk:9:10", 314, 415, "expect repo(\"{\\\"repo\\\": \\\"a\\\", \\\"description\\\": \\\"d\\\"}\") == Some(Repo { repo: \"a\", description: Some(\"d\") })\n  expected: repo(\"{\\\"repo\\\": \\\"a\\\", \\\"description\\\": \\\"d\\\"}\") == Some(Repo { repo: \"a\", description: Some(\"d\") })\n  actual:   " + __bynkShow((repo("{\"repo\": \"a\", \"description\": \"d\"}"))) + " == " + __bynkShow((Some({ repo: "a", description: Some("d") })))); }
    if (!(__bynkEq(repo("{\"repo\": \"a\", \"description\": {\"kind\": \"Some\", \"value\": \"d\"}}"), Some({ repo: "a", description: Some("d") })))) { throw __bynkExpectFailure("tests/demo/opt.bynk:10:10", 425, 559, "expect repo(\"{\\\"repo\\\": \\\"a\\\", \\\"description\\\": {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": \\\"d\\\"}}\") == Some(Repo { repo: \"a\", description: Some(\"d\") })\n  expected: repo(\"{\\\"repo\\\": \\\"a\\\", \\\"description\\\": {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": \\\"d\\\"}}\") == Some(Repo { repo: \"a\", description: Some(\"d\") })\n  actual:   " + __bynkShow((repo("{\"repo\": \"a\", \"description\": {\"kind\": \"Some\", \"value\": \"d\"}}"))) + " == " + __bynkShow((Some({ repo: "a", description: Some("d") })))); }
    if (!(__bynkEq(repo("{\"repo\": \"a\", \"description\": {\"kind\": \"None\"}}"), Some({ repo: "a", description: None })))) { throw __bynkExpectFailure("tests/demo/opt.bynk:11:10", 569, 680, "expect repo(\"{\\\"repo\\\": \\\"a\\\", \\\"description\\\": {\\\"kind\\\": \\\"None\\\"}}\") == Some(Repo { repo: \"a\", description: None })\n  expected: repo(\"{\\\"repo\\\": \\\"a\\\", \\\"description\\\": {\\\"kind\\\": \\\"None\\\"}}\") == Some(Repo { repo: \"a\", description: None })\n  actual:   " + __bynkShow((repo("{\"repo\": \"a\", \"description\": {\"kind\": \"None\"}}"))) + " == " + __bynkShow((Some({ repo: "a", description: None })))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_bare_value_is_checked_as_the_inner_type() {
  try {
    const deps = {};
    const { Boxed, Holder, Name, Named, Nested, Pair, Repo, Wrapped, boxed, boxedRoundTrips, holder, holderRoundTrips, named, nested, nestedError, nestedRoundTrips, repo, repoError } = __ns_demo_opt;
    type Boxed = __ns_demo_opt.Boxed;
    type Holder = __ns_demo_opt.Holder;
    type Name = __ns_demo_opt.Name;
    type Named = __ns_demo_opt.Named;
    type Nested = __ns_demo_opt.Nested;
    type Pair = __ns_demo_opt.Pair;
    type Repo = __ns_demo_opt.Repo;
    type Wrapped = __ns_demo_opt.Wrapped;
    if (!(__bynkEq(repo("{\"repo\": \"a\", \"description\": 7}"), None))) { throw __bynkExpectFailure("tests/demo/opt.bynk:15:10", 744, 797, "expect repo(\"{\\\"repo\\\": \\\"a\\\", \\\"description\\\": 7}\") == None\n  expected: repo(\"{\\\"repo\\\": \\\"a\\\", \\\"description\\\": 7}\") == None\n  actual:   " + __bynkShow((repo("{\"repo\": \"a\", \"description\": 7}"))) + " == " + __bynkShow((None))); }
    if (!((named("{\"name\": \"x\"}").tag === "Some"))) { throw __bynkExpectFailure("tests/demo/opt.bynk:16:10", 807, 842, "expect named(\"{\\\"name\\\": \\\"x\\\"}\").isSome()"); }
    if (!(__bynkEq(named("{\"name\": \"\"}"), None))) { throw __bynkExpectFailure("tests/demo/opt.bynk:17:10", 852, 885, "expect named(\"{\\\"name\\\": \\\"\\\"}\") == None\n  expected: named(\"{\\\"name\\\": \\\"\\\"}\") == None\n  actual:   " + __bynkShow((named("{\"name\": \"\"}"))) + " == " + __bynkShow((None))); }
    if (!(__bynkEq(named("{\"name\": {\"kind\": \"Some\", \"value\": \"\"}}"), None))) { throw __bynkExpectFailure("tests/demo/opt.bynk:18:10", 895, 961, "expect named(\"{\\\"name\\\": {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": \\\"\\\"}}\") == None\n  expected: named(\"{\\\"name\\\": {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": \\\"\\\"}}\") == None\n  actual:   " + __bynkShow((named("{\"name\": {\"kind\": \"Some\", \"value\": \"\"}}"))) + " == " + __bynkShow((None))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_failed_bare_value_names_every_Option_form() {
  try {
    const deps = {};
    const { Boxed, Holder, Name, Named, Nested, Pair, Repo, Wrapped, boxed, boxedRoundTrips, holder, holderRoundTrips, named, nested, nestedError, nestedRoundTrips, repo, repoError } = __ns_demo_opt;
    type Boxed = __ns_demo_opt.Boxed;
    type Holder = __ns_demo_opt.Holder;
    type Name = __ns_demo_opt.Name;
    type Named = __ns_demo_opt.Named;
    type Nested = __ns_demo_opt.Nested;
    type Pair = __ns_demo_opt.Pair;
    type Repo = __ns_demo_opt.Repo;
    type Wrapped = __ns_demo_opt.Wrapped;
    if (!(repoError("{\"repo\": \"a\", \"description\": 7}") === "$.description: expected string | null | {\"kind\": \"None\"} | {\"kind\": \"Some\", \"value\": ...}, got number")) { throw __bynkExpectFailure("tests/demo/opt.bynk:22:10", 1027, 1194, "expect repoError(\"{\\\"repo\\\": \\\"a\\\", \\\"description\\\": 7}\") == \"$.description: expected string | null | {\\\"kind\\\": \\\"None\\\"} | {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": ...}, got number\"\n  expected: repoError(\"{\\\"repo\\\": \\\"a\\\", \\\"description\\\": 7}\") == \"$.description: expected string | null | {\\\"kind\\\": \\\"None\\\"} | {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": ...}, got number\"\n  actual:   " + __bynkShow((repoError("{\"repo\": \"a\", \"description\": 7}"))) + " == " + __bynkShow(("$.description: expected string | null | {\"kind\": \"None\"} | {\"kind\": \"Some\", \"value\": ...}, got number"))); }
    if (!(repoError("{\"repo\": \"a\", \"description\": {\"kind\": \"Some\", \"value\": 7}}") === "$.description.value: expected string, got number")) { throw __bynkExpectFailure("tests/demo/opt.bynk:23:10", 1204, 1341, "expect repoError(\"{\\\"repo\\\": \\\"a\\\", \\\"description\\\": {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": 7}}\") == \"$.description.value: expected string, got number\"\n  expected: repoError(\"{\\\"repo\\\": \\\"a\\\", \\\"description\\\": {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": 7}}\") == \"$.description.value: expected string, got number\"\n  actual:   " + __bynkShow((repoError("{\"repo\": \"a\", \"description\": {\"kind\": \"Some\", \"value\": 7}}"))) + " == " + __bynkShow(("$.description.value: expected string, got number"))); }
    if (!(nestedError("{\"n\": \"x\"}") === "$.n: expected number | null | {\"kind\": \"None\"} | {\"kind\": \"Some\", \"value\": ...}, got string")) { throw __bynkExpectFailure("tests/demo/opt.bynk:24:10", 1351, 1487, "expect nestedError(\"{\\\"n\\\": \\\"x\\\"}\") == \"$.n: expected number | null | {\\\"kind\\\": \\\"None\\\"} | {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": ...}, got string\"\n  expected: nestedError(\"{\\\"n\\\": \\\"x\\\"}\") == \"$.n: expected number | null | {\\\"kind\\\": \\\"None\\\"} | {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": ...}, got string\"\n  actual:   " + __bynkShow((nestedError("{\"n\": \"x\"}"))) + " == " + __bynkShow(("$.n: expected number | null | {\"kind\": \"None\"} | {\"kind\": \"Some\", \"value\": ...}, got string"))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_tagged_object_with_an_extra_key_is_a_bare_value() {
  try {
    const deps = {};
    const { Boxed, Holder, Name, Named, Nested, Pair, Repo, Wrapped, boxed, boxedRoundTrips, holder, holderRoundTrips, named, nested, nestedError, nestedRoundTrips, repo, repoError } = __ns_demo_opt;
    type Boxed = __ns_demo_opt.Boxed;
    type Holder = __ns_demo_opt.Holder;
    type Name = __ns_demo_opt.Name;
    type Named = __ns_demo_opt.Named;
    type Nested = __ns_demo_opt.Nested;
    type Pair = __ns_demo_opt.Pair;
    type Repo = __ns_demo_opt.Repo;
    type Wrapped = __ns_demo_opt.Wrapped;
    if (!(repoError("{\"repo\": \"a\", \"description\": {\"kind\": \"Some\", \"value\": \"d\", \"note\": \"x\"}}") === "$.description: expected string | null | {\"kind\": \"None\"} | {\"kind\": \"Some\", \"value\": ...}, got object")) { throw __bynkExpectFailure("tests/demo/opt.bynk:30:10", 1704, 1925, "expect repoError(\"{\\\"repo\\\": \\\"a\\\", \\\"description\\\": {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": \\\"d\\\", \\\"note\\\": \\\"x\\\"}}\") == \"$.description: expected string | null | {\\\"kind\\\": \\\"None\\\"} | {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": ...}, got object\"\n  expected: repoError(\"{\\\"repo\\\": \\\"a\\\", \\\"description\\\": {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": \\\"d\\\", \\\"note\\\": \\\"x\\\"}}\") == \"$.description: expected string | null | {\\\"kind\\\": \\\"None\\\"} | {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": ...}, got object\"\n  actual:   " + __bynkShow((repoError("{\"repo\": \"a\", \"description\": {\"kind\": \"Some\", \"value\": \"d\", \"note\": \"x\"}}"))) + " == " + __bynkShow(("$.description: expected string | null | {\"kind\": \"None\"} | {\"kind\": \"Some\", \"value\": ...}, got object"))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_Option_Option_Int____tagged_forms_win__bare_forms_nest() {
  try {
    const deps = {};
    const { Boxed, Holder, Name, Named, Nested, Pair, Repo, Wrapped, boxed, boxedRoundTrips, holder, holderRoundTrips, named, nested, nestedError, nestedRoundTrips, repo, repoError } = __ns_demo_opt;
    type Boxed = __ns_demo_opt.Boxed;
    type Holder = __ns_demo_opt.Holder;
    type Name = __ns_demo_opt.Name;
    type Named = __ns_demo_opt.Named;
    type Nested = __ns_demo_opt.Nested;
    type Pair = __ns_demo_opt.Pair;
    type Repo = __ns_demo_opt.Repo;
    type Wrapped = __ns_demo_opt.Wrapped;
    if (!(__bynkEq(nested("{}"), Some({ n: None })))) { throw __bynkExpectFailure("tests/demo/opt.bynk:34:10", 2002, 2042, "expect nested(\"{}\") == Some(Nested { n: None })\n  expected: nested(\"{}\") == Some(Nested { n: None })\n  actual:   " + __bynkShow((nested("{}"))) + " == " + __bynkShow((Some({ n: None })))); }
    if (!(__bynkEq(nested("{\"n\": null}"), Some({ n: None })))) { throw __bynkExpectFailure("tests/demo/opt.bynk:35:10", 2052, 2103, "expect nested(\"{\\\"n\\\": null}\") == Some(Nested { n: None })\n  expected: nested(\"{\\\"n\\\": null}\") == Some(Nested { n: None })\n  actual:   " + __bynkShow((nested("{\"n\": null}"))) + " == " + __bynkShow((Some({ n: None })))); }
    if (!(__bynkEq(nested("{\"n\": 1}"), Some({ n: Some(Some(1)) })))) { throw __bynkExpectFailure("tests/demo/opt.bynk:36:10", 2113, 2170, "expect nested(\"{\\\"n\\\": 1}\") == Some(Nested { n: Some(Some(1)) })\n  expected: nested(\"{\\\"n\\\": 1}\") == Some(Nested { n: Some(Some(1)) })\n  actual:   " + __bynkShow((nested("{\"n\": 1}"))) + " == " + __bynkShow((Some({ n: Some(Some(1)) })))); }
    if (!(__bynkEq(nested("{\"n\": {\"kind\": \"None\"}}"), Some({ n: None })))) { throw __bynkExpectFailure("tests/demo/opt.bynk:37:10", 2180, 2247, "expect nested(\"{\\\"n\\\": {\\\"kind\\\": \\\"None\\\"}}\") == Some(Nested { n: None })\n  expected: nested(\"{\\\"n\\\": {\\\"kind\\\": \\\"None\\\"}}\") == Some(Nested { n: None })\n  actual:   " + __bynkShow((nested("{\"n\": {\"kind\": \"None\"}}"))) + " == " + __bynkShow((Some({ n: None })))); }
    if (!(__bynkEq(nested("{\"n\": {\"kind\": \"Some\", \"value\": {\"kind\": \"None\"}}}"), Some({ n: Some(None) })))) { throw __bynkExpectFailure("tests/demo/opt.bynk:38:10", 2257, 2363, "expect nested(\"{\\\"n\\\": {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": {\\\"kind\\\": \\\"None\\\"}}}\") == Some(Nested { n: Some(None) })\n  expected: nested(\"{\\\"n\\\": {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": {\\\"kind\\\": \\\"None\\\"}}}\") == Some(Nested { n: Some(None) })\n  actual:   " + __bynkShow((nested("{\"n\": {\"kind\": \"Some\", \"value\": {\"kind\": \"None\"}}}"))) + " == " + __bynkShow((Some({ n: Some(None) })))); }
    if (!(__bynkEq(nested("{\"n\": {\"kind\": \"Some\", \"value\": null}}"), Some({ n: Some(None) })))) { throw __bynkExpectFailure("tests/demo/opt.bynk:39:10", 2373, 2463, "expect nested(\"{\\\"n\\\": {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": null}}\") == Some(Nested { n: Some(None) })\n  expected: nested(\"{\\\"n\\\": {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": null}}\") == Some(Nested { n: Some(None) })\n  actual:   " + __bynkShow((nested("{\"n\": {\"kind\": \"Some\", \"value\": null}}"))) + " == " + __bynkShow((Some({ n: Some(None) })))); }
    if (!(__bynkEq(nested("{\"n\": {\"kind\": \"Some\", \"value\": 1}}"), Some({ n: Some(Some(1)) })))) { throw __bynkExpectFailure("tests/demo/opt.bynk:40:10", 2473, 2563, "expect nested(\"{\\\"n\\\": {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": 1}}\") == Some(Nested { n: Some(Some(1)) })\n  expected: nested(\"{\\\"n\\\": {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": 1}}\") == Some(Nested { n: Some(Some(1)) })\n  actual:   " + __bynkShow((nested("{\"n\": {\"kind\": \"Some\", \"value\": 1}}"))) + " == " + __bynkShow((Some({ n: Some(Some(1)) })))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_record_with_kind_and_value_fields__the_tagged_reading_wins() {
  try {
    const deps = {};
    const { Boxed, Holder, Name, Named, Nested, Pair, Repo, Wrapped, boxed, boxedRoundTrips, holder, holderRoundTrips, named, nested, nestedError, nestedRoundTrips, repo, repoError } = __ns_demo_opt;
    type Boxed = __ns_demo_opt.Boxed;
    type Holder = __ns_demo_opt.Holder;
    type Name = __ns_demo_opt.Name;
    type Named = __ns_demo_opt.Named;
    type Nested = __ns_demo_opt.Nested;
    type Pair = __ns_demo_opt.Pair;
    type Repo = __ns_demo_opt.Repo;
    type Wrapped = __ns_demo_opt.Wrapped;
    if (!(__bynkEq(boxed("{\"p\": {\"kind\": \"x\", \"value\": 1}}"), Some({ p: Some({ kind: "x", value: 1 }) })))) { throw __bynkExpectFailure("tests/demo/opt.bynk:44:10", 2646, 2752, "expect boxed(\"{\\\"p\\\": {\\\"kind\\\": \\\"x\\\", \\\"value\\\": 1}}\") == Some(Boxed { p: Some(Pair { kind: \"x\", value: 1 }) })\n  expected: boxed(\"{\\\"p\\\": {\\\"kind\\\": \\\"x\\\", \\\"value\\\": 1}}\") == Some(Boxed { p: Some(Pair { kind: \"x\", value: 1 }) })\n  actual:   " + __bynkShow((boxed("{\"p\": {\"kind\": \"x\", \"value\": 1}}"))) + " == " + __bynkShow((Some({ p: Some({ kind: "x", value: 1 }) })))); }
    if (!(__bynkEq(boxed("{\"p\": {\"kind\": \"Some\", \"value\": 1}}"), None))) { throw __bynkExpectFailure("tests/demo/opt.bynk:45:10", 2762, 2822, "expect boxed(\"{\\\"p\\\": {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": 1}}\") == None\n  expected: boxed(\"{\\\"p\\\": {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": 1}}\") == None\n  actual:   " + __bynkShow((boxed("{\"p\": {\"kind\": \"Some\", \"value\": 1}}"))) + " == " + __bynkShow((None))); }
    if (!(__bynkEq(boxed("{\"p\": {\"kind\": \"Some\", \"value\": {\"kind\": \"Some\", \"value\": 1}}}"), Some({ p: Some({ kind: "Some", value: 1 }) })))) { throw __bynkExpectFailure("tests/demo/opt.bynk:46:10", 2832, 2977, "expect boxed(\"{\\\"p\\\": {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": 1}}}\") == Some(Boxed { p: Some(Pair { kind: \"Some\", value: 1 }) })\n  expected: boxed(\"{\\\"p\\\": {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": 1}}}\") == Some(Boxed { p: Some(Pair { kind: \"Some\", value: 1 }) })\n  actual:   " + __bynkShow((boxed("{\"p\": {\"kind\": \"Some\", \"value\": {\"kind\": \"Some\", \"value\": 1}}}"))) + " == " + __bynkShow((Some({ p: Some({ kind: "Some", value: 1 }) })))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_a_kind_tagged_sum_decodes_bare_or_tagged() {
  try {
    const deps = {};
    const { Boxed, Holder, Name, Named, Nested, Pair, Repo, Wrapped, boxed, boxedRoundTrips, holder, holderRoundTrips, named, nested, nestedError, nestedRoundTrips, repo, repoError } = __ns_demo_opt;
    type Boxed = __ns_demo_opt.Boxed;
    type Holder = __ns_demo_opt.Holder;
    type Name = __ns_demo_opt.Name;
    type Named = __ns_demo_opt.Named;
    type Nested = __ns_demo_opt.Nested;
    type Pair = __ns_demo_opt.Pair;
    type Repo = __ns_demo_opt.Repo;
    type Wrapped = __ns_demo_opt.Wrapped;
    if (!(__bynkEq(holder("{\"w\": {\"kind\": \"Wrap\", \"value\": 3}}"), Some({ w: Some(Wrapped.Wrap(3)) })))) { throw __bynkExpectFailure("tests/demo/opt.bynk:50:10", 3040, 3130, "expect holder(\"{\\\"w\\\": {\\\"kind\\\": \\\"Wrap\\\", \\\"value\\\": 3}}\") == Some(Holder { w: Some(Wrap(3)) })\n  expected: holder(\"{\\\"w\\\": {\\\"kind\\\": \\\"Wrap\\\", \\\"value\\\": 3}}\") == Some(Holder { w: Some(Wrap(3)) })\n  actual:   " + __bynkShow((holder("{\"w\": {\"kind\": \"Wrap\", \"value\": 3}}"))) + " == " + __bynkShow((Some({ w: Some(Wrapped.Wrap(3)) })))); }
    if (!(__bynkEq(holder("{\"w\": {\"kind\": \"Empty\"}}"), Some({ w: Some(Wrapped.Empty) })))) { throw __bynkExpectFailure("tests/demo/opt.bynk:51:10", 3140, 3215, "expect holder(\"{\\\"w\\\": {\\\"kind\\\": \\\"Empty\\\"}}\") == Some(Holder { w: Some(Empty) })\n  expected: holder(\"{\\\"w\\\": {\\\"kind\\\": \\\"Empty\\\"}}\") == Some(Holder { w: Some(Empty) })\n  actual:   " + __bynkShow((holder("{\"w\": {\"kind\": \"Empty\"}}"))) + " == " + __bynkShow((Some({ w: Some(Wrapped.Empty) })))); }
    if (!(__bynkEq(holder("{\"w\": {\"kind\": \"Some\", \"value\": {\"kind\": \"Wrap\", \"value\": 3}}}"), Some({ w: Some(Wrapped.Wrap(3)) })))) { throw __bynkExpectFailure("tests/demo/opt.bynk:52:10", 3225, 3348, "expect holder(\"{\\\"w\\\": {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": {\\\"kind\\\": \\\"Wrap\\\", \\\"value\\\": 3}}}\") == Some(Holder { w: Some(Wrap(3)) })\n  expected: holder(\"{\\\"w\\\": {\\\"kind\\\": \\\"Some\\\", \\\"value\\\": {\\\"kind\\\": \\\"Wrap\\\", \\\"value\\\": 3}}}\") == Some(Holder { w: Some(Wrap(3)) })\n  actual:   " + __bynkShow((holder("{\"w\": {\"kind\": \"Some\", \"value\": {\"kind\": \"Wrap\", \"value\": 3}}}"))) + " == " + __bynkShow((Some({ w: Some(Wrapped.Wrap(3)) })))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

// case tier: unit
async function test_what_Json_encode_writes_decodes_back_to_the_same_value() {
  try {
    const deps = {};
    const { Boxed, Holder, Name, Named, Nested, Pair, Repo, Wrapped, boxed, boxedRoundTrips, holder, holderRoundTrips, named, nested, nestedError, nestedRoundTrips, repo, repoError } = __ns_demo_opt;
    type Boxed = __ns_demo_opt.Boxed;
    type Holder = __ns_demo_opt.Holder;
    type Name = __ns_demo_opt.Name;
    type Named = __ns_demo_opt.Named;
    type Nested = __ns_demo_opt.Nested;
    type Pair = __ns_demo_opt.Pair;
    type Repo = __ns_demo_opt.Repo;
    type Wrapped = __ns_demo_opt.Wrapped;
    if (!(nestedRoundTrips({ n: None }))) { throw __bynkExpectFailure("tests/demo/opt.bynk:56:10", 3425, 3461, "expect nestedRoundTrips(Nested { n: None })"); }
    if (!(nestedRoundTrips({ n: Some(None) }))) { throw __bynkExpectFailure("tests/demo/opt.bynk:57:10", 3471, 3513, "expect nestedRoundTrips(Nested { n: Some(None) })"); }
    if (!(nestedRoundTrips({ n: Some(Some(1)) }))) { throw __bynkExpectFailure("tests/demo/opt.bynk:58:10", 3523, 3568, "expect nestedRoundTrips(Nested { n: Some(Some(1)) })"); }
    if (!(boxedRoundTrips({ p: None }))) { throw __bynkExpectFailure("tests/demo/opt.bynk:59:10", 3578, 3612, "expect boxedRoundTrips(Boxed { p: None })"); }
    if (!(boxedRoundTrips({ p: Some({ kind: "Some", value: 1 }) }))) { throw __bynkExpectFailure("tests/demo/opt.bynk:60:10", 3622, 3689, "expect boxedRoundTrips(Boxed { p: Some(Pair { kind: \"Some\", value: 1 }) })"); }
    if (!(boxedRoundTrips({ p: Some({ kind: "None", value: 2 }) }))) { throw __bynkExpectFailure("tests/demo/opt.bynk:61:10", 3699, 3766, "expect boxedRoundTrips(Boxed { p: Some(Pair { kind: \"None\", value: 2 }) })"); }
    if (!(holderRoundTrips({ w: None }))) { throw __bynkExpectFailure("tests/demo/opt.bynk:62:10", 3776, 3812, "expect holderRoundTrips(Holder { w: None })"); }
    if (!(holderRoundTrips({ w: Some(Wrapped.Wrap(3)) }))) { throw __bynkExpectFailure("tests/demo/opt.bynk:63:10", 3822, 3867, "expect holderRoundTrips(Holder { w: Some(Wrap(3)) })"); }
    if (!(holderRoundTrips({ w: Some(Wrapped.Empty) }))) { throw __bynkExpectFailure("tests/demo/opt.bynk:64:10", 3877, 3920, "expect holderRoundTrips(Holder { w: Some(Empty) })"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run(only?: string) {
  const results = [];
  const want = (n: string): boolean => only === undefined || only === n;
  if (want("the issue's five rows decode")) results.push({ name: "the issue's five rows decode", ...(await test_the_issue_s_five_rows_decode()) });
  if (want("a bare value is checked as the inner type")) results.push({ name: "a bare value is checked as the inner type", ...(await test_a_bare_value_is_checked_as_the_inner_type()) });
  if (want("a failed bare value names every Option form")) results.push({ name: "a failed bare value names every Option form", ...(await test_a_failed_bare_value_names_every_Option_form()) });
  if (want("a tagged object with an extra key is a bare value")) results.push({ name: "a tagged object with an extra key is a bare value", ...(await test_a_tagged_object_with_an_extra_key_is_a_bare_value()) });
  if (want("Option[Option[Int]]: tagged forms win, bare forms nest")) results.push({ name: "Option[Option[Int]]: tagged forms win, bare forms nest", ...(await test_Option_Option_Int____tagged_forms_win__bare_forms_nest()) });
  if (want("a record with kind and value fields: the tagged reading wins")) results.push({ name: "a record with kind and value fields: the tagged reading wins", ...(await test_a_record_with_kind_and_value_fields__the_tagged_reading_wins()) });
  if (want("a kind-tagged sum decodes bare or tagged")) results.push({ name: "a kind-tagged sum decodes bare or tagged", ...(await test_a_kind_tagged_sum_decodes_bare_or_tagged()) });
  if (want("what Json.encode writes decodes back to the same value")) results.push({ name: "what Json.encode writes decodes back to the same value", ...(await test_what_Json_encode_writes_decodes_back_to_the_same_value()) });
  return results;
}
